import type { GridPage } from '@/components/shared/AdvancedDataGrid';
export type ShipmentMode='OrderBasedTask'|'StockBasedTask'|'StockBasedDirect'|'OrderBasedDirect';
export interface ShipmentPolicy{id:number;branchCode:string;allowOrderBasedTask:boolean;allowStockBasedTask:boolean;allowOrderBasedDirect:boolean;allowStockBasedDirect:boolean;requireApproval:boolean;requireAssigneeForTask:boolean;allowMultipleAssignees:boolean;autoReleaseTaskBased:boolean;allowPartialPicking:boolean;allowPartialShipment:boolean;requireSourceLocation:boolean;requireShipmentInformation:boolean;requireLoadingConfirmation:boolean;autoPostErpAfterApproval:boolean;minimumFulfillmentPercent:number;overPickTolerancePercent:number;reservationPolicy:'None'|'OnCreate'|'OnRelease';packingPolicy:'NotRequired'|'Optional'|'Required';shortagePolicy:'Block'|'AllowPartial'|'RequireApproval';overPickPolicy:'Block'|'AllowWithinTolerance'|'RequireApproval'}
export interface ShipmentOrderHeader{mode:string;orderNumber:string;orderId?:number;customerCode?:string;customerName?:string;orderDate?:string;availableQuantity?:number;projectCode?:string}
export interface ShipmentOrderLine extends ShipmentOrderHeader{orderId:number;stockCode?:string;stockName?:string;yapCode?:string;yapDescription?:string;orderedQuantity?:number;deliveredQuantity?:number}
export interface ShipmentGridRow{id:number;branchCode:string;documentNo:string;documentDate:string;initiationMode:ShipmentMode;status:string;approvalStatus:string;erpIntegrationStatus:string;customerId:number;customerCode:string;customerName?:string;sourceWarehouseId:number;sourceWarehouseCode:number;sourceWarehouseName:string;lineCount:number;requestedQuantity:number;pickedQuantity:number;packedQuantity:number;loadedQuantity:number;shippedQuantity:number;priority:number;plannedShipmentAtUtc?:string;createdBy?:number;createdDate?:string;updatedBy?:number;updatedDate?:string}
export interface ShipmentDetailLine{id:number;lineNo:number;stockId:number;stockCode:string;stockName?:string;yapCode?:string;unitCode:string;requestedQuantity:number;reservedQuantity:number;pickedQuantity:number;packedQuantity:number;loadedQuantity:number;shippedQuantity:number;status:string;trackingCount:number;trackingType:'None'|'Lot'|'Serial'|'LotAndSerial';requireHandlingUnit:boolean;projectCode?:string}
export interface ShipmentDetail{header:ShipmentGridRow;lines:ShipmentDetailLine[];rowVersion:string;draft:{stagingLocationId?:number;loadingLocationId?:number;externalReferenceNo?:string;isEDispatch:boolean;carrierCode?:string;carrierName?:string;vehiclePlate?:string;trailerPlate?:string;driverName?:string;sealNo?:string;description?:string;projectCode?:string;costCenterCode?:string;movementTypeCode?:string;exitLocationCode?:string}}
export interface UpdateShipmentDraft{rowVersion:string;documentDate:string;stagingLocationId:number|null;loadingLocationId:number|null;plannedShipmentAtUtc:string|null;priority:number;externalReferenceNo:string|null;isEDispatch:boolean;carrierCode:string|null;carrierName:string|null;vehiclePlate:string|null;trailerPlate:string|null;driverName:string|null;sealNo:string|null;description:string|null}
export interface ShipmentResult{id:number;documentNo:string;lineCount:number;requestedQuantity:number;replayed:boolean;taskId?:number;taskNo?:string}
export type ShipmentPage=GridPage<ShipmentGridRow>;
