import i18n, { normalizeLanguage } from './i18n';

const KNOWN_ENUM_VALUES = new Set([
  'Accepted', 'AdvanceShippingNotice', 'AfterAllApprovals', 'AfterQualityApproval',
  'AfterReceipt', 'AfterReceiptApproval', 'All', 'AllowPartial',
  'AllowWithinTolerance', 'AllowWithReason', 'AlphaNumeric', 'And', 'Api',
  'Approval', 'ApprovalRequired', 'Approved', 'Arrived', 'Assigned',
  'AutoWhenComplete', 'Available', 'AwaitingApproval', 'Bag', 'BarcodeScan',
  'Block', 'Box', 'BranchDefault', 'Cancelled', 'CheckedIn', 'Closed',
  'CommitUncertain', 'Completed', 'Consumed', 'Contains', 'Converted', 'Crate',
  'Created', 'CustomerReturn', 'CustomerReturnOrder', 'Damaged', 'Date', 'Direct',
  'DirectReceipt', 'DirectTransfer', 'Dispatch', 'Document', 'DocumentNo', 'Draft',
  'Drum', 'ElectronicWaybill', 'EndsWith', 'Envelope', 'Equals', 'ErpIntegration',
  'ErpOrderBased', 'EveryNthHandlingUnit', 'Expected', 'Failed', 'Field',
  'FixedQuantity', 'FourDigit', 'Generated', 'GenerateOnReceipt', 'Global',
  'GoodsReceipt', 'GreaterThan', 'GreaterThanOrEqual', 'Gs1', 'Hold', 'Immediate',
  'Import', 'Imported', 'Inbound', 'InProgress', 'Inspected',
  'InspectionInProgress', 'InspectionRequired', 'InternalRequest',
  'InterWarehouseTransfer', 'IsNotNull', 'IsNull', 'LessThan',
  'LessThanOrEqual', 'LinkedToReceipt', 'Literal', 'Load', 'Loaded', 'Loading',
  'Location', 'LocationCode', 'Logistics', 'Lookup', 'Lost', 'Lot', 'LotAndSerial',
  'LotNo', 'Lower', 'ManagerApproval', 'Manual', 'Missing', 'Netsis', 'NoCheck',
  'None', 'NotAllowed', 'NotApplicable', 'NotContains', 'NotCreated', 'NotEquals',
  'NotRequired', 'Numeric', 'Observer', 'OnClose', 'OnCreate',
  'OneSerialPerBaseUnit', 'OneSerialPerLine', 'OneStep', 'OnRelease', 'Open',
  'Operation', 'Optional', 'Or', 'OrderBasedDirect', 'OrderBasedDirectReceipt',
  'OrderBasedDirectTransfer', 'OrderBasedTask', 'OrderlessDirectReceipt',
  'OrderlessTask', 'Other', 'Outbound', 'Owner', 'Pack', 'Packed', 'Packing',
  'Pallet', 'PartiallyApproved', 'PartiallyCompleted', 'PartiallyConsumed',
  'PartiallyConverted', 'PartiallyDecided', 'PartiallyPicked', 'PartiallyPrinted',
  'PartiallyProcessed', 'PartiallyPutaway', 'PartiallyReadyForReceipt', 'PartiallyReceived', 'Passed', 'Paused',
  'Pending', 'Percentage', 'Pick', 'Picked', 'Picking', 'Placed', 'Planned',
  'Posted', 'PreGenerate', 'PreGeneratedLabel', 'Printed', 'Processed',
  'Processing', 'Product', 'ProductionOrder', 'ProductionReturn', 'ProductLot',
  'ProductSerial', 'PurchaseOrder', 'Putaway', 'Quality', 'QualityCheck',
  'QualityMove', 'Quarantine', 'Quarantined', 'QuickCheck', 'ReadyForReceipt',
  'Receive', 'Received', 'Receiving', 'Reject', 'Rejected', 'Released',
  'Replenishment', 'RequireApproval', 'Required', 'Reserved',
  'ReturnableContainer', 'Returned', 'ReturnToSupplier', 'ReturnToWarehouse',
  'Reversed', 'SacMalKabul', 'SacPanel', 'Sequence', 'Serial', 'SerialLot',
  'SerialNo', 'Ship', 'Shipment', 'Shipped', 'ShortClosed', 'SideBySide', 'Sscc',
  'Stacked', 'StartsWith', 'SteelPlate', 'Stock', 'StockAndYapCode',
  'StockBasedDirect', 'StockBasedTask', 'StockCode', 'StockGroup', 'Succeeded',
  'Supervisor', 'SupplierLabel', 'SupplierWaybill', 'TransferIn', 'TransferOrder',
  'Transit', 'TwoDigit', 'TwoStepTransit', 'Unassigned', 'UnplannedTask', 'Upper',
  'UpperAlphaNumeric', 'Void', 'Voided', 'WarehouseCode', 'WarehouseIssue',
  'WarehouseOutbound', 'WarehouseReceipt', 'WarehouseTransfer', 'WithinTolerance',
  'Worker', 'YapCode', 'User', 'Manager', 'Admin', 'superadmin', 'Running',
  'TriggerFailed', 'QualityHold', 'InTransit', 'AwaitingHandover', 'CompletedWithShortage',
]);

const TR_ENUM_LABELS: Record<string, string> = {
  Accepted: 'Kabul Edildi',
  AdvanceShippingNotice: 'Ön Sevkiyat Bildirimi',
  AfterAllApprovals: 'Tüm Onaylardan Sonra',
  AfterQualityApproval: 'Kalite Onayından Sonra',
  AfterReceipt: 'Kabulden Sonra',
  AfterReceiptApproval: 'Mal Kabul Onayından Sonra',
  All: 'Tümü',
  AllowPartial: 'Kısmi İşleme İzin Ver',
  AllowWithinTolerance: 'Tolerans İçinde İzin Ver',
  AllowWithReason: 'Neden Girilerek İzin Ver',
  AlphaNumeric: 'Alfanümerik',
  And: 'Tümü',
  Api: 'API',
  Approval: 'Onay',
  ApprovalRequired: 'Onay Gerekli',
  Approved: 'Onaylandı',
  Arrived: 'Geldi',
  Assigned: 'Atandı',
  AutoWhenComplete: 'Tamamlanınca Otomatik',
  Available: 'Kullanılabilir',
  AwaitingApproval: 'Onay Bekliyor',
  AwaitingHandover: 'Teslim Onayı Bekliyor',
  Bag: 'Torba',
  BarcodeScan: 'Barkod Okutma',
  Block: 'Engelle',
  Box: 'Kutu',
  BranchDefault: 'Şube Varsayılanı',
  Cancelled: 'İptal Edildi',
  CheckedIn: 'Araç Girişi Yapıldı',
  Closed: 'Kapatıldı',
  CommitUncertain: 'Aktarım Sonucu Belirsiz',
  Completed: 'Tamamlandı',
  CompletedWithShortage: 'Eksik Tamamlandı',
  Consumed: 'Kullanıldı',
  Contains: 'İçerir',
  Converted: 'Dönüştürüldü',
  Crate: 'Kasa',
  Created: 'Oluşturuldu',
  CustomerReturn: 'Müşteri İadesi',
  CustomerReturnOrder: 'Müşteri İade Siparişi',
  Damaged: 'Hasarlı',
  Date: 'Tarih',
  Direct: 'Doğrudan',
  DirectReceipt: 'Doğrudan Mal Kabul',
  DirectTransfer: 'Doğrudan Transfer',
  Dispatch: 'Sevk',
  Document: 'Belge',
  DocumentNo: 'Belge Numarası',
  Draft: 'Taslak',
  Drum: 'Varil',
  ElectronicWaybill: 'E-İrsaliye',
  EndsWith: 'İle Biter',
  Envelope: 'Zarf',
  Equals: 'Eşittir',
  ErpIntegration: 'ERP Entegrasyonu',
  ErpOrderBased: 'ERP Siparişine İstinaden',
  EveryNthHandlingUnit: 'Her N. Taşıma Birimi',
  Expected: 'Bekleniyor',
  Failed: 'Başarısız',
  Field: 'Alan',
  FixedQuantity: 'Sabit Miktar',
  FourDigit: 'Dört Haneli',
  Generated: 'Oluşturuldu',
  GenerateOnReceipt: 'Mal Kabulde Oluştur',
  Global: 'Genel',
  GoodsReceipt: 'Mal Kabul',
  GreaterThan: 'Büyüktür',
  GreaterThanOrEqual: 'Büyük veya Eşittir',
  Gs1: 'GS1',
  Hold: 'Beklet',
  Immediate: 'Hemen',
  Import: 'İçe Aktarım',
  Imported: 'İçe Aktarıldı',
  Inbound: 'Giriş',
  InProgress: 'Devam Ediyor',
  Inspected: 'İncelendi',
  InspectionInProgress: 'İnceleme Devam Ediyor',
  InspectionRequired: 'İnceleme Gerekli',
  QualityDisposition: 'Kalite Dağıtımı',
  InternalRequest: 'Dahili Talep',
  InterWarehouseTransfer: 'Depolar Arası Transfer',
  IsNotNull: 'Boş Değildir',
  IsNull: 'Boştur',
  LessThan: 'Küçüktür',
  LessThanOrEqual: 'Küçük veya Eşittir',
  LinkedToReceipt: 'Mal Kabule Bağlandı',
  Literal: 'Sabit Metin',
  Load: 'Yükleme',
  Loaded: 'Yüklendi',
  Loading: 'Yükleniyor',
  Location: 'Raf',
  LocationCode: 'Raf Kodu',
  Logistics: 'Lojistik',
  Lookup: 'Sorgulama',
  Lost: 'Kayıp',
  Lot: 'Lot',
  LotAndSerial: 'Lot ve Seri',
  LotNo: 'Lot Numarası',
  Lower: 'Küçük Harf',
  ManagerApproval: 'Yönetici Onayı',
  Manual: 'Manuel',
  Missing: 'Eksik',
  Netsis: 'Netsis',
  NoCheck: 'Kontrol Yok',
  None: 'Yok',
  NotAllowed: 'İzin Verilmez',
  NotApplicable: 'Uygulanamaz',
  NotContains: 'İçermez',
  NotCreated: 'Oluşturulmadı',
  NotEquals: 'Eşit Değildir',
  NotRequired: 'Gerekmiyor',
  Numeric: 'Sayısal',
  Observer: 'Gözlemci',
  OnClose: 'Kapatıldığında',
  OnCreate: 'Oluşturulduğunda',
  OneSerialPerBaseUnit: 'Ana Birim Başına Bir Seri',
  OneSerialPerLine: 'Satır Başına Bir Seri',
  OneStep: 'Tek Aşamalı',
  OnRelease: 'Serbest Bırakıldığında',
  Open: 'Açık',
  Operation: 'Operasyon',
  Optional: 'İsteğe Bağlı',
  Or: 'Herhangi Biri',
  OrderBasedDirect: 'Siparişe İstinaden Doğrudan',
  OrderBasedDirectReceipt: 'Siparişe İstinaden Doğrudan Kabul',
  OrderBasedDirectTransfer: 'Siparişe İstinaden Doğrudan Transfer',
  OrderBasedTask: 'Siparişe İstinaden Emirli',
  OrderlessDirectReceipt: 'Siparişsiz Doğrudan Kabul',
  OrderlessTask: 'Siparişsiz Emirli',
  Other: 'Diğer',
  Outbound: 'Çıkış',
  Owner: 'Sorumlu',
  Pack: 'Paketleme',
  Packed: 'Paketlendi',
  Packing: 'Paketleniyor',
  Pallet: 'Palet',
  PartiallyApproved: 'Kısmen Onaylandı',
  PartiallyCompleted: 'Kısmen Tamamlandı',
  PartiallyConsumed: 'Kısmen Kullanıldı',
  PartiallyConverted: 'Kısmen Dönüştürüldü',
  PartiallyReadyForReceipt: 'Kısmen Mal Kabule Hazır',
  PartiallyDecided: 'Kısmen Karar Verildi',
  PartiallyPicked: 'Kısmen Toplandı',
  PartiallyPrinted: 'Kısmen Basıldı',
  PartiallyProcessed: 'Kısmen İşlendi',
  PartiallyPutaway: 'Kısmen Raflandı',
  PartiallyReceived: 'Kısmen Kabul Edildi',
  Passed: 'Başarılı',
  Paused: 'Duraklatıldı',
  Pending: 'Bekliyor',
  Percentage: 'Yüzde',
  Pick: 'Toplama',
  Picked: 'Toplandı',
  Picking: 'Toplanıyor',
  Placed: 'Yerleştirildi',
  Planned: 'Planlandı',
  Posted: 'ERP’ye Aktarıldı',
  PreGenerate: 'Önceden Oluştur',
  PreGeneratedLabel: 'Önceden Oluşturulmuş Etiket',
  Printed: 'Basıldı',
  Processed: 'İşlendi',
  Processing: 'İşleniyor',
  Product: 'Ürün',
  ProductionOrder: 'Üretim Emri',
  ProductionReturn: 'Üretim İadesi',
  ProductLot: 'Ürün Lotu',
  ProductSerial: 'Ürün Serisi',
  PurchaseOrder: 'Satın Alma Siparişi',
  Putaway: 'Raflama',
  Quality: 'Kalite',
  QualityCheck: 'Kalite Kontrolü',
  QualityMove: 'Kalite Transferi',
  Quarantine: 'Karantinaya Al',
  Quarantined: 'Karantinada',
  QuickCheck: 'Hızlı Kontrol',
  ReadyForReceipt: 'Mal Kabule Hazır',
  Receive: 'Kabul',
  Received: 'Kabul Edildi',
  Receiving: 'Kabul Ediliyor',
  Reject: 'Reddet',
  Rejected: 'Reddedildi',
  Released: 'Serbest Bırakıldı',
  Replenishment: 'İkmal',
  RequireApproval: 'Onay Gerektir',
  Required: 'Zorunlu',
  Reserved: 'Rezerve Edildi',
  ReturnableContainer: 'İadeli Konteyner',
  Returned: 'İade Edildi',
  ReturnToSupplier: 'Tedarikçiye İade',
  ReturnToWarehouse: 'Depoya İade',
  Reversed: 'Ters Kayıt Oluşturuldu',
  SacMalKabul: 'SAC Mal Kabul',
  SacPanel: 'SAC Levha',
  Sequence: 'Sıra',
  Serial: 'Seri',
  SerialLot: 'Seri / Lot',
  SerialNo: 'Seri Numarası',
  Ship: 'Sevk',
  Shipment: 'Sevkiyat',
  Shipped: 'Sevk Edildi',
  ShortClosed: 'Eksik Kapatıldı',
  SideBySide: 'Üst Üste',
  Sscc: 'SSCC',
  Stacked: 'Üst Üste',
  StartsWith: 'İle Başlar',
  SteelPlate: 'SAC Levha',
  Stock: 'Stok',
  StockAndYapCode: 'Stok ve Yapılandırma Kodu',
  StockBasedDirect: 'Stoktan Doğrudan',
  StockBasedTask: 'Stoktan Emirli',
  StockCode: 'Stok Kodu',
  StockGroup: 'Stok Grubu',
  Succeeded: 'Başarılı',
  Supervisor: 'Amir',
  SupplierLabel: 'Tedarikçi Etiketi',
  SupplierWaybill: 'Tedarikçi İrsaliyesi',
  TransferIn: 'Transfer Girişi',
  TransferOrder: 'Transfer Emri',
  Transit: 'Transit',
  TwoDigit: 'İki Haneli',
  TwoStepTransit: 'İki Aşamalı Transit',
  Unassigned: 'Atama Kaldırıldı',
  UnplannedTask: 'Plansız Emir',
  Upper: 'Büyük Harf',
  UpperAlphaNumeric: 'Büyük Harf ve Sayı',
  Void: 'Geçersiz',
  Voided: 'Geçersiz Kılındı',
  WarehouseCode: 'Depo Kodu',
  WarehouseIssue: 'Ambar Çıkış',
  WarehouseOutbound: 'Ambar Çıkış',
  WarehouseReceipt: 'Ambar Giriş',
  WarehouseTransfer: 'Depolar Arası Transfer',
  WithinTolerance: 'Tolerans İçinde',
  Worker: 'Depo Personeli',
  YapCode: 'Yapılandırma Kodu',
  User: 'Kullanıcı',
  Manager: 'Yönetici',
  Admin: 'Uygulama Yöneticisi',
  superadmin: 'Sistem Yöneticisi',
  Running: 'Çalışıyor',
  TriggerFailed: 'Tetiklenemedi',
  QualityHold: 'Kalite Bekletmesi',
  InTransit: 'Yoldaki Stok',
};

const EN_ACRONYMS: Record<string, string> = {
  Api: 'API',
  Gs1: 'GS1',
  Sscc: 'SSCC',
  SacMalKabul: 'SAC Goods Receipt',
  SacPanel: 'SAC Plate',
  YapCode: 'Yapılandırma Kodu',
};

function humanizeEnumValue(value: string): string {
  const acronym = EN_ACRONYMS[value];
  if (acronym) return acronym;

  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1 $2')
    .trim();
}

export function isKnownEnumValue(value: unknown): value is string {
  return typeof value === 'string' && KNOWN_ENUM_VALUES.has(value);
}

export function localizeEnumValue(
  value: string | null | undefined,
  language?: string | null,
): string {
  if (!value) return '—';
  const normalizedLanguage = normalizeLanguage(
    language ?? i18n.resolvedLanguage ?? i18n.language,
  );
  if (normalizedLanguage === 'tr') {
    return TR_ENUM_LABELS[value] ?? humanizeEnumValue(value);
  }
  return humanizeEnumValue(value);
}

export function localizeEnumOptionLabel(
  value: string,
  label: string,
  language?: string | null,
): string {
  const isRawLabel = label === value || label === humanizeEnumValue(value);
  return isRawLabel && isKnownEnumValue(value)
    ? localizeEnumValue(value, language)
    : label;
}
