import { normalizeLanguage } from '@/lib/i18n';

/*
 * Compatibility translator for labels supplied by legacy grid definitions.
 * New feature code must use module translation keys; this bridge prevents a
 * partially migrated column/title from leaking Turkish into another locale.
 */
const ENGLISH_PHRASES: ReadonlyArray<readonly [string, string]> = [
  ['Ambar İşlemleri', 'Warehouse Operations'],
  ['Ambar Giriş', 'Warehouse Inbound'],
  ['Giriş Emri Oluştur', 'Create Inbound Task'],
  ['Doğrudan Giriş', 'Direct Inbound'],
  ['Emir ve Atamalar', 'Tasks and Assignments'],
  ['Giriş Kayıtları', 'Inbound Records'],
  ['Giriş Ayarları', 'Inbound Settings'],
  ['Ambar Çıkış', 'Warehouse Outbound'],
  ['Çıkış Emri Oluştur', 'Create Outbound Task'],
  ['Çıkış Kayıtları', 'Outbound Records'],
  ['Çıkış Ayarları', 'Outbound Settings'],
  ['Depolar Arası Transfer', 'Inter-Warehouse Transfer'],
  ['Transfer Taslağı', 'Transfer Draft'],
  ['Transfer Kayıtları', 'Transfer Records'],
  ['Sevk Oluştur', 'Create Shipment'],
  ['Süreç Merkezi', 'Process Centre'],
  ['Bu kombinasyon süreç politikasında kapalı.', 'This combination is disabled by the process policy.'],
  ['Siparişten Emir', 'Order-Based Task'],
  ['Siparişsiz Emir', 'Orderless Task'],
  ['Doğrudan Mal Kabul', 'Direct Goods Receipt'],
  ['Bana Atanan Emirler', 'My Assigned Tasks'],
  ['Ön Etiketler', 'Pre-Labels'],
  ['SAC İşlemleri', 'Steel Operations'],
  ['SAC Süreç Merkezi', 'Steel Process Centre'],
  ['Araç Giriş Kayıtları', 'Vehicle Entry Records'],
  ['Excel Beklenti Aktarımı', 'Excel Expectation Import'],
  ['Beklenen Levha Listesi', 'Expected Plate List'],
  ['Saha Kabul Kontrolü', 'Yard Receipt Inspection'],
  ['Alış İrsaliyesi Oluşturma', 'Create Purchase Dispatch Note'],
  ['Saha / Raf Yerleştirme', 'Yard / Location Putaway'],
  ['SAC Operasyon Raporları', 'Steel Operation Reports'],
  ['Depo Yönetimi', 'Warehouse Management'],
  ['Raf Tanımları', 'Location Definitions'],
  ['Belge Seri Tanımları', 'Document Series Definitions'],
  ['Barkod Tasarım ve Baskı', 'Barcode Design and Printing'],
  ['Genel Barkod Politikası', 'General Barcode Policy'],
  ['Stok Hareketleri', 'Stock Movements'],
  ['Raf Bakiyeleri', 'Location Balances'],
  ['Kalite İnceleme Listesi', 'Quality Inspection List'],
  ['Karantina Kararları', 'Quarantine Decisions'],
  ['Stok Kuralları', 'Stock Rules'],
  ['Genel Ayarlar', 'General Settings'],
  ['Paketleme', 'Packing'],
  ['Paketleme İstasyonu', 'Packing Station'],
  ['Paketleme Tanımları', 'Packing Definitions'],
  ['Paketleme Ayarları', 'Packing Settings'],
  ['Sistem ve Yetki', 'System and Access'],
  ['Kullanıcı Yönetimi', 'User Management'],
  ['İzin Tanımları', 'Permission Definitions'],
  ['İzin Grupları', 'Permission Groups'],
  ['İzin gruplarını ve izin atamalarını CRM seviyesinde yönetin.', 'Manage permission groups and permission assignments at CRM-grade depth.'],
  ['İzinler', 'Permissions'],
  ['Hangfire İzleme', 'Hangfire Monitoring'],
  ['Tamamlanan mal kabullerini kalite gereksinimi ve karar durumu ile birlikte izleyin.', 'Track completed goods receipts together with their quality requirement and decision status.'],
  ['Tamamlanan mal kabullerin özetini görüntüleyin; stok, lot, seri ve karar ayrıntıları için kaydı açın.', 'Review completed goods receipt summaries; open a record for stock, lot, serial and decision details.'],
  ['Stok bazlı kalite zorunluluğu, kontrol tipi ve örnekleme planını yönetin.', 'Manage stock-specific quality requirements, inspection types and sampling plans.'],
  ['Stok bazında kontrol, örnekleme ve başarısızlık aksiyonunu belirleyin.', 'Define inspection, sampling and failure actions by stock.'],
  ['Karantinadaki ürünleri yetkili biçimde serbest bırakın, reddedin veya iade edin.', 'Authorised users can release, reject or return quarantined products.'],
  ['Karantina Karar Kuyruğu', 'Quarantine Decision Queue'],
  ['Kalite Yönetimi Ayarları', 'Quality Management Settings'],
  ['Mal kabulde kontrol, karantina, stok serbest bırakma ve ERP bekleme davranışlarını merkezi yönetin.', 'Centrally manage inspection, quarantine, stock release and ERP hold behaviour during goods receipt.'],
  ['Varsayılan kontrol modu', 'Default inspection mode'],
  ['Kontrol yok', 'No inspection'],
  ['Başarısızlık aksiyonu', 'Failure action'],
  ['Kalite hareket rafları', 'Quality movement locations'],
  ['Kalite kararı stok hareketine dönüştüğünde kullanılacak fiziksel hedefleri belirleyin.', 'Define the physical destinations used when a quality decision becomes a stock movement.'],
  ['Kalite bekleme rafı', 'Quality hold location'],
  ['Karantina rafı', 'Quarantine location'],
  ['Ret rafı', 'Rejection location'],
  ['Raf seçin', 'Select location'],
  ['Mal kabulde kontrolü otomatik oluştur', 'Automatically create an inspection during goods receipt'],
  ['Karara kadar stoğu kullanılabilir yapma', 'Do not make stock available until a decision'],
  ['Kalite kararına kadar ERP kaydını beklet', 'Hold ERP posting until the quality decision'],
  ['Serbest bırakmada yönetici onayı', 'Require manager approval for release'],
  ['Kısmi kalite kararına izin ver', 'Allow partial quality decisions'],
  ['Kural yoksa doğrudan kabule izin ver', 'Allow direct receipt when no rule exists'],
  ['Lot eksikse kabulü engelle', 'Block receipt when lot is missing'],
  ['Seri eksikse kabulü engelle', 'Block receipt when serial is missing'],
  ['SKT eksikse kabulü engelle', 'Block receipt when expiration date is missing'],
  ['Bekletilen ürünler fiziksel olarak kabul alanında bulunabilir; ancak kalite kararı verilene kadar kullanılabilir stok projection’ına alınmaz.', 'Held products may physically remain in the receiving area, but they are excluded from the available-stock projection until a quality decision is recorded.'],
  ['Kalite İncelemeleri', 'Quality Inspections'],
  ['Kalite İnceleme Listesi', 'Quality Inspection List'],
  ['Kalite Kuralları', 'Quality Rules'],
  ['Yeni kalite kuralı', 'New quality rule'],
  ['Kaliteye Gönderilme', 'Sent to Quality At'],
  ['İşlemi Yapan', 'Processed By'],
  ['Kontrol No', 'Inspection No'],
  ['Örnekleme', 'Sampling'],
  ['Başarısızlık', 'Failure'],
  ['Kontrol', 'Inspection'],
  ['Mal kabul, transfer, sevk, iade ve sayım farklarının değiştirilemez kayıtları.', 'Immutable records of goods receipts, transfers, shipments, returns and count variances.'],
  ['Yeni Hareket', 'New Movement'],
  ['Hareket Zamanı', 'Movement Time'],
  ['Çıkan', 'Outbound'],
  ['Depo, raf, stok, yapılandırma kodu, lot, seri ve stok durumu seviyesinde güncel fiziksel/rezerve/kullanılabilir miktarlar.', 'Current physical, reserved and available quantities by warehouse, location, stock, configuration code, lot, serial and stock status.'],
  ['Uzlaştır ve Onar', 'Reconcile and Repair'],
  ['Son Hareket ID', 'Last Movement ID'],
  ['Depo ve stok seviyesinde özet bakiye; işlemden raf, lot ve seri kırılımına inebilirsiniz.', 'Summary balance by warehouse and stock; drill down to location, lot and serial details.'],
  ['Raf Sayısı', 'Location Count'],
  ['Lot Sayısı', 'Lot Count'],
  ['Seri Sayısı', 'Serial Count'],
  ['Seri takipli stokların depo, raf, YAP ve lot kırılımındaki güncel bakiyesi; işlemden serinin uçtan uca hareket geçmişine ulaşabilirsiniz.', 'Current balance of serial-tracked stock by warehouse, location, configuration code and lot; open the end-to-end serial movement history from the action menu.'],
  ['Genel Proje Ayarları', 'General Project Settings'],
  ['Tüm kullanıcılar için sayı, miktar, tarih, saat, yıl ve zaman dilimi gösterimini merkezi olarak yönetin.', 'Centrally manage number, quantity, date, time, year and time-zone display for all users.'],
  ['TARİH / SAAT', 'DATE / TIME'],
  ['Sayı biçimi', 'Number format'],
  ['Ondalık basamak', 'Decimal places'],
  ['Tarih biçimi', 'Date format'],
  ['Saat biçimi', 'Time format'],
  ['Yıl biçimi', 'Year format'],
  ['İstanbul (UTC+3)', 'Istanbul (UTC+3)'],
  ['Canlı örnek: Ayarı seçtiğiniz anda üstteki kartlar değişir. Kayıt sonrasında açık ekranlardaki ortak grid ve WMS miktar/tarih alanları yeni biçimi kullanır.', 'Live preview: the cards above change as soon as you select a setting. After saving, shared grids and WMS quantity/date fields use the new format.'],
  ['Ayarları Kaydet', 'Save Settings'],
  ['Kullanıcı hesaplarını, profil bilgilerini, rolleri ve yetki gruplarını yönetin.', 'Manage user accounts, profile information, roles and permission groups.'],
  ['Yeni Kullanıcı', 'New User'],
  ['Kullanıcı Adı', 'Username'],
  ['Son Giriş', 'Last Login'],
  ['Uygulama izin kataloğunu oluşturun, güncelleyin ve güvenli biçimde pasife alın.', 'Create, update and safely deactivate the application permission catalogue.'],
  ['Yeni İzin', 'New Permission'],
  ['İzin Kodu', 'Permission Code'],
  ['Audit Kayıtları', 'Audit Logs'],
  ['Kritik kullanıcı ve yetki değişikliklerini eski-yeni değerleriyle izleyin.', 'Track critical user and permission changes with their before-and-after values.'],
  ['Varlık', 'Entity'],
  ['Sonuç', 'Result'],
  ['İstek', 'Request'],
  ['SMTP Ayarları', 'SMTP Settings'],
  ['CRM ile aynı tek aktif SMTP ayarı ve şifre koruma mantığı.', 'Uses the same single-active SMTP setting and password-protection model as CRM.'],
  ['Gönderen E-posta', 'Sender Email'],
  ['Gönderen Ad', 'Sender Name'],
  ['Zaman Aşımı (sn)', 'Timeout (sec)'],
  ['Test Gönder', 'Send Test'],
  ['Recurring job durumları, manuel tetikleme ve kalıcı çalışma geçmişi.', 'Recurring job statuses, manual triggering and persistent execution history.'],
  ['Çalışma Geçmişi', 'Execution History'],
  ['Başarılı ve başarısız Hangfire çalıştırmaları veritabanından sayfalı olarak listelenir.', 'Successful and failed Hangfire executions are listed from the database with server-side paging.'],
  ['Son Çalışma', 'Last Run'],
  ['Kaynak Kayıt', 'Source Record'],
  ['Güncellenen', 'Updated'],
  ['Süre', 'Duration'],
  ['Ambalaj, istasyon ve stok/müşteri bazlı paketleme kapasite kurallarını tek yerden yönetin.', 'Manage packaging, stations and stock/customer-specific packing capacity rules in one place.'],
  ['Paketleme spesifikasyonları', 'Packing specifications'],
  ['Azami brüt', 'Maximum gross'],
  ['İadeli', 'Returnable'],
  ['Atanmış emirleri kabul edin, başlatın ve barkodla fiziksel kabulü işleyin.', 'Accept assigned tasks, start them and process physical receipt by barcode.'],
  ['Mal Kabul Kayıtları', 'Goods Receipt Records'],
  ['E-İrsaliye', 'E-Dispatch Note'],
  ['Stok *', 'Stock *'],
  ['Cari *', 'Customer *'],
  ['Miktar *', 'Quantity *'],
  ['Sevk Kayıtları', 'Shipment Records'],
  ['Plan, toplama, paketleme, yükleme ve sevk miktarlarını sunucu taraflı izleyin.', 'Track planned, picked, packed, loaded and shipped quantities with server-side data.'],
  ['Akış', 'Flow'],
  ['Toplandı', 'Picked'],
  ['Yüklendi', 'Loaded'],
  ['Mevcut cyan/turuncu depo operasyon kimliği', 'Current cyan/orange warehouse operations identity'],
  ['Depo Mavisi', 'Warehouse Blue'],
  ['Yoğun operasyon ekranları için güvenli mavi ton', 'A dependable blue tone for high-activity operation screens'],
  ['Endüstriyel Çelik', 'Industrial Steel'],
  ['Fabrika, stok ve transfer süreçleri için metalik yapı', 'A metallic theme for factory, inventory and transfer processes'],
  ['Güvenli Yeşil', 'Safety Green'],
  ['Onay, tamamlama ve saha kontrol süreçleri için sakin tema', 'A calm theme for approval, completion and floor-control processes'],
  ['Forklift Amber', 'Forklift Amber'],
  ['Saha uyarıları ve sevkiyat operasyonları için sıcak aksan', 'A warm accent for floor alerts and shipping operations'],
  ['Grafit Operasyon', 'Graphite Operations'],
  ['Az dikkat dağıtan, sade ve kurumsal görünüm', 'A restrained corporate look with minimal distraction'],
  ['Premium Koyu', 'Premium Dark'],
  ['Yönetim, rapor ve dashboard ekranları için güçlü koyu tema', 'A strong dark theme for management, reporting and dashboard screens'],
  ['Bordo Kurumsal', 'Corporate Burgundy'],
  ['ERP ve yönetim ekranları için ağır, kurumsal kırmızı ton', 'A formal corporate red tone for ERP and management screens'],
  ['Sade Açık', 'Clean Light'],
  ['Gündüz kullanım ve yoğun veri girişi için yumuşak arayüz', 'A soft interface for daytime use and intensive data entry'],
  ['Yüksek Kontrast', 'High Contrast'],
  ['Belirgin odak, net sınır ve erişilebilir saha kullanımı', 'Clear focus, strong boundaries and accessible warehouse-floor use'],
  ['Düz Lacivert', 'Flat Navy'],
  ['Gradientsiz, net ve kurumsal lacivert görünüm', 'A clear corporate navy appearance without gradients'],
  ['Düz Grafit', 'Flat Graphite'],
  ['Gradientsiz, sakin ve operasyon odaklı yönetim paneli', 'A calm operations-focused administration panel without gradients'],
  ['Düz Açık', 'Flat Light'],
  ['Gradientsiz, aydınlık ve tablo odaklı çalışma modu', 'A bright table-focused work mode without gradients'],
  ['Paketleme Ayarları', 'Packing Settings'],
  ['Paketleme no', 'Packing No'],
  ['Kaynak tipi', 'Source Type'],
  ['Kaynak belge', 'Source Document'],
  ['Koli / Palet', 'Boxes / Pallets'],
  ['Brüt', 'Gross'],
  ['Açılış', 'Opened At'],
  ['Depolar', 'Warehouses'],
  ['Depo Kodu', 'Warehouse Code'],
  ['Depo Adı', 'Warehouse Name'],
  ['Stoklar', 'Stocks'],
  ['Cariler', 'Customers'],
  ['Yapılandırma Kodları', 'Configuration Codes'],
  ['Üretici Kodu', 'Manufacturer Code'],
  ['Grup Kodu', 'Group Code'],
  ['İşletme', 'Company'],
  ['Son Eşleme', 'Last Sync'],
  ['Şimdi Eşle', 'Sync Now'],
  ['Netsis depo kartlarının eşlenmiş görünümü.', 'Mirrored view of Netsis warehouse cards.'],
  ['Netsis stok kartları ve stoğa bağlı WMS takip zorunlulukları.', 'Netsis stock cards and stock-specific WMS tracking requirements.'],
  ['Mal Kabul Süreç Politikası', 'Goods Receipt Process Policy'],
  ['Mal kabul emirlerini, sorumlularını ve ön etiketlerini yönetin.', 'Manage goods receipt tasks, assignees and pre-generated labels.'],
  ['Mal kabulü görüntüleyin; belge veya kalem bazında etiket yazdırın ve PDF önizleyin.', 'Review goods receipts and print or preview labels by document or line.'],
  ['Mal Kabul', 'Goods Receipt'],
  ['Mal kabul', 'Goods receipt'],
  ['Fazla/eksik kabul, operasyon onayı, kalite kapısı, stok kullanılabilirliği ve ERP gönderim zamanını merkezi yönetin.', 'Centrally manage over/under receipt, operational approval, the quality gate, stock availability and ERP posting time.'],
  ['Bu ayarlar emir oluşturulurken başlığa snapshot olarak yazılır. Sonradan ayar değişse bile devam eden emir aynı kurallarla tamamlanır.', 'These settings are snapshotted onto the task header when it is created. Existing tasks keep the same rules after a policy change.'],
  ['Ambar Giriş Süreç Politikası', 'Warehouse Inbound Process Policy'],
  ['Ambar Çıkış Süreç Politikası', 'Warehouse Outbound Process Policy'],
  ['Depolar Arası Transfer Süreç Politikası', 'Inter-Warehouse Transfer Process Policy'],
  ['Sevk Süreç Politikası', 'Shipping Process Policy'],
  ['Emir Yönetimi', 'Task Management'],
  ['Emir ve Atamalar', 'Tasks and Assignments'],
  ['Atanmış Emirler', 'Assigned Tasks'],
  ['Süreç Merkezi', 'Process Centre'],
  ['Süreç Ayarları', 'Process Settings'],
  ['Süreç Politikası', 'Process Policy'],
  ['Kayıtları', 'Records'],
  ['Ayarları', 'Settings'],
  ['Tanımları', 'Definitions'],
  ['Parametreleri', 'Parameters'],
  ['İnceleme Listesi', 'Inspection List'],
  ['Karantina Kararları', 'Quarantine Decisions'],
  ['Sipariş seçimi', 'Order selection'],
  ['Kalem ve kabul planı', 'Lines and receipt plan'],
  ['Kontrol ve oluşturma', 'Review and create'],
  ['Belge ve emir ayarları', 'Document and task settings'],
  ['Belge serisi', 'Document series'],
  ['Varsayılan depo', 'Default warehouse'],
  ['Sipariş No', 'Order No'],
  ['Fazla kabul toleransı (%)', 'Over-receipt tolerance (%)'],
  ['Fazla kabul', 'Over-receipt'],
  ['Stok ne zaman kullanılabilir?', 'When is stock available?'],
  ['ERP kaydı ne zaman?', 'When is the ERP record posted?'],
  ['Eksik kabule izin ver', 'Allow under-receipt'],
  ['Eksik kapatmada onay iste', 'Require approval for short close'],
  ['Kabul sonrası operasyon onayı iste', 'Require operational approval after receipt'],
  ['Kalite onayı iste', 'Require quality approval'],
  ['ERP onayı iste', 'Require ERP approval'],
  ['Kalite kararına kadar stoğu beklet', 'Hold stock until the quality decision'],
  ['Kalite kararına kadar rafa kaldırmayı beklet', 'Block putaway until the quality decision'],
  ['Emirsiz kabule izin ver', 'Allow orderless receipt'],
  ['Plansız kabule izin ver', 'Allow unplanned receipt'],
  ['Politikayı kaydet', 'Save policy'],
  ['İzin verme', 'Do not allow'],
  ['Tolerans içinde izin ver', 'Allow within tolerance'],
  ['Tolerans içinde onaya gönder', 'Require approval within tolerance'],
  ['Kabulde hemen', 'Immediately on receipt'],
  ['Mal kabul onayından sonra', 'After receipt approval'],
  ['Kalite onayından sonra', 'After quality approval'],
  ['Tüm onaylardan sonra', 'After all approvals'],
  ['Kabul tamamlanınca', 'When receipt is completed'],
  ['Esnek Sevk Oluşturma', 'Flexible Shipment Creation'],
  ['Sipariş kaynağı ve görev yürütmesini bağımsız seçin; tüm varyantlar aynı sevk başlık ve kalem yapısını kullanır.', 'Choose the order source and execution mode independently; every variant uses the same shipment header and line model.'],
  ['Operasyon emri oluşturulur, kullanıcı atanır ve saha ilerlemesi izlenir.', 'Creates an operation task, assigns operators and tracks warehouse-floor progress.'],
  ['Görev oluşturmadan yetkili kullanıcı tarafından doğrudan işlenir.', 'An authorised operator processes the shipment directly without creating a task.'],
  ['ERP belgesi ve açık miktarlar ile izlenebilir bağlantı kurar.', 'Creates a traceable link to the ERP document and its open quantities.'],
  ['Stok, miktar, depo ve raf bilgileri kullanıcı tarafından belirlenir.', 'The operator selects the stock, quantity, warehouse and source location.'],
  ['Toplama emri ve kullanıcı ataması oluşturulur.', 'Creates a picking task and operator assignments.'],
  ['Yürütme Modeli', 'Execution Model'],
  ['Emir yürütme modeli', 'Task execution model'],
  ['Emirli İşlem', 'Task-Based Operation'],
  ['Emirsiz İşlem', 'Direct Operation'],
  ['Belge Kaynağı', 'Document Source'],
  ['Operasyon belge kaynağı', 'Operation document source'],
  ['Netsis satış siparişine istinaden', 'Based on a Netsis sales order'],
  ['Netsis transfer emrine istinaden', 'Based on a Netsis transfer order'],
  ['Siparişsiz / serbest stoktan', 'Orderless / from free stock'],
  ['Kalemler ERP stok mirror üzerinden seçilir. Toplama emri, rezervasyon ve kullanıcı ataması oluşur.', 'Lines are selected from the ERP stock mirror; the system creates a picking task, reservations and operator assignments.'],
  ['Belge ve rota', 'Document and route'],
  ['Kaynak hazırlama alanı', 'Source staging location'],
  ['Hedef kabul alanı', 'Destination receiving location'],
  ['Emir sorumluları', 'Task assignees'],
  ['Aktif kullanıcı ara', 'Search active users'],
  ['Transfer kalemleri', 'Transfer lines'],
  ['Yeni kalem', 'New line'],
  ['Palet zorunlu', 'Pallet required'],
  ['Transferi Oluştur', 'Create Transfer'],
  ['Yerleşen', 'Put Away'],
  ['Operasyonu yürüt', 'Execute operation'],
  ['Taslağı düzenle', 'Edit draft'],
  ['Taslağı sil', 'Delete draft'],
  ['Transferi iptal et', 'Cancel transfer'],
  ['Detayı göster', 'Show details'],
  ['Emir, rezervasyon ve karşılama', 'Task, reservation and fulfilment'],
  ['Rezervasyon zamanı', 'Reservation time'],
  ['Depoya serbest bırakınca', 'When released to the warehouse'],
  ['Emir oluşturulunca', 'When the task is created'],
  ['Toplama başlayınca', 'When picking starts'],
  ['Minimum karşılama (%)', 'Minimum fulfilment (%)'],
  ['Fark politikası', 'Variance policy'],
  ['Onaya gönder', 'Send for approval'],
  ['İzin ver', 'Allow'],
  ['Engelle', 'Block'],
  ['Transfer onayı zorunlu', 'Transfer approval required'],
  ['Emirli transferde kullanıcı zorunlu', 'Assignee required for task-based transfer'],
  ['Birden fazla kullanıcı atanabilir', 'Allow multiple assignees'],
  ['Emirli transferi otomatik serbest bırak', 'Automatically release task-based transfer'],
  ['Kaynak operasyonu ve hedef kabul', 'Source operation and destination receipt'],
  ['Kısmi toplamaya izin ver', 'Allow partial picking'],
  ['Kısmi sevke izin ver', 'Allow partial dispatch'],
  ['Kısmi kabule izin ver', 'Allow partial receipt'],
  ['Hedef depo kabulü zorunlu', 'Destination warehouse receipt required'],
  ['Transit stok oluştur', 'Create in-transit stock'],
  ['Raf yerleştirme zorunlu', 'Putaway required'],
  ['Kaynak raf zorunlu', 'Source location required'],
  ['Hedef raf zorunlu', 'Destination location required'],
  ['Sevk/plaka bilgisi zorunlu', 'Shipment/vehicle information required'],
  ['Doğrudan transfer davranışı', 'Direct transfer behaviour'],
  ['İki adım: kaynak → transit → hedef', 'Two steps: source → transit → destination'],
  ['Politika transfer oluşturulurken başlığa snapshot alınır. Devam eden transferler sonradan değişen ayarlardan etkilenmez.', 'The policy is snapshotted onto the transfer header at creation. Existing transfers are not affected by later policy changes.'],
  ['Politikayı Kaydet', 'Save Policy'],
  ['Cari, belge ve depo', 'Customer, document and warehouse'],
  ['Cari', 'Customer'],
  ['Toplama emri kullanıcıları', 'Picking task assignees'],
  ['Sevk kalemleri', 'Shipment lines'],
  ['Sevk Taslağı Oluştur', 'Create Shipment Draft'],
  ['Hazırlama alanı', 'Staging location'],
  ['Yükleme alanı', 'Loading location'],
  ['Araç plakası', 'Vehicle plate'],
  ['Taşıyıcı kodu', 'Carrier code'],
  ['Harici referans', 'External reference'],
  ['Palet / kasa zorunlu', 'Pallet / container required'],
  ['Kalem ekle', 'Add line'],
  ['Önce stok seçin', 'Select stock first'],
  ['Stok takip politikası', 'Stock tracking policy'],
  ['Yapılandırma kodu', 'Configuration code'],
  ['Planlanan sevk', 'Planned shipment'],
  ['Planlanan varış', 'Planned arrival'],
  ['Belge tarihi', 'Document date'],
  ['Kaynak depo', 'Source warehouse'],
  ['Hedef depo', 'Destination warehouse'],
  ['Kaynak raf', 'Source location'],
  ['Hedef raf', 'Destination location'],
  ['Açıklama', 'Description'],
  ['Öncelik', 'Priority'],
  ['Miktar', 'Quantity'],
  ['Birim', 'Unit'],
  ['Sevk', 'Shipment'],
  ['Kayıt Zamanı', 'Created At'],
  ['Kayıt Eden Kullanıcı', 'Created By'],
  ['Kayıt Eden', 'Created By'],
  ['Güncelleme Zamanı', 'Updated At'],
  ['Güncelleyen Kullanıcı', 'Updated By'],
  ['Son Güncelleyen', 'Updated By'],
  ['Yapılandırma Kodu', 'Configuration Code'],
  ['Yapılandırma', 'Configuration'],
  ['Belge Numarası', 'Document Number'],
  ['Belge No', 'Document No'],
  ['Belge Tarihi', 'Document Date'],
  ['Mal Kabul', 'Goods Receipt'],
  ['Ambar Giriş', 'Warehouse Inbound'],
  ['Ambar Çıkış', 'Warehouse Outbound'],
  ['Depolar Arası Transfer', 'Inter-Warehouse Transfer'],
  ['Stok Hareket Defteri', 'Stock Movement Ledger'],
  ['Depo Stok Bakiyesi', 'Warehouse Stock Balance'],
  ['Stok Seri Bakiyesi', 'Stock Serial Balance'],
  ['Raf Bakiyesi', 'Location Balance'],
  ['Toplam Miktar', 'Total Quantity'],
  ['Kalan Miktar', 'Remaining Quantity'],
  ['Kabul Miktarı', 'Received Quantity'],
  ['Planlanan Miktar', 'Planned Quantity'],
  ['Rezerve Miktar', 'Reserved Quantity'],
  ['Kullanılabilir Miktar', 'Available Quantity'],
  ['İşlem Tipi', 'Operation Type'],
  ['Hareket Tipi', 'Movement Type'],
  ['Kaynak Depo', 'Source Warehouse'],
  ['Hedef Depo', 'Destination Warehouse'],
  ['Kaynak Raf', 'Source Location'],
  ['Hedef Raf', 'Destination Location'],
  ['Son Kullanma Tarihi', 'Expiration Date'],
  ['Üretim Tarihi', 'Manufacturing Date'],
  ['Araç Plakası', 'Vehicle Plate'],
  ['Çekici Plakası', 'Truck Plate'],
  ['İrsaliye No', 'Dispatch Note No'],
  ['İrsaliye', 'Dispatch Note'],
  ['İşlemler', 'Actions'],
  ['Görüntüle', 'View'],
  ['Düzenle', 'Edit'],
  ['Güncelle', 'Update'],
  ['Kayıt ID', 'Record ID'],
  ['Kayıt', 'Record'],
  ['Oluşturan', 'Created By'],
  ['Oluşturma', 'Creation'],
  ['Güncellenme', 'Updated'],
  ['Stok Kodu', 'Stock Code'],
  ['Stok Adı', 'Stock Name'],
  ['Cari Kodu', 'Customer Code'],
  ['Cari Adı', 'Customer Name'],
  ['Şube', 'Branch'],
  ['Depo', 'Warehouse'],
  ['Raf', 'Location'],
  ['Konum', 'Location'],
  ['Stok', 'Stock'],
  ['Miktar', 'Quantity'],
  ['Birim', 'Unit'],
  ['Seri', 'Serial'],
  ['Lot', 'Lot'],
  ['Durum', 'Status'],
  ['Kalite', 'Quality'],
  ['Karantina', 'Quarantine'],
  ['Onay', 'Approval'],
  ['Öncelik', 'Priority'],
  ['Açıklama', 'Description'],
  ['Tarih', 'Date'],
  ['Saat', 'Time'],
  ['Kullanıcı', 'User'],
  ['Rol', 'Role'],
  ['İzin', 'Permission'],
  ['Grup', 'Group'],
  ['Adı', 'Name'],
  ['Kod', 'Code'],
  ['Tip', 'Type'],
  ['Sıra', 'Sequence'],
  ['Beklenen', 'Expected'],
  ['Kabul', 'Receipt'],
  ['Toplanan', 'Picked'],
  ['Sevk', 'Shipment'],
  ['Alınan', 'Received'],
  ['Aktif', 'Active'],
  ['Pasif', 'Inactive'],
];

const ENGLISH_EXACT_PHRASES = new Map(ENGLISH_PHRASES);
const escapeRegExp = (value: string): string =>
  value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const ENGLISH_COMPOUND_PATTERN = new RegExp(
  ENGLISH_PHRASES
    .map(([source]) => source)
    .filter((source) => /\s|[/:%→–—]/u.test(source))
    .sort((left, right) => right.length - left.length)
    .map(escapeRegExp)
    .join('|'),
  'gu',
);

export function localizeLegacyUiText(value: string, language?: string): string {
  if (!value || normalizeLanguage(language) === 'tr') return value;

  const exact = ENGLISH_EXACT_PHRASES.get(value);
  if (exact) return exact;

  // Replace against the original value in a single pass. This prevents
  // translated targets such as "Serial" from being matched again by the
  // Turkish source "Seri" and keeps single-word business data untouched.
  return value.replace(
    ENGLISH_COMPOUND_PATTERN,
    (source) => ENGLISH_EXACT_PHRASES.get(source) ?? source,
  );
}
