import { normalizeLanguage } from '@/lib/i18n';

/*
 * Compatibility translator for labels supplied by legacy grid definitions.
 * New feature code must use module translation keys; this bridge prevents a
 * partially migrated column/title from leaking Turkish into another locale.
 */
const ENGLISH_PHRASES: ReadonlyArray<readonly [string, string]> = [
  ['Paketleme Ayarları', 'Packing Settings'],
  ['Paketleme no', 'Packing No'],
  ['Kaynak tipi', 'Source Type'],
  ['Kaynak belge', 'Source Document'],
  ['Koli / Palet', 'Boxes / Pallets'],
  ['Brüt', 'Gross'],
  ['Açılış', 'Opened At'],
  ['Depolar', 'Warehouses'],
  ['Depo Kodu', 'Warehouse Code'],
  ['Depo Adı', 'Warehouse Name'],
  ['Stoklar', 'Stocks'],
  ['Cariler', 'Customers'],
  ['Yapılandırma Kodları', 'Configuration Codes'],
  ['Üretici Kodu', 'Manufacturer Code'],
  ['Grup Kodu', 'Group Code'],
  ['İşletme', 'Company'],
  ['Son Eşleme', 'Last Sync'],
  ['Şimdi Eşle', 'Sync Now'],
  ['Netsis depo kartlarının eşlenmiş görünümü.', 'Mirrored view of Netsis warehouse cards.'],
  ['Netsis stok kartları ve stoğa bağlı WMS takip zorunlulukları.', 'Netsis stock cards and stock-specific WMS tracking requirements.'],
  ['Mal Kabul Süreç Politikası', 'Goods Receipt Process Policy'],
  ['Mal kabul emirlerini, sorumlularını ve ön etiketlerini yönetin.', 'Manage goods receipt tasks, assignees and pre-generated labels.'],
  ['Mal kabulü görüntüleyin; belge veya kalem bazında etiket yazdırın ve PDF önizleyin.', 'Review goods receipts and print or preview labels by document or line.'],
  ['Mal Kabul', 'Goods Receipt'],
  ['Mal kabul', 'Goods receipt'],
  ['Fazla/eksik kabul, operasyon onayı, kalite kapısı, stok kullanılabilirliği ve ERP gönderim zamanını merkezi yönetin.', 'Centrally manage over/under receipt, operational approval, the quality gate, stock availability and ERP posting time.'],
  ['Bu ayarlar emir oluşturulurken başlığa snapshot olarak yazılır. Sonradan ayar değişse bile devam eden emir aynı kurallarla tamamlanır.', 'These settings are snapshotted onto the task header when it is created. Existing tasks keep the same rules after a policy change.'],
  ['Ambar Giriş Süreç Politikası', 'Warehouse Inbound Process Policy'],
  ['Ambar Çıkış Süreç Politikası', 'Warehouse Outbound Process Policy'],
  ['Depolar Arası Transfer Süreç Politikası', 'Inter-Warehouse Transfer Process Policy'],
  ['Sevk Süreç Politikası', 'Shipping Process Policy'],
  ['Emir Yönetimi', 'Task Management'],
  ['Emir ve Atamalar', 'Tasks and Assignments'],
  ['Atanmış Emirler', 'Assigned Tasks'],
  ['Süreç Merkezi', 'Process Centre'],
  ['Süreç Ayarları', 'Process Settings'],
  ['Süreç Politikası', 'Process Policy'],
  ['Kayıtları', 'Records'],
  ['Ayarları', 'Settings'],
  ['Tanımları', 'Definitions'],
  ['Parametreleri', 'Parameters'],
  ['İnceleme Listesi', 'Inspection List'],
  ['Karantina Kararları', 'Quarantine Decisions'],
  ['Sipariş seçimi', 'Order selection'],
  ['Kalem ve kabul planı', 'Lines and receipt plan'],
  ['Kontrol ve oluşturma', 'Review and create'],
  ['Belge ve emir ayarları', 'Document and task settings'],
  ['Belge serisi', 'Document series'],
  ['Varsayılan depo', 'Default warehouse'],
  ['Sipariş No', 'Order No'],
  ['Fazla kabul toleransı (%)', 'Over-receipt tolerance (%)'],
  ['Fazla kabul', 'Over-receipt'],
  ['Stok ne zaman kullanılabilir?', 'When is stock available?'],
  ['ERP kaydı ne zaman?', 'When is the ERP record posted?'],
  ['Eksik kabule izin ver', 'Allow under-receipt'],
  ['Eksik kapatmada onay iste', 'Require approval for short close'],
  ['Kabul sonrası operasyon onayı iste', 'Require operational approval after receipt'],
  ['Kalite onayı iste', 'Require quality approval'],
  ['ERP onayı iste', 'Require ERP approval'],
  ['Kalite kararına kadar stoğu beklet', 'Hold stock until the quality decision'],
  ['Kalite kararına kadar rafa kaldırmayı beklet', 'Block putaway until the quality decision'],
  ['Emirsiz kabule izin ver', 'Allow orderless receipt'],
  ['Plansız kabule izin ver', 'Allow unplanned receipt'],
  ['Politikayı kaydet', 'Save policy'],
  ['İzin verme', 'Do not allow'],
  ['Tolerans içinde izin ver', 'Allow within tolerance'],
  ['Tolerans içinde onaya gönder', 'Require approval within tolerance'],
  ['Kabulde hemen', 'Immediately on receipt'],
  ['Mal kabul onayından sonra', 'After receipt approval'],
  ['Kalite onayından sonra', 'After quality approval'],
  ['Tüm onaylardan sonra', 'After all approvals'],
  ['Kabul tamamlanınca', 'When receipt is completed'],
  ['Esnek Sevk Oluşturma', 'Flexible Shipment Creation'],
  ['Sipariş kaynağı ve görev yürütmesini bağımsız seçin; tüm varyantlar aynı sevk başlık ve kalem yapısını kullanır.', 'Choose the order source and execution mode independently; every variant uses the same shipment header and line model.'],
  ['Operasyon emri oluşturulur, kullanıcı atanır ve saha ilerlemesi izlenir.', 'Creates an operation task, assigns operators and tracks warehouse-floor progress.'],
  ['Görev oluşturmadan yetkili kullanıcı tarafından doğrudan işlenir.', 'An authorised operator processes the shipment directly without creating a task.'],
  ['ERP belgesi ve açık miktarlar ile izlenebilir bağlantı kurar.', 'Creates a traceable link to the ERP document and its open quantities.'],
  ['Stok, miktar, depo ve raf bilgileri kullanıcı tarafından belirlenir.', 'The operator selects the stock, quantity, warehouse and source location.'],
  ['Toplama emri ve kullanıcı ataması oluşturulur.', 'Creates a picking task and operator assignments.'],
  ['Yürütme Modeli', 'Execution Model'],
  ['Emir yürütme modeli', 'Task execution model'],
  ['Emirli İşlem', 'Task-Based Operation'],
  ['Emirsiz İşlem', 'Direct Operation'],
  ['Belge Kaynağı', 'Document Source'],
  ['Operasyon belge kaynağı', 'Operation document source'],
  ['Netsis satış siparişine istinaden', 'Based on a Netsis sales order'],
  ['Netsis transfer emrine istinaden', 'Based on a Netsis transfer order'],
  ['Siparişsiz / serbest stoktan', 'Orderless / from free stock'],
  ['Kalemler ERP stok mirror üzerinden seçilir. Toplama emri, rezervasyon ve kullanıcı ataması oluşur.', 'Lines are selected from the ERP stock mirror; the system creates a picking task, reservations and operator assignments.'],
  ['Belge ve rota', 'Document and route'],
  ['Kaynak hazırlama alanı', 'Source staging location'],
  ['Hedef kabul alanı', 'Destination receiving location'],
  ['Emir sorumluları', 'Task assignees'],
  ['Aktif kullanıcı ara', 'Search active users'],
  ['Transfer kalemleri', 'Transfer lines'],
  ['Yeni kalem', 'New line'],
  ['Palet zorunlu', 'Pallet required'],
  ['Transferi Oluştur', 'Create Transfer'],
  ['Yerleşen', 'Put Away'],
  ['Operasyonu yürüt', 'Execute operation'],
  ['Taslağı düzenle', 'Edit draft'],
  ['Taslağı sil', 'Delete draft'],
  ['Transferi iptal et', 'Cancel transfer'],
  ['Detayı göster', 'Show details'],
  ['Emir, rezervasyon ve karşılama', 'Task, reservation and fulfilment'],
  ['Rezervasyon zamanı', 'Reservation time'],
  ['Depoya serbest bırakınca', 'When released to the warehouse'],
  ['Emir oluşturulunca', 'When the task is created'],
  ['Toplama başlayınca', 'When picking starts'],
  ['Minimum karşılama (%)', 'Minimum fulfilment (%)'],
  ['Fark politikası', 'Variance policy'],
  ['Onaya gönder', 'Send for approval'],
  ['İzin ver', 'Allow'],
  ['Engelle', 'Block'],
  ['Transfer onayı zorunlu', 'Transfer approval required'],
  ['Emirli transferde kullanıcı zorunlu', 'Assignee required for task-based transfer'],
  ['Birden fazla kullanıcı atanabilir', 'Allow multiple assignees'],
  ['Emirli transferi otomatik serbest bırak', 'Automatically release task-based transfer'],
  ['Kaynak operasyonu ve hedef kabul', 'Source operation and destination receipt'],
  ['Kısmi toplamaya izin ver', 'Allow partial picking'],
  ['Kısmi sevke izin ver', 'Allow partial dispatch'],
  ['Kısmi kabule izin ver', 'Allow partial receipt'],
  ['Hedef depo kabulü zorunlu', 'Destination warehouse receipt required'],
  ['Transit stok oluştur', 'Create in-transit stock'],
  ['Raf yerleştirme zorunlu', 'Putaway required'],
  ['Kaynak raf zorunlu', 'Source location required'],
  ['Hedef raf zorunlu', 'Destination location required'],
  ['Sevk/plaka bilgisi zorunlu', 'Shipment/vehicle information required'],
  ['Doğrudan transfer davranışı', 'Direct transfer behaviour'],
  ['İki adım: kaynak → transit → hedef', 'Two steps: source → transit → destination'],
  ['Politika transfer oluşturulurken başlığa snapshot alınır. Devam eden transferler sonradan değişen ayarlardan etkilenmez.', 'The policy is snapshotted onto the transfer header at creation. Existing transfers are not affected by later policy changes.'],
  ['Politikayı Kaydet', 'Save Policy'],
  ['Cari, belge ve depo', 'Customer, document and warehouse'],
  ['Cari', 'Customer'],
  ['Toplama emri kullanıcıları', 'Picking task assignees'],
  ['Sevk kalemleri', 'Shipment lines'],
  ['Sevk Taslağı Oluştur', 'Create Shipment Draft'],
  ['Hazırlama alanı', 'Staging location'],
  ['Yükleme alanı', 'Loading location'],
  ['Araç plakası', 'Vehicle plate'],
  ['Taşıyıcı kodu', 'Carrier code'],
  ['Harici referans', 'External reference'],
  ['Palet / kasa zorunlu', 'Pallet / container required'],
  ['Kalem ekle', 'Add line'],
  ['Önce stok seçin', 'Select stock first'],
  ['Stok takip politikası', 'Stock tracking policy'],
  ['Yapılandırma kodu', 'Configuration code'],
  ['Planlanan sevk', 'Planned shipment'],
  ['Planlanan varış', 'Planned arrival'],
  ['Belge tarihi', 'Document date'],
  ['Kaynak depo', 'Source warehouse'],
  ['Hedef depo', 'Destination warehouse'],
  ['Kaynak raf', 'Source location'],
  ['Hedef raf', 'Destination location'],
  ['Açıklama', 'Description'],
  ['Öncelik', 'Priority'],
  ['Miktar', 'Quantity'],
  ['Birim', 'Unit'],
  ['Sevk', 'Shipment'],
  ['Kayıt Zamanı', 'Created At'],
  ['Kayıt Eden Kullanıcı', 'Created By'],
  ['Kayıt Eden', 'Created By'],
  ['Güncelleme Zamanı', 'Updated At'],
  ['Güncelleyen Kullanıcı', 'Updated By'],
  ['Son Güncelleyen', 'Updated By'],
  ['Yapılandırma Kodu', 'Configuration Code'],
  ['Yapılandırma', 'Configuration'],
  ['Belge Numarası', 'Document Number'],
  ['Belge No', 'Document No'],
  ['Belge Tarihi', 'Document Date'],
  ['Mal Kabul', 'Goods Receipt'],
  ['Ambar Giriş', 'Warehouse Inbound'],
  ['Ambar Çıkış', 'Warehouse Outbound'],
  ['Depolar Arası Transfer', 'Inter-Warehouse Transfer'],
  ['Stok Hareket Defteri', 'Stock Movement Ledger'],
  ['Depo Stok Bakiyesi', 'Warehouse Stock Balance'],
  ['Stok Seri Bakiyesi', 'Stock Serial Balance'],
  ['Raf Bakiyesi', 'Location Balance'],
  ['Toplam Miktar', 'Total Quantity'],
  ['Kalan Miktar', 'Remaining Quantity'],
  ['Kabul Miktarı', 'Received Quantity'],
  ['Planlanan Miktar', 'Planned Quantity'],
  ['Rezerve Miktar', 'Reserved Quantity'],
  ['Kullanılabilir Miktar', 'Available Quantity'],
  ['İşlem Tipi', 'Operation Type'],
  ['Hareket Tipi', 'Movement Type'],
  ['Kaynak Depo', 'Source Warehouse'],
  ['Hedef Depo', 'Destination Warehouse'],
  ['Kaynak Raf', 'Source Location'],
  ['Hedef Raf', 'Destination Location'],
  ['Son Kullanma Tarihi', 'Expiration Date'],
  ['Üretim Tarihi', 'Manufacturing Date'],
  ['Araç Plakası', 'Vehicle Plate'],
  ['Çekici Plakası', 'Truck Plate'],
  ['İrsaliye No', 'Dispatch Note No'],
  ['İrsaliye', 'Dispatch Note'],
  ['İşlemler', 'Actions'],
  ['Görüntüle', 'View'],
  ['Düzenle', 'Edit'],
  ['Güncelle', 'Update'],
  ['Kayıt ID', 'Record ID'],
  ['Kayıt', 'Record'],
  ['Oluşturan', 'Created By'],
  ['Oluşturma', 'Creation'],
  ['Güncellenme', 'Updated'],
  ['Stok Kodu', 'Stock Code'],
  ['Stok Adı', 'Stock Name'],
  ['Cari Kodu', 'Customer Code'],
  ['Cari Adı', 'Customer Name'],
  ['Şube', 'Branch'],
  ['Depo', 'Warehouse'],
  ['Raf', 'Location'],
  ['Konum', 'Location'],
  ['Stok', 'Stock'],
  ['Miktar', 'Quantity'],
  ['Birim', 'Unit'],
  ['Seri', 'Serial'],
  ['Lot', 'Lot'],
  ['Durum', 'Status'],
  ['Kalite', 'Quality'],
  ['Karantina', 'Quarantine'],
  ['Onay', 'Approval'],
  ['Öncelik', 'Priority'],
  ['Açıklama', 'Description'],
  ['Tarih', 'Date'],
  ['Saat', 'Time'],
  ['Kullanıcı', 'User'],
  ['Rol', 'Role'],
  ['İzin', 'Permission'],
  ['Grup', 'Group'],
  ['Adı', 'Name'],
  ['Kod', 'Code'],
  ['Tip', 'Type'],
  ['Sıra', 'Sequence'],
  ['Beklenen', 'Expected'],
  ['Kabul', 'Receipt'],
  ['Toplanan', 'Picked'],
  ['Sevk', 'Shipment'],
  ['Alınan', 'Received'],
  ['Aktif', 'Active'],
  ['Pasif', 'Inactive'],
];

export function localizeLegacyUiText(value: string, language?: string): string {
  if (!value || normalizeLanguage(language) === 'tr') return value;

  let translated = value;
  for (const [source, target] of ENGLISH_PHRASES) {
    translated = translated.split(source).join(target);
  }
  return translated;
}
