import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import type { TFunction } from 'i18next';
import { Barcode, Box, Download, FilePenLine, Loader2, Pencil, Printer, QrCode, Save, Send, Sparkles, Trash2, Type, X } from 'lucide-react';
import { toast } from 'sonner';
import { AdvancedDataGrid, type GridColumn } from '@/components/shared/AdvancedDataGrid';
import { AppDropdown } from '@/components/shared/AppDropdown';
import { requiredActionColumn, systemColumns } from '@/components/shared/GridSystemColumns';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import { usePermissionAccess } from '@/features/access-control/hooks/usePermissionAccess';
import { useModuleTranslation } from '@/hooks/useModuleTranslation';
import { barcodeDesignerApi } from '../api/barcode-designer.api';
import { BarcodeLabelCanvas, type BarcodeCanvasHandle } from './BarcodeLabelCanvas';
import { sampleDocument, type BarcodeLabelType, type BarcodeSchemaField, type BarcodeTemplatePayload, type BarcodeTemplateRow, type BarcodeTemplateVersion, type LabelDocument, type LabelElement } from '../types/barcode-designer.types';

const empty=():BarcodeTemplatePayload=>({branchCode:'0',templateCode:'',displayName:'',labelType:'Product',widthMm:100,heightMm:70,dpi:203,isActive:true});
const types:BarcodeLabelType[]=['Product','SerialLot','Location','Logistics','Sscc'];

export function BarcodeDesignerPage(){
  const {t,moduleReady}=useModuleTranslation('barcode-designer'); const {can}=usePermissionAccess(); const cache=useQueryClient();
  const [metadataMode,setMetadataMode]=useState<'create'|'edit'|null>(null); const [form,setForm]=useState<BarcodeTemplatePayload>(empty()); const [editing,setEditing]=useState<BarcodeTemplateRow|null>(null); const [designer,setDesigner]=useState<BarcodeTemplateRow|null>(null); const [deleteTarget,setDeleteTarget]=useState<BarcodeTemplateRow|null>(null); const [busy,setBusy]=useState(false);
  const openCreate=async()=>{setEditing(null);setForm(empty());setMetadataMode('create')};
  const openEdit=useCallback(async(row:BarcodeTemplateRow)=>{setEditing(row);setForm({branchCode:row.branchCode,templateCode:row.templateCode,displayName:row.displayName,labelType:row.labelType,widthMm:row.widthMm,heightMm:row.heightMm,dpi:row.dpi,isActive:row.isActive});setMetadataMode('edit')},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{if(metadataMode==='create'){const id=await barcodeDesignerApi.create(form);toast.success(t('messages.created'));setMetadataMode(null);const row=await barcodeDesignerApi.get(id);setDesigner(row)}else if(editing){await barcodeDesignerApi.update(editing.id,form);toast.success(t('messages.saved'));setMetadataMode(null)}await cache.invalidateQueries({queryKey:['advanced-grid','barcode-designer-v2']})}catch(error){toast.error(message(error))}finally{setBusy(false)}};
  const remove=async()=>{if(!deleteTarget)return;setBusy(true);try{await barcodeDesignerApi.delete(deleteTarget.id);toast.success(t('messages.deleted'));setDeleteTarget(null);await cache.invalidateQueries({queryKey:['advanced-grid','barcode-designer-v2']})}catch(error){toast.error(message(error))}finally{setBusy(false)}};
  const columns=useMemo<GridColumn<BarcodeTemplateRow>[]>(()=>moduleReady?[...systemColumns<BarcodeTemplateRow>(),
    {key:'templateCode',label:t('columns.code'),render:r=><span className="font-mono font-semibold">{r.templateCode}</span>},{key:'displayName',label:t('columns.name'),render:r=>r.displayName},{key:'labelType',label:t('columns.type'),render:r=>t(`types.${r.labelType}`)},{key:'widthMm',label:t('columns.size'),render:r=>`${r.widthMm} × ${r.heightMm} mm`},{key:'dpi',label:t('columns.dpi'),render:r=>r.dpi},{key:'isActive',label:t('columns.status'),render:r=><Badge active={r.isActive} text={r.isActive?t('status.active'):t('status.passive')}/>},{key:'draftVersionId',label:t('columns.draft'),render:r=>r.draftVersionId?`#${r.draftVersionId}`:t('status.none')},{key:'publishedVersionId',label:t('columns.published'),render:r=>r.publishedVersionId?`#${r.publishedVersionId}`:t('status.none')},
    {key:'actions',label:t('columns.actions'),...requiredActionColumn,render:r=><div className="flex gap-1">{can('WMS.BARCODE_DESIGNER.UPDATE')&&<button title={t('actions.design')} onClick={()=>setDesigner(r)} className="rounded-lg border p-2 text-cyan-600"><FilePenLine className="size-4"/></button>}{can('WMS.BARCODE_DESIGNER.UPDATE')&&<button title={t('actions.edit')} onClick={()=>void openEdit(r)} className="rounded-lg border p-2 text-blue-600"><Pencil className="size-4"/></button>}{can('WMS.BARCODE_DESIGNER.DELETE')&&<button title={t('actions.delete')} onClick={()=>setDeleteTarget(r)} className="rounded-lg border p-2 text-red-600"><Trash2 className="size-4"/></button>}</div>}
  ]:[],[can,moduleReady,openEdit,t]);
  if(!moduleReady)return <section className="grid min-h-[50vh] place-items-center"><Loader2 className="size-7 animate-spin"/></section>;
  return <><AdvancedDataGrid pageKey="barcode-designer-v2" title={t('page.title')} description={t('page.description')} columns={columns} fetchPage={barcodeDesignerApi.getPaged} toolbarAction={can('WMS.BARCODE_DESIGNER.CREATE')?{label:t('page.new'),run:openCreate}:undefined}/>
    {metadataMode&&<MetadataDialog title={t(`form.${metadataMode}`)} form={form} setForm={setForm} busy={busy} t={t} onClose={()=>setMetadataMode(null)} onSubmit={submit}/>} 
    {designer&&<DesignerDialog template={designer} onClose={()=>{setDesigner(null);void cache.invalidateQueries({queryKey:['advanced-grid','barcode-designer-v2']})}} t={t} canPublish={can('WMS.BARCODE_DESIGNER.PUBLISH')} canPrint={can('WMS.BARCODE_DESIGNER.PRINT')}/>} 
    {deleteTarget&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setDeleteTarget(null)}}><DialogContent className="!max-w-md bg-[var(--wms-app-panel)]"><DialogTitle>{t('actions.delete')}</DialogTitle><p>{deleteTarget.templateCode} - {deleteTarget.displayName}</p><div className="flex justify-end gap-2"><button className="rounded-xl border px-4 py-2" onClick={()=>setDeleteTarget(null)}>{t('form.cancel')}</button><button className="rounded-xl bg-red-600 px-4 py-2 text-white" onClick={()=>void remove()}>{t('actions.delete')}</button></div></DialogContent></Dialog>}
  </>;
}

function DesignerDialog({template,onClose,t,canPublish,canPrint}:{template:BarcodeTemplateRow;onClose:()=>void;t:TFunction;canPublish:boolean;canPrint:boolean}){
  const canvas=useRef<BarcodeCanvasHandle>(null); const [doc,setDoc]=useState<LabelDocument>(()=>sampleDocument(template.widthMm,template.heightMm,template.dpi)); const [selected,setSelected]=useState<string|null>(null); const [fields,setFields]=useState<BarcodeSchemaField[]>([]); const [versions,setVersions]=useState<BarcodeTemplateVersion[]>([]); const [currentVersion,setCurrentVersion]=useState<BarcodeTemplateVersion|null>(null); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(true);
  useEffect(()=>{let active=true;void Promise.all([barcodeDesignerApi.getDraft(template.id),barcodeDesignerApi.getVersions(template.id),barcodeDesignerApi.getFields()]).then(([draft,all,schema])=>{if(!active)return;if(draft){try{setDoc(JSON.parse(draft.templateJson));setCurrentVersion(draft)}catch{setDoc(sampleDocument(template.widthMm,template.heightMm,template.dpi))}}setVersions(all);setFields(schema)}).catch(e=>toast.error(message(e))).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[template.dpi,template.heightMm,template.id,template.widthMm]);
  const element=doc.elements.find(x=>x.id===selected)??null; const updateElement=(next:LabelElement)=>setDoc(value=>({...value,elements:value.elements.map(item=>item.id===next.id?next:item)}));
  const add=(type:LabelElement['type'])=>{const next:LabelElement={id:crypto.randomUUID(),type,xMm:5,yMm:5,widthMm:type==='qrcode'||type==='datamatrix'?24:50,heightMm:type==='text'?8:type==='rectangle'?25:20,text:type==='text'?'Yeni metin':undefined,value:type==='barcode'?'8691234567890':type==='qrcode'||type==='datamatrix'?'https://v3rii.com':undefined,symbology:type==='barcode'?'code128':type==='qrcode'?'qrcode':type==='datamatrix'?'datamatrix':undefined,fontSize:12};setDoc(value=>({...value,elements:[...value.elements,next]}));setSelected(next.id)};
  const save=async()=>{setBusy(true);try{const version=await barcodeDesignerApi.saveDraft(template.id,JSON.stringify(doc),notes);setCurrentVersion(version);setVersions(await barcodeDesignerApi.getVersions(template.id));toast.success(t('messages.saved'))}catch(e){toast.error(message(e))}finally{setBusy(false)}};
  const publish=async()=>{if(!currentVersion){toast.error('Önce taslağı kaydedin.');return}setBusy(true);try{const version=await barcodeDesignerApi.publish(template.id,currentVersion.id);setCurrentVersion(version);setVersions(await barcodeDesignerApi.getVersions(template.id));toast.success(t('messages.published'))}catch(e){toast.error(message(e))}finally{setBusy(false)}};
  const dataUrl=()=>canvas.current?.toDataUrl(Math.max(3,template.dpi/96))??'';
  const loadDemo=()=>{setDoc(sampleDocument(template.widthMm,template.heightMm,template.dpi));setSelected(null);setCurrentVersion(null);setNotes('Hazır WMS stok etiketi demosu');toast.success(t('messages.demoLoaded'))};
  const pdf=async()=>{const previewWindow=window.open('','_blank');try{if(!previewWindow)throw new Error(t('messages.popupBlocked'));previewWindow.opener=null;previewWindow.document.title=t('messages.preparingPdf');previewWindow.document.body.innerHTML=`<main style="font:16px system-ui;padding:32px">${t('messages.preparingPdf')}</main>`;const {jsPDF}=await import('jspdf');const imageUrl=dataUrl();if(!imageUrl)throw new Error(t('messages.canvasNotReady'));const documentPdf=new jsPDF({orientation:template.widthMm>template.heightMm?'landscape':'portrait',unit:'mm',format:[template.widthMm,template.heightMm]});documentPdf.addImage(imageUrl,'PNG',0,0,template.widthMm,template.heightMm);openAndDownloadPdf(documentPdf.output('blob'),`${template.templateCode}-ornek-v${currentVersion?.versionNo??'taslak'}.pdf`,previewWindow);toast.success(t('messages.pdf'))}catch(error){previewWindow?.close();toast.error(message(error))}};
  const print=()=>{const url=dataUrl();const win=window.open('','_blank','noopener,noreferrer');if(!win){toast.error('Yazdırma penceresi tarayıcı tarafından engellendi.');return}win.document.write(`<html><head><title>${template.displayName}</title><style>@page{size:${template.widthMm}mm ${template.heightMm}mm;margin:0}html,body{margin:0;width:${template.widthMm}mm;height:${template.heightMm}mm;overflow:hidden}img{display:block;width:100%;height:100%}</style></head><body><img src="${url}" onload="window.print();window.onafterprint=()=>window.close()"/></body></html>`);win.document.close();toast.success(t('messages.print'))};
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent showCloseButton={false} className="h-[calc(100vh-1rem)] w-[calc(100vw-1rem)] !max-w-none overflow-hidden border bg-[var(--wms-app-panel)] p-0">
    <div className="flex h-full flex-col"><header className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><DialogTitle>{t('editor.title')}</DialogTitle><p className="text-sm text-slate-500">{template.templateCode} · {template.widthMm} × {template.heightMm} mm · {template.dpi} DPI</p></div><div className="flex flex-wrap gap-2"><button onClick={loadDemo} disabled={busy} className="tool"><Sparkles className="size-4"/>{t('actions.demo')}</button><button onClick={()=>void save()} disabled={busy} className="tool"><Save className="size-4"/>{t('actions.saveDraft')}</button>{canPublish&&<button onClick={()=>void publish()} disabled={busy||!currentVersion} className="tool"><Send className="size-4"/>{t('actions.publish')}</button>}{canPrint&&<><button onClick={pdf} disabled={busy} className="tool"><Download className="size-4"/>{t('actions.pdf')}</button><button onClick={print} disabled={busy} className="tool"><Printer className="size-4"/>{t('actions.print')}</button></>}<button onClick={onClose} className="rounded-xl border p-2"><X className="size-4"/></button></div></header>
    <div className="grid min-h-0 flex-1 overflow-auto lg:grid-cols-[220px_minmax(420px,1fr)_290px] lg:overflow-hidden"><aside className="order-2 border-r p-4 lg:order-1 lg:overflow-auto"><h3 className="mb-3 font-semibold">{t('editor.toolbox')}</h3><div className="grid grid-cols-2 gap-2"><Tool icon={<Type/>} label={t('actions.addText')} onClick={()=>add('text')}/><Tool icon={<Barcode/>} label={t('actions.addBarcode')} onClick={()=>add('barcode')}/><Tool icon={<QrCode/>} label={t('actions.addQr')} onClick={()=>add('qrcode')}/><Tool icon={<QrCode/>} label={t('actions.addMatrix')} onClick={()=>add('datamatrix')}/><Tool icon={<Box/>} label={t('actions.addBox')} onClick={()=>add('rectangle')}/></div><h3 className="mb-2 mt-6 font-semibold">{t('editor.bindings')}</h3><div className="space-y-1">{fields.map(f=><button key={f.key} title={f.sampleValue} onClick={()=>element&&updateElement({...element,binding:f.key,value:undefined,text:undefined})} className="w-full rounded-lg border px-2 py-1.5 text-left text-xs hover:bg-[var(--wms-brand-soft)]"><strong>{f.label}</strong><span className="block truncate text-slate-500">{f.sampleValue}</span></button>)}</div></aside>
      <main className="order-1 min-h-[360px] min-w-0 overflow-auto p-4 lg:order-2 lg:min-h-0">{busy?<div className="grid h-full place-items-center"><Loader2 className="animate-spin"/></div>:<><div className="mb-3 flex items-center gap-2 rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-3 py-2 text-sm"><Sparkles className="size-4 text-cyan-500"/><span>{t('editor.demoHint')}</span></div><BarcodeLabelCanvas ref={canvas} document={doc} selectedId={selected} onSelect={setSelected} onChange={updateElement}/></>}</main>
      <aside className="order-3 border-l p-4 lg:overflow-auto">
        <Properties element={element} update={updateElement} remove={()=>{setDoc(v=>({...v,elements:v.elements.filter(x=>x.id!==selected)}));setSelected(null)}} fields={fields} t={t}/>
        <h3 className="mb-2 mt-6 font-semibold">{t('editor.notes')}</h3>
        <textarea className="w-full rounded-xl border bg-transparent p-2 text-sm" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500}/>
        <h3 className="mb-2 mt-6 font-semibold">{t('editor.versions')}</h3>
        <div className="space-y-2">{versions.map(v=><button key={v.id} onClick={()=>{try{setDoc(JSON.parse(v.templateJson));setCurrentVersion(v);setSelected(null)}catch{toast.error('Sürüm okunamadı.')}}} className={`w-full rounded-xl border p-2 text-left text-xs ${currentVersion?.id===v.id?'border-cyan-500 bg-cyan-500/10':''}`}><strong>v{v.versionNo}</strong>{v.isPublished&&<span className="ml-2 text-emerald-600">Yayınlandı</span>}<span className="block truncate text-slate-500">{v.notes||'Not yok'}</span></button>)}</div>
      </aside></div></div>
  </DialogContent></Dialog>;
}

function Properties({element,update,remove,fields,t}:{element:LabelElement|null;update:(e:LabelElement)=>void;remove:()=>void;fields:BarcodeSchemaField[];t:TFunction}){if(!element)return <><h3 className="font-semibold">{t('editor.properties')}</h3><p className="mt-3 text-sm text-slate-500">{t('editor.noSelection')}</p></>;const set=(key:keyof LabelElement,value:unknown)=>update({...element,[key]:value} as LabelElement);return <><h3 className="mb-3 font-semibold">{t('editor.properties')}</h3><div className="space-y-3"><Field label={t('editor.value')}><input className="input" value={element.value??element.text??''} onChange={e=>set(element.type==='text'?'text':'value',e.target.value)}/></Field><Field label={t('editor.binding')}><AppDropdown value={element.binding??''} onValueChange={v=>set('binding',v||undefined)} options={[{value:'',label:'Sabit değer'},...fields.map(f=>({value:f.key,label:f.label}))]} searchable/></Field>{element.type==='barcode'&&<Field label={t('editor.symbology')}><AppDropdown value={element.symbology??'code128'} onValueChange={v=>set('symbology',v)} options={[{value:'code128',label:'Code 128'},{value:'gs1-128',label:'GS1-128'}]}/></Field>}<div className="grid grid-cols-2 gap-2">{(['xMm','yMm','widthMm','heightMm'] as const).map((key,i)=><Field key={key} label={t(`editor.${['x','y','width','height'][i]}`)}><input type="number" step="0.1" min="0" className="input" value={element[key]} onChange={e=>set(key,Number(e.target.value))}/></Field>)}</div>{element.type==='text'&&<Field label={t('editor.font')}><input type="number" min="6" max="72" className="input" value={element.fontSize??12} onChange={e=>set('fontSize',Number(e.target.value))}/></Field>}<button onClick={remove} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-red-300 px-3 py-2 text-sm text-red-600"><Trash2 className="size-4"/>{t('editor.remove')}</button></div></>}

function MetadataDialog({title,form,setForm,busy,t,onClose,onSubmit}:{title:string;form:BarcodeTemplatePayload;setForm:(v:BarcodeTemplatePayload)=>void;busy:boolean;t:TFunction;onClose:()=>void;onSubmit:(e:FormEvent)=>void}){const set=(key:keyof BarcodeTemplatePayload,value:unknown)=>setForm({...form,[key]:value} as BarcodeTemplatePayload);return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent showCloseButton={false} className="!max-w-2xl bg-[var(--wms-app-panel)]"><div className="flex justify-between"><DialogTitle>{title}</DialogTitle><button onClick={onClose}><X/></button></div><form onSubmit={onSubmit} className="grid gap-4 sm:grid-cols-2"><Field label={t('form.code')}><input required maxLength={50} className="input" value={form.templateCode} onChange={e=>set('templateCode',e.target.value.toUpperCase())}/></Field><Field label={t('form.name')}><input required maxLength={150} className="input" value={form.displayName} onChange={e=>set('displayName',e.target.value)}/></Field><Field label={t('form.type')}><AppDropdown value={form.labelType} onValueChange={v=>set('labelType',v)} options={types.map(v=>({value:v,label:t(`types.${v}`)}))}/></Field><Field label={t('form.dpi')}><AppDropdown value={String(form.dpi)} onValueChange={v=>set('dpi',Number(v))} options={[203,300,600].map(v=>({value:String(v),label:`${v} DPI`}))}/></Field><Field label={t('form.width')}><input type="number" min="10" max="300" step="0.1" className="input" value={form.widthMm} onChange={e=>set('widthMm',Number(e.target.value))}/></Field><Field label={t('form.height')}><input type="number" min="10" max="500" step="0.1" className="input" value={form.heightMm} onChange={e=>set('heightMm',Number(e.target.value))}/></Field><label className="flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>set('isActive',e.target.checked)}/>{t('form.active')}</label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2">{t('form.cancel')}</button><button disabled={busy} className="rounded-xl bg-[var(--wms-brand-primary)] px-4 py-2 text-white">{t('form.save')}</button></div></form></DialogContent></Dialog>}
function Tool({icon,label,onClick}:{icon:ReactNode;label:string;onClick:()=>void}){return <button onClick={onClick} className="flex flex-col items-center gap-1 rounded-xl border p-3 text-xs hover:bg-[var(--wms-brand-soft)]"><span className="[&>svg]:size-5">{icon}</span>{label}</button>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="space-y-1 text-sm"><span className="font-medium">{label}</span>{children}</label>}
function Badge({active,text}:{active:boolean;text:string}){return <span className={`rounded-full px-2 py-1 text-xs ${active?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{text}</span>}
function message(error:unknown){return error instanceof Error?error.message:'İşlem tamamlanamadı.'}
function openAndDownloadPdf(blob:Blob,fileName:string,previewWindow:Window){const previewUrl=URL.createObjectURL(blob);previewWindow.location.replace(previewUrl);const downloadUrl=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=downloadUrl;anchor.download=fileName;anchor.style.display='none';document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(downloadUrl),30_000);window.setTimeout(()=>URL.revokeObjectURL(previewUrl),300_000)}
