import { useEffect, useMemo, useState, type FormEvent, type ReactElement } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, Boxes, CalendarRange, CheckCircle2, Clock3, Eye, GitCompareArrows, Loader2, Plus, Search, Sparkles, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { formatProjectDate, formatProjectDateTime } from '@/lib/project-format';
import { generatorProductionApi } from './api';
import type { CreateGeneratorProjectRequest, GeneratorPlanPreview, GeneratorPolicy } from './types';
import {
  GeneratorEmpty, GeneratorLoading, GeneratorMetric, GeneratorPageHeader, GeneratorStatus, GeneratorTag,
  generatorError, generatorPartLabel, gpField, gpPanel, gpPrimaryButton, gpSecondaryButton, useGeneratorDefinitions, useGeneratorProjects,
} from './GeneratorProductionScreenKit';

function localDateTime(date: Date): string { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16); }
function initialProject(policy: GeneratorPolicy): CreateGeneratorProjectRequest {
  const start = new Date(); start.setHours(8, 0, 0, 0); const delivery = new Date(start); delivery.setDate(delivery.getDate() + policy.defaultLeadTimeDays); delivery.setHours(17, 0, 0, 0);
  return { projectCode: '', projectName: '', generatorType: '', serialNumber: '', customerCode: '', customerName: '', externalWorkOrderNo: '', sourceSystemCode: 'WMS', plannedStartAtUtc: localDateTime(start), plannedDeliveryAtUtc: localDateTime(delivery), priority: policy.defaultProjectPriority, quantity: policy.defaultProjectQuantity, hasStator: true, hasRotor: true, hasStiffener: true, includeFinalAssembly: true, planningOrder: 0, description: '' };
}

export function GeneratorProductionProjectListPage(): ReactElement {
  const queryClient = useQueryClient(); const projects = useGeneratorProjects(); const [search, setSearch] = useState('');
  const remove = useMutation({ mutationFn: generatorProductionApi.deleteProject, onSuccess: () => { toast.success('Taslak proje silindi.'); void queryClient.invalidateQueries({ queryKey: ['generator-production'] }); }, onError: (error) => toast.error(generatorError(error)) });
  const rows = useMemo(() => { const term = search.trim().toLocaleLowerCase('tr-TR'); return (projects.data?.items ?? []).filter((x) => !term || `${x.projectCode} ${x.projectName} ${x.customerName ?? ''} ${x.generatorType ?? ''} ${x.serialNumber ?? ''}`.toLocaleLowerCase('tr-TR').includes(term)); }, [projects.data, search]);
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Projeler" title="Jeneratör Projeleri" description="Proje kartlarını, teslim hedeflerini, üretim kapsamını ve tamamlanma durumunu yönetin." actions={<><Link className={gpSecondaryButton} to="/warehouse/production/generator/planning"><CalendarRange className="size-4" /> Planlama havuzu</Link><Link className={gpPrimaryButton} to="/warehouse/production/generator/projects/new"><Plus className="size-4" /> Yeni proje</Link></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={Boxes} label="Toplam proje" value={projects.data?.totalCount ?? 0} /><GeneratorMetric icon={CalendarRange} label="Planlanan" value={(projects.data?.items ?? []).filter((x) => x.status === 'Planned').length} /><GeneratorMetric icon={Clock3} label="Üretimde" value={(projects.data?.items ?? []).filter((x) => x.status === 'InProgress').length} /><GeneratorMetric icon={CheckCircle2} label="Tamamlanan" value={(projects.data?.items ?? []).filter((x) => x.status === 'Completed').length} /></div>
    <div className={`${gpPanel} p-3`}><label className="relative block max-w-xl"><Search className="absolute left-3 top-3.5 size-4 text-[var(--wms-app-text-muted)]" /><input className={`${gpField} pl-10`} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Proje kodu, müşteri, tip veya seri ara" /></label></div>
    {projects.isLoading ? <GeneratorLoading text="Projeler yükleniyor…" /> : rows.length === 0 ? <GeneratorEmpty text="Arama ölçütüne uygun jeneratör projesi bulunamadı." /> : <div className={`${gpPanel} overflow-auto`}><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr className="border-b border-[var(--wms-app-border)] text-xs uppercase tracking-wide text-[var(--wms-app-text-muted)]"><th className="p-3">Proje</th><th className="p-3">Müşteri</th><th className="p-3">Tip / seri</th><th className="p-3">Durum</th><th className="p-3">Öncelik</th><th className="p-3">Adet</th><th className="p-3">Başlangıç</th><th className="p-3">Teslim</th><th className="p-3">İlerleme</th><th className="p-3">İşlem</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-[var(--wms-app-border)] hover:bg-[color-mix(in_oklab,var(--wms-brand-primary)_5%,transparent)]"><td className="p-3"><Link className="font-black text-[var(--wms-brand-primary)] hover:underline" to={`/warehouse/production/generator/projects/${row.id}`}>{row.projectCode}</Link><p className="text-xs text-[var(--wms-app-text-muted)]">{row.projectName}</p></td><td className="p-3">{row.customerName || '—'}</td><td className="p-3">{row.generatorType || '—'}<p className="text-xs text-[var(--wms-app-text-muted)]">{row.serialNumber || 'Seri yok'}</p></td><td className="p-3"><GeneratorStatus status={row.status} /></td><td className="p-3 font-black">{row.priority}</td><td className="p-3">{row.quantity}</td><td className="p-3">{formatProjectDate(row.plannedStartAtUtc)}</td><td className="p-3">{formatProjectDate(row.plannedDeliveryAtUtc)}</td><td className="p-3"><strong>{row.completedOperationCount}/{row.operationCount}</strong></td><td className="p-3"><div className="flex gap-1"><Link className="rounded-lg p-2 hover:bg-[var(--wms-app-surface)]" aria-label="Detay" to={`/warehouse/production/generator/projects/${row.id}`}><Eye className="size-4" /></Link>{['Draft', 'ReadyToPlan'].includes(row.status) && <button className="rounded-lg p-2 text-red-500 hover:bg-red-500/10" aria-label="Sil" disabled={remove.isPending} onClick={() => { if (window.confirm(`${row.projectCode} taslak projesi silinsin mi?`)) remove.mutate(row.id); }}><Trash2 className="size-4" /></button>}</div></td></tr>)}</tbody></table></div>}
  </section>;
}

export function GeneratorProductionProjectCreatePage(): ReactElement {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const definitions = useGeneratorDefinitions(); const [form, setForm] = useState<CreateGeneratorProjectRequest>();
  useEffect(() => { if (!form && definitions.data?.policy.id) setForm(initialProject(definitions.data.policy)); }, [definitions.data?.policy, form]);
  const create = useMutation({ mutationFn: generatorProductionApi.createProject, onSuccess: (row) => { toast.success('Jeneratör projesi oluşturuldu.'); void queryClient.invalidateQueries({ queryKey: ['generator-production'] }); navigate(`/warehouse/production/generator/projects/${row.id}`); }, onError: (error) => toast.error(generatorError(error)) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form) return; create.mutate({ ...form, plannedStartAtUtc: new Date(form.plannedStartAtUtc).toISOString(), plannedDeliveryAtUtc: new Date(form.plannedDeliveryAtUtc).toISOString() }); };
  if (!form || !definitions.data?.policy.id) return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Projeler" title="Yeni Jeneratör Projesi" description="Proje varsayılanları üretim parametrelerinden hazırlanıyor." /><GeneratorLoading /></section>;
  const policy = definitions.data.policy;
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Projeler" title="Yeni Jeneratör Projesi" description="Proje kimliğini, teslim hedefini ve üretilecek stator/rotor/taşıyıcı kol kapsamını tanımlayın." actions={<Link className={gpSecondaryButton} to="/warehouse/production/generator/projects"><ArrowLeft className="size-4" /> Projelere dön</Link>} />
    <form onSubmit={submit} className={`${gpPanel} grid gap-5 p-5 md:grid-cols-2 xl:grid-cols-4`}>
      <label className="text-sm font-bold">Proje kodu<input required maxLength={100} className={`${gpField} mt-1`} value={form.projectCode} onChange={(e) => setForm({ ...form, projectCode: e.target.value })} /></label><label className="text-sm font-bold md:col-span-2">Proje adı<input required maxLength={300} className={`${gpField} mt-1`} value={form.projectName} onChange={(e) => setForm({ ...form, projectName: e.target.value })} /></label><label className="text-sm font-bold">Jeneratör tipi<input className={`${gpField} mt-1`} value={form.generatorType ?? ''} onChange={(e) => setForm({ ...form, generatorType: e.target.value })} /></label>
      <label className="text-sm font-bold">Seri numarası<input className={`${gpField} mt-1`} value={form.serialNumber ?? ''} onChange={(e) => setForm({ ...form, serialNumber: e.target.value })} /></label><label className="text-sm font-bold">Müşteri kodu<input className={`${gpField} mt-1`} value={form.customerCode ?? ''} onChange={(e) => setForm({ ...form, customerCode: e.target.value })} /></label><label className="text-sm font-bold md:col-span-2">Müşteri adı<input className={`${gpField} mt-1`} value={form.customerName ?? ''} onChange={(e) => setForm({ ...form, customerName: e.target.value })} /></label>
      <label className="text-sm font-bold">Dış iş emri no<input className={`${gpField} mt-1`} value={form.externalWorkOrderNo ?? ''} onChange={(e) => setForm({ ...form, externalWorkOrderNo: e.target.value })} /></label><label className="text-sm font-bold">Kaynak sistem<input className={`${gpField} mt-1`} value={form.sourceSystemCode ?? ''} onChange={(e) => setForm({ ...form, sourceSystemCode: e.target.value })} /></label><label className="text-sm font-bold">Plan başlangıcı<input required type="datetime-local" className={`${gpField} mt-1`} value={form.plannedStartAtUtc} onChange={(e) => setForm({ ...form, plannedStartAtUtc: e.target.value })} /></label><label className="text-sm font-bold">Teslim tarihi<input required type="datetime-local" className={`${gpField} mt-1`} value={form.plannedDeliveryAtUtc} onChange={(e) => setForm({ ...form, plannedDeliveryAtUtc: e.target.value })} /></label>
      <label className="text-sm font-bold">Öncelik ({policy.minimumProjectPriority}–{policy.maximumProjectPriority})<input required type="number" min={policy.minimumProjectPriority} max={policy.maximumProjectPriority} className={`${gpField} mt-1`} value={form.priority} onChange={(e) => setForm({ ...form, priority: Number(e.target.value) })} /></label><label className="text-sm font-bold">Jeneratör adedi<input required type="number" min={1} max={policy.maximumProjectQuantity} className={`${gpField} mt-1`} value={form.quantity} onChange={(e) => setForm({ ...form, quantity: Number(e.target.value) })} /></label><label className="text-sm font-bold">Manuel plan sırası<input type="number" className={`${gpField} mt-1`} value={form.planningOrder} onChange={(e) => setForm({ ...form, planningOrder: Number(e.target.value) })} /><small className="mt-1 block font-normal text-[var(--wms-app-text-muted)]">Manuel sıralama stratejisinde kullanılır.</small></label>
      <fieldset className="md:col-span-2 xl:col-span-4"><legend className="mb-2 text-sm font-bold">Üretim kapsamı</legend><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{([['hasStator', 'Stator'], ['hasRotor', 'Rotor'], ['hasStiffener', 'Taşıyıcı kol'], ['includeFinalAssembly', 'Final montaj']] as const).map(([key, label]) => <label key={key} className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--wms-app-border)] px-3 text-sm font-bold"><input type="checkbox" checked={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.checked })} />{label}</label>)}</div></fieldset>
      <label className="text-sm font-bold md:col-span-2 xl:col-span-4">Açıklama<textarea className={`${gpField} mt-1 min-h-28 py-3`} value={form.description ?? ''} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>
      <div className="flex justify-end gap-2 md:col-span-2 xl:col-span-4"><Link className={gpSecondaryButton} to="/warehouse/production/generator/projects">Vazgeç</Link><button className={gpPrimaryButton} disabled={create.isPending}>{create.isPending ? <Loader2 className="size-4 animate-spin" /> : <Plus className="size-4" />} Projeyi oluştur</button></div>
    </form>
  </section>;
}

export function GeneratorProductionProjectDetailPage(): ReactElement {
  const id = Number(useParams().id); const project = useQuery({ queryKey: ['generator-production', 'project', id], queryFn: () => generatorProductionApi.project(id), enabled: Number.isFinite(id) }); const operations = useQuery({ queryKey: ['generator-production', 'project', id, 'operations'], queryFn: () => generatorProductionApi.projectOperations(id), enabled: Number.isFinite(id) });
  if (project.isLoading) return <GeneratorLoading text="Proje detayı yükleniyor…" />; if (!project.data) return <GeneratorEmpty text="Jeneratör projesi bulunamadı." />;
  const row = project.data; const completed = (operations.data ?? []).filter((x) => x.status === 'Completed').length; const scope = [['Stator', row.hasStator], ['Rotor', row.hasRotor], ['Taşıyıcı kol', row.hasStiffener], ['Final montaj', row.includeFinalAssembly]] as const;
  return <section className="space-y-5"><GeneratorPageHeader eyebrow={`Jeneratör Üretim / ${row.projectCode}`} title={row.projectName} description="Proje kartı, kapsam, plan takvimi ve operasyon gerçekleşmelerinin tek proje görünümü." actions={<><Link className={gpSecondaryButton} to="/warehouse/production/generator/projects"><ArrowLeft className="size-4" /> Projeler</Link><Link className={gpPrimaryButton} to="/warehouse/production/generator/planning"><CalendarRange className="size-4" /> Planlamaya git</Link></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={Boxes} label="Jeneratör adedi" value={row.quantity} /><GeneratorMetric icon={CalendarRange} label="Teslim" value={formatProjectDate(row.plannedDeliveryAtUtc)} /><GeneratorMetric icon={Clock3} label="Operasyon" value={(operations.data ?? []).length} /><GeneratorMetric icon={CheckCircle2} label="Tamamlanan" value={completed} /></div>
    <div className="grid gap-4 xl:grid-cols-[1fr_1.4fr]"><article className={`${gpPanel} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-[var(--wms-brand-primary)]">{row.projectCode}</p><h2 className="mt-1 text-lg font-black">Proje bilgileri</h2></div><GeneratorStatus status={row.status} /></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-[var(--wms-app-text-muted)]">Müşteri</dt><dd className="font-bold">{row.customerName || '—'}</dd></div><div><dt className="text-[var(--wms-app-text-muted)]">Tip / seri</dt><dd className="font-bold">{row.generatorType || '—'} / {row.serialNumber || '—'}</dd></div><div><dt className="text-[var(--wms-app-text-muted)]">Plan başlangıcı</dt><dd>{formatProjectDateTime(row.plannedStartAtUtc)}</dd></div><div><dt className="text-[var(--wms-app-text-muted)]">Teslim</dt><dd>{formatProjectDateTime(row.plannedDeliveryAtUtc)}</dd></div><div><dt className="text-[var(--wms-app-text-muted)]">Öncelik</dt><dd className="font-black">{row.priority}</dd></div><div><dt className="text-[var(--wms-app-text-muted)]">Dış iş emri</dt><dd>{row.externalWorkOrderNo || '—'}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2">{scope.map(([label, enabled]) => <GeneratorTag key={label} tone={enabled ? 'success' : 'normal'}>{enabled ? '✓ ' : '— '}{label}</GeneratorTag>)}</div>{row.description && <p className="mt-5 border-t border-[var(--wms-app-border)] pt-4 text-sm text-[var(--wms-app-text-muted)]">{row.description}</p>}</article>
      <article className={`${gpPanel} p-5`}><h2 className="text-lg font-black">İlerleme</h2><div className="mt-5 h-3 overflow-hidden rounded-full bg-[var(--wms-app-surface)]"><div className="h-full bg-[var(--wms-brand-primary)]" style={{ width: `${operations.data?.length ? completed / operations.data.length * 100 : 0}%` }} /></div><div className="mt-2 flex justify-between text-xs text-[var(--wms-app-text-muted)]"><span>{completed} tamamlandı</span><span>{operations.data?.length ?? 0} toplam operasyon</span></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{Object.entries((operations.data ?? []).reduce<Record<string, number>>((acc, op) => { acc[op.partType] = (acc[op.partType] ?? 0) + 1; return acc; }, {})).map(([part, count]) => <div key={part} className="rounded-xl border border-[var(--wms-app-border)] p-3"><strong>{generatorPartLabel(part)}</strong><p className="text-xs text-[var(--wms-app-text-muted)]">{count} operasyon</p></div>)}</div></article></div>
    {operations.isLoading ? <GeneratorLoading text="Operasyonlar yükleniyor…" /> : (operations.data ?? []).length === 0 ? <GeneratorEmpty text="Bu proje henüz planlanmadı. Planlama havuzundan projeyi seçip önizleme oluşturun." /> : <div className={`${gpPanel} overflow-auto`}><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b border-[var(--wms-app-border)]"><th className="p-3">Ünite / bileşen</th><th className="p-3">İstasyon</th><th className="p-3">Operasyon</th><th className="p-3">Durum</th><th className="p-3">Plan başlangıç</th><th className="p-3">Plan bitiş</th><th className="p-3">Risk</th></tr></thead><tbody>{operations.data?.map((op) => <tr key={op.id} className="border-b border-[var(--wms-app-border)]"><td className="p-3">{op.unitIndex} / {generatorPartLabel(op.partType)}</td><td className="p-3"><strong className="font-mono">{op.stationCode}</strong><p className="text-xs text-[var(--wms-app-text-muted)]">{op.stationName}</p></td><td className="p-3">{op.operationName}</td><td className="p-3"><GeneratorStatus status={op.status} /></td><td className="p-3">{formatProjectDateTime(op.plannedStartAtUtc)}</td><td className="p-3">{formatProjectDateTime(op.plannedEndAtUtc)}</td><td className="p-3"><div className="flex gap-1">{op.isCritical && <GeneratorTag tone="warning">Kritik</GeneratorTag>}{op.hasProblem && <GeneratorTag tone="danger">Problem</GeneratorTag>}{op.hasMaterialShortage && <GeneratorTag tone="danger">Malzeme</GeneratorTag>}</div></td></tr>)}</tbody></table></div>}
  </section>;
}

export function GeneratorProductionScenarioPage(): ReactElement {
  const projects = useGeneratorProjects(); const [selected, setSelected] = useState<number[]>([]); const [earliestStart, setEarliestStart] = useState(''); const [preview, setPreview] = useState<GeneratorPlanPreview | null>(null);
  const simulate = useMutation({ mutationFn: () => generatorProductionApi.preview(selected, earliestStart ? new Date(earliestStart).toISOString() : undefined), onSuccess: setPreview, onError: (error) => toast.error(generatorError(error)) });
  const selectable = (projects.data?.items ?? []).filter((x) => ['Draft', 'ReadyToPlan', 'Planned'].includes(x.status)); const projectedEnd = preview?.items.length ? new Date(Math.max(...preview.items.map((x) => new Date(x.plannedEndAtUtc).getTime()))) : null;
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Planlama" title="Senaryo Simülasyonu" description="Projeleri ve alternatif başlangıç zamanını seçip üretim planını veritabanına yazmadan karşılaştırın." actions={<Link className={gpSecondaryButton} to="/warehouse/production/generator/planning"><ArrowLeft className="size-4" /> Planlama havuzu</Link>} />
    <div className="grid gap-4 xl:grid-cols-[1fr_1.4fr]"><section className={`${gpPanel} p-5`}><h2 className="font-black">Senaryo kapsamı</h2><label className="mt-4 block text-sm font-bold">En erken başlangıç (isteğe bağlı)<input type="datetime-local" className={`${gpField} mt-1`} value={earliestStart} onChange={(e) => setEarliestStart(e.target.value)} /></label><div className="mt-4 max-h-96 space-y-2 overflow-auto">{selectable.map((row) => <label key={row.id} className="flex items-start gap-3 rounded-xl border border-[var(--wms-app-border)] p-3"><input className="mt-1" type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected((value) => value.includes(row.id) ? value.filter((id) => id !== row.id) : [...value, row.id])} /><div className="min-w-0 flex-1"><strong>{row.projectCode}</strong><p className="truncate text-xs text-[var(--wms-app-text-muted)]">{row.projectName} · Teslim {formatProjectDate(row.plannedDeliveryAtUtc)}</p></div><GeneratorStatus status={row.status} /></label>)}</div><button className={`${gpPrimaryButton} mt-4 w-full`} disabled={selected.length === 0 || simulate.isPending} onClick={() => simulate.mutate()}>{simulate.isPending ? <Loader2 className="size-4 animate-spin" /> : <GitCompareArrows className="size-4" />} Senaryoyu hesapla</button></section>
      <section className={`${gpPanel} p-5`}><h2 className="font-black">Simülasyon sonucu</h2>{!preview ? <p className="mt-4 text-sm text-[var(--wms-app-text-muted)]">Bir veya daha fazla proje seçip senaryoyu hesaplayın. Bu işlem mevcut planı değiştirmez.</p> : <><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[var(--wms-app-border)] p-3"><span className="text-xs text-[var(--wms-app-text-muted)]">Operasyon</span><strong className="block text-2xl">{preview.items.length}</strong></div><div className="rounded-xl border border-[var(--wms-app-border)] p-3"><span className="text-xs text-[var(--wms-app-text-muted)]">Uyarı / hata</span><strong className="block text-2xl">{preview.issues.length}</strong></div><div className="rounded-xl border border-[var(--wms-app-border)] p-3"><span className="text-xs text-[var(--wms-app-text-muted)]">Tahmini bitiş</span><strong className="block text-sm">{projectedEnd ? formatProjectDateTime(projectedEnd) : '—'}</strong></div></div><div className="mt-4 space-y-2">{preview.issues.map((issue, index) => <div key={`${issue.ruleCode}-${index}`} className={`flex gap-2 rounded-xl border p-3 text-sm ${issue.severity === 'Error' ? 'border-red-500/50' : 'border-amber-500/50'}`}><AlertTriangle className="size-5 shrink-0" /><div><strong className="font-mono text-xs">{issue.ruleCode}</strong><p>{issue.message}</p></div></div>)}{preview.issues.length === 0 && <p className="rounded-xl bg-emerald-500/10 p-3 text-sm font-bold text-emerald-500">Senaryoda engel veya uyarı bulunmadı.</p>}</div><div className="mt-4 max-h-72 overflow-auto rounded-xl border border-[var(--wms-app-border)]"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-[var(--wms-app-border)]"><th className="p-3">Proje</th><th className="p-3">Bileşen</th><th className="p-3">İstasyon</th><th className="p-3">Başlangıç</th><th className="p-3">Bitiş</th></tr></thead><tbody>{preview.items.map((item) => <tr key={item.key} className="border-b border-[var(--wms-app-border)]"><td className="p-3 font-bold">{item.projectCode} / {item.unitIndex}</td><td className="p-3">{generatorPartLabel(item.partType)}</td><td className="p-3 font-mono">{item.stationCode}</td><td className="p-3">{formatProjectDateTime(item.plannedStartAtUtc)}</td><td className="p-3">{formatProjectDateTime(item.plannedEndAtUtc)}</td></tr>)}</tbody></table></div></>}</section></div>
  </section>;
}

export function GeneratorProductionAssistantPage(): ReactElement {
  const projects = useGeneratorProjects(); const candidates = useMemo(() => (projects.data?.items ?? []).filter((x) => ['Draft', 'ReadyToPlan'].includes(x.status)).sort((a, b) => b.priority - a.priority || new Date(a.plannedDeliveryAtUtc).getTime() - new Date(b.plannedDeliveryAtUtc).getTime()), [projects.data]); const now = Date.now(); const delayed = (projects.data?.items ?? []).filter((x) => new Date(x.plannedDeliveryAtUtc).getTime() < now && x.status !== 'Completed');
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Planlama" title="Planlama Asistanı" description="Teslim tarihi, öncelik ve plan durumuna göre açıklanabilir öneriler üretir; planı kendiliğinden değiştirmez." actions={<Link className={gpPrimaryButton} to="/warehouse/production/generator/scenarios"><GitCompareArrows className="size-4" /> Senaryo oluştur</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={Sparkles} label="Plan bekleyen" value={candidates.length} /><GeneratorMetric icon={AlertTriangle} label="Teslim tarihi geçen" value={delayed.length} /><GeneratorMetric icon={Boxes} label="Toplam proje" value={projects.data?.totalCount ?? 0} /><GeneratorMetric icon={CheckCircle2} label="Tamamlanan" value={(projects.data?.items ?? []).filter((x) => x.status === 'Completed').length} /></div>
    {projects.isLoading ? <GeneratorLoading /> : <div className="grid gap-4 xl:grid-cols-[1.2fr_1fr]"><section className={`${gpPanel} overflow-hidden`}><header className="border-b border-[var(--wms-app-border)] p-4"><h2 className="font-black">Önerilen planlama sırası</h2><p className="text-xs text-[var(--wms-app-text-muted)]">Yüksek öncelik, ardından yakın teslim tarihi</p></header>{candidates.length ? <div className="divide-y divide-[var(--wms-app-border)]">{candidates.slice(0, 15).map((row, index) => <div key={row.id} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 p-4"><span className="flex size-8 items-center justify-center rounded-full bg-[var(--wms-brand-primary)] text-xs font-black text-[var(--wms-brand-on-primary)]">{index + 1}</span><div><Link className="font-black text-[var(--wms-brand-primary)]" to={`/warehouse/production/generator/projects/${row.id}`}>{row.projectCode}</Link><p className="text-xs text-[var(--wms-app-text-muted)]">Öncelik {row.priority} · Teslim {formatProjectDate(row.plannedDeliveryAtUtc)}</p></div><GeneratorStatus status={row.status} /></div>)}</div> : <p className="p-5 text-sm text-[var(--wms-app-text-muted)]">Plan bekleyen proje yok.</p>}</section><section className={`${gpPanel} p-4`}><h2 className="font-black">Asistan aksiyonları</h2><div className="mt-4 space-y-3">{candidates.length > 0 && <Link className="block rounded-xl border border-[var(--wms-app-border)] p-4 hover:border-[var(--wms-brand-primary)]" to="/warehouse/production/generator/planning"><strong>{candidates[0].projectCode} ile planlamaya başla</strong><p className="mt-1 text-xs text-[var(--wms-app-text-muted)]">En yüksek öncelikli açık projeyi planlama havuzunda seçin.</p></Link>}{delayed.length > 0 && <Link className="block rounded-xl border border-red-500/50 bg-red-500/5 p-4" to="/warehouse/production/generator/reports"><strong className="text-red-500">{delayed.length} teslim riski için analiz aç</strong><p className="mt-1 text-xs text-[var(--wms-app-text-muted)]">Gecikme ve istasyon yükünü birlikte inceleyin.</p></Link>}<Link className="block rounded-xl border border-[var(--wms-app-border)] p-4 hover:border-[var(--wms-brand-primary)]" to="/warehouse/production/generator/scenarios"><strong>Alternatif başlangıç senaryosu dene</strong><p className="mt-1 text-xs text-[var(--wms-app-text-muted)]">Veritabanına yazmadan yeni bir plan önizlemesi hesaplayın.</p></Link></div></section></div>}
  </section>;
}
