import { useMemo, type ReactElement } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Boxes, CalendarClock, CheckCircle2, Clock3, Factory, History, PackageCheck, RefreshCw, ShieldAlert, Truck, Warehouse } from 'lucide-react';
import { Link } from 'react-router-dom';
import { formatProjectDateTime } from '@/lib/project-format';
import { generatorProductionApi } from './api';
import type { GeneratorScheduleRow, GeneratorStation } from './types';
import {
  GeneratorEmpty, GeneratorLoading, GeneratorMetric, GeneratorPageHeader, GeneratorStatus, GeneratorTag,
  generatorPartLabel, gpPanel, gpSecondaryButton, useGeneratorDefinitions, useGeneratorProjects, useGeneratorWideSchedule,
} from './GeneratorProductionScreenKit';

function groupByStation(rows: GeneratorScheduleRow[]): Array<[string, GeneratorScheduleRow[]]> {
  return Object.entries(rows.reduce<Record<string, GeneratorScheduleRow[]>>((result, row) => { (result[`${row.stationCode}|${row.stationName}`] ??= []).push(row); return result; }, {}));
}
function durationMinutes(row: GeneratorScheduleRow): number { return Math.max(0, (new Date(row.plannedEndAtUtc).getTime() - new Date(row.plannedStartAtUtc).getTime()) / 60_000); }

export function GeneratorProductionStationBoardPage(): ReactElement {
  const schedule = useGeneratorWideSchedule(true); const rows = (schedule.data ?? []).filter((x) => !['Completed', 'Cancelled'].includes(x.status)); const grouped = groupByStation(rows);
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Yürütme" title="Canlı İstasyon Panosu" description="SA, RA ve FA alanlarındaki açık işleri istasyon kuyruğu olarak izleyin. Operasyon işlemleri Andon ekranında yapılır." actions={<><Link className={gpSecondaryButton} to="/warehouse/production/generator/andon">Operasyon ekranı</Link><button className={gpSecondaryButton} onClick={() => schedule.refetch()}><RefreshCw className="size-4" /> Yenile</button></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={Factory} label="Açık operasyon" value={rows.length} /><GeneratorMetric icon={Clock3} label="Devam eden" value={rows.filter((x) => x.status === 'InProgress').length} /><GeneratorMetric icon={AlertTriangle} label="Problemli" value={rows.filter((x) => x.hasProblem).length} /><GeneratorMetric icon={ShieldAlert} label="Malzeme blokajı" value={rows.filter((x) => x.hasMaterialShortage).length} /></div>
    {schedule.isLoading ? <GeneratorLoading /> : grouped.length === 0 ? <GeneratorEmpty text="Açık jeneratör operasyonu bulunmuyor." /> : <div className="grid gap-4 xl:grid-cols-2">{grouped.map(([key, stationRows]) => { const [code, name] = key.split('|'); return <article key={key} className={`${gpPanel} overflow-hidden`}><header className="flex items-center justify-between border-b border-[var(--wms-app-border)] p-4"><div><p className="font-mono text-xs font-black text-[var(--wms-brand-primary)]">{code}</p><h2 className="font-black">{name}</h2></div><GeneratorTag>{stationRows.length} iş</GeneratorTag></header><div className="divide-y divide-[var(--wms-app-border)]">{stationRows.sort((a, b) => new Date(a.plannedStartAtUtc).getTime() - new Date(b.plannedStartAtUtc).getTime()).map((row) => <div key={row.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><Link className="font-black text-[var(--wms-brand-primary)]" to={`/warehouse/production/generator/projects/${row.projectId}`}>{row.projectCode} / Ünite {row.unitIndex}</Link><p className="text-sm font-bold">{row.operationName}</p><p className="text-xs text-[var(--wms-app-text-muted)]">{generatorPartLabel(row.partType)} · {formatProjectDateTime(row.plannedStartAtUtc)}</p></div><GeneratorStatus status={row.status} /></div><div className="mt-2 flex gap-1">{row.isCritical && <GeneratorTag tone="warning">Kritik</GeneratorTag>}{row.hasProblem && <GeneratorTag tone="danger">Problem</GeneratorTag>}{row.hasMaterialShortage && <GeneratorTag tone="danger">Malzeme</GeneratorTag>}</div></div>)}</div></article>; })}</div>}
  </section>;
}

export function GeneratorProductionFactoryMapPage(): ReactElement {
  const definitions = useGeneratorDefinitions(); const schedule = useGeneratorWideSchedule(true); const now = Date.now();
  const occupancy = useMemo(() => (schedule.data ?? []).reduce<Record<number, GeneratorScheduleRow[]>>((result, row) => { if (row.status === 'InProgress' || (new Date(row.plannedStartAtUtc).getTime() <= now && new Date(row.plannedEndAtUtc).getTime() >= now && !['Completed', 'Cancelled'].includes(row.status))) (result[row.stationId] ??= []).push(row); return result; }, {}), [schedule.data, now]);
  const areas = useMemo(() => Object.entries((definitions.data?.stations ?? []).reduce<Record<string, GeneratorStation[]>>((result, station) => { (result[station.area] ??= []).push(station); return result; }, {})), [definitions.data]);
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Dijital Fabrika" title="Üretim Haritası" description="Fiziksel yerleşim çizimi yerine WMS ana verisinden üretilen alan-istasyon haritasında anlık yükü görün." actions={<button className={gpSecondaryButton} onClick={() => schedule.refetch()}><RefreshCw className="size-4" /> Canlı veriyi yenile</button>} />
    {(definitions.isLoading || schedule.isLoading) ? <GeneratorLoading /> : <div className={`${gpPanel} overflow-hidden bg-[radial-gradient(circle_at_top,color-mix(in_oklab,var(--wms-brand-primary)_12%,transparent),transparent_45%)] p-5`}><div className="grid gap-5 xl:grid-cols-3">{areas.map(([area, stations]) => <section key={area} className="rounded-2xl border border-[var(--wms-app-border)] bg-[color-mix(in_oklab,var(--wms-app-panel)_88%,transparent)] p-4"><header className="mb-3 flex items-center justify-between"><h2 className="font-black">{area}</h2><GeneratorTag>{stations.length} istasyon</GeneratorTag></header><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">{stations.sort((a, b) => a.planningOrder - b.planningOrder).map((station) => { const active = occupancy[station.id] ?? []; const problem = active.some((x) => x.hasProblem || x.hasMaterialShortage); return <article key={station.id} className={`rounded-xl border p-3 ${problem ? 'border-red-500/70 bg-red-500/5' : active.length ? 'border-sky-500/70 bg-sky-500/5' : 'border-[var(--wms-app-border)]'}`}><div className="flex items-start justify-between"><strong className="font-mono text-xs text-[var(--wms-brand-primary)]">{station.code}</strong><span className={`size-2.5 rounded-full ${problem ? 'bg-red-500' : active.length ? 'bg-sky-500' : 'bg-emerald-500'}`} /></div><p className="mt-1 text-sm font-bold">{station.name}</p><p className="mt-2 text-xs text-[var(--wms-app-text-muted)]">{active.length}/{station.maxParallelJobs} anlık iş</p>{active.slice(0, 2).map((row) => <p key={row.id} className="mt-1 truncate text-xs font-bold">{row.projectCode} · {row.operationCode}</p>)}</article>; })}</div></section>)}</div><div className="mt-5 flex flex-wrap gap-4 text-xs text-[var(--wms-app-text-muted)]"><span className="flex items-center gap-2"><i className="size-2.5 rounded-full bg-emerald-500" /> Boş / hazır</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-full bg-sky-500" /> Aktif yük</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-full bg-red-500" /> Problem veya eksik malzeme</span></div></div>}
  </section>;
}

export function GeneratorProductionMaterialControlPage(): ReactElement {
  const schedule = useGeneratorWideSchedule(); const risks = (schedule.data ?? []).filter((x) => x.hasMaterialShortage);
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Malzeme" title="Malzeme Kontrol" description="Jeneratör operasyonlarına bağlanan genel üretim iş emirlerindeki malzeme blokajlarını proje ve istasyon bazında izleyin." actions={<Link className={gpSecondaryButton} to="/warehouse/production-transfers"><Warehouse className="size-4" /> Üretim transferlerine git</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={ShieldAlert} label="Bloke operasyon" value={risks.length} /><GeneratorMetric icon={Boxes} label="Etkilenen proje" value={new Set(risks.map((x) => x.projectId)).size} /><GeneratorMetric icon={Factory} label="Etkilenen istasyon" value={new Set(risks.map((x) => x.stationId)).size} /><GeneratorMetric icon={CheckCircle2} label="Malzeme riski olmayan" value={(schedule.data ?? []).filter((x) => !x.hasMaterialShortage).length} /></div>
    {schedule.isLoading ? <GeneratorLoading /> : risks.length === 0 ? <GeneratorEmpty text="Açık malzeme eksiği bulunan jeneratör operasyonu yok. Ayrıntılı stok ve transfer hareketleri genel WMS üretim transferlerinde yönetilir." /> : <div className={`${gpPanel} overflow-auto`}><table className="w-full min-w-[950px] text-left text-sm"><thead><tr className="border-b border-[var(--wms-app-border)]"><th className="p-3">Proje</th><th className="p-3">Ünite / bileşen</th><th className="p-3">İstasyon</th><th className="p-3">Operasyon</th><th className="p-3">Plan zamanı</th><th className="p-3">Durum</th></tr></thead><tbody>{risks.map((row) => <tr key={row.id} className="border-b border-[var(--wms-app-border)]"><td className="p-3"><Link className="font-black text-[var(--wms-brand-primary)]" to={`/warehouse/production/generator/projects/${row.projectId}`}>{row.projectCode}</Link></td><td className="p-3">{row.unitIndex} / {generatorPartLabel(row.partType)}</td><td className="p-3"><strong className="font-mono">{row.stationCode}</strong><p className="text-xs text-[var(--wms-app-text-muted)]">{row.stationName}</p></td><td className="p-3">{row.operationName}</td><td className="p-3">{formatProjectDateTime(row.plannedStartAtUtc)}</td><td className="p-3"><GeneratorTag tone="danger">Malzeme eksiği</GeneratorTag></td></tr>)}</tbody></table></div>}
  </section>;
}

export function GeneratorProductionOutboundPage(): ReactElement {
  const schedule = useGeneratorWideSchedule(); const outbound = (schedule.data ?? []).filter((x) => x.stationCode === 'OUTBOUND');
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Çıkış" title="Paketleme ve Sevkiyata Devir" description="Final montajdan çıkan jeneratörlerin sevkiyat tamponundaki durumunu izleyin ve WMS paketleme/sevkiyat süreçlerine geçin." actions={<><Link className={gpSecondaryButton} to="/warehouse/packing"><PackageCheck className="size-4" /> Paketleme</Link><Link className={gpSecondaryButton} to="/warehouse/shipments"><Truck className="size-4" /> Sevkiyat</Link></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={Truck} label="Toplam devir" value={outbound.length} /><GeneratorMetric icon={Clock3} label="Bekleyen" value={outbound.filter((x) => !['InProgress', 'Completed'].includes(x.status)).length} /><GeneratorMetric icon={PackageCheck} label="İşlemde" value={outbound.filter((x) => x.status === 'InProgress').length} /><GeneratorMetric icon={CheckCircle2} label="Tamamlanan" value={outbound.filter((x) => x.status === 'Completed').length} /></div>
    {schedule.isLoading ? <GeneratorLoading /> : outbound.length === 0 ? <GeneratorEmpty text="Sevkiyat tamponuna planlanmış jeneratör bulunmuyor." /> : <div className={`${gpPanel} overflow-auto`}><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-[var(--wms-app-border)]"><th className="p-3">Proje</th><th className="p-3">Ünite</th><th className="p-3">Operasyon</th><th className="p-3">Plan başlangıç</th><th className="p-3">Plan bitiş</th><th className="p-3">Durum</th></tr></thead><tbody>{outbound.map((row) => <tr key={row.id} className="border-b border-[var(--wms-app-border)]"><td className="p-3"><Link className="font-black text-[var(--wms-brand-primary)]" to={`/warehouse/production/generator/projects/${row.projectId}`}>{row.projectCode}</Link><p className="text-xs text-[var(--wms-app-text-muted)]">{row.projectName}</p></td><td className="p-3">{row.unitIndex}</td><td className="p-3">{row.operationName}</td><td className="p-3">{formatProjectDateTime(row.plannedStartAtUtc)}</td><td className="p-3">{formatProjectDateTime(row.plannedEndAtUtc)}</td><td className="p-3"><GeneratorStatus status={row.status} /></td></tr>)}</tbody></table></div>}
  </section>;
}

export function GeneratorProductionRevisionsPage(): ReactElement {
  const revisions = useQuery({ queryKey: ['generator-production', 'revisions'], queryFn: () => generatorProductionApi.revisions(undefined, 200) });
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Planlama" title="Plan Revizyon Geçmişi" description="Her plan oluşturma veya yeniden planlama işleminin gerekçesini, zamanını ve etkilenen operasyon sayısını denetleyin." actions={<button className={gpSecondaryButton} onClick={() => revisions.refetch()}><RefreshCw className="size-4" /> Yenile</button>} />
    {revisions.isLoading ? <GeneratorLoading /> : revisions.data?.length ? <div className="space-y-3">{revisions.data.map((revision) => <article key={revision.id} className={`${gpPanel} flex flex-wrap items-start gap-4 p-4`}><span className="rounded-xl bg-[color-mix(in_oklab,var(--wms-brand-primary)_14%,transparent)] p-3 text-[var(--wms-brand-primary)]"><History className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{revision.projectCode || 'Toplu plan'}</strong><GeneratorTag tone={revision.hasPreviousPlan ? 'warning' : 'success'}>{revision.actionType === 'PlanReplaced' ? 'Plan yenilendi' : 'Plan oluşturuldu'}</GeneratorTag></div><p className="mt-1 text-sm">{revision.reason}</p><p className="mt-2 text-xs text-[var(--wms-app-text-muted)]">{formatProjectDateTime(revision.occurredAtUtc)} · Kullanıcı #{revision.actorUserId} · {revision.operationCount} operasyon</p></div>{revision.projectId && <Link className={gpSecondaryButton} to={`/warehouse/production/generator/projects/${revision.projectId}`}>Projeyi aç</Link>}</article>)}</div> : <GeneratorEmpty text="Henüz uygulanmış plan revizyonu yok." />}
  </section>;
}

export function GeneratorProductionReportsPage(): ReactElement {
  const projects = useGeneratorProjects(); const definitions = useGeneratorDefinitions(); const schedule = useGeneratorWideSchedule(); const now = Date.now(); const rows = useMemo(() => schedule.data ?? [], [schedule.data]);
  const late = rows.filter((x) => new Date(x.plannedEndAtUtc).getTime() < now && !['Completed', 'Cancelled'].includes(x.status)); const material = rows.filter((x) => x.hasMaterialShortage); const problems = rows.filter((x) => x.hasProblem);
  const stationLoads = useMemo(() => (definitions.data?.stations ?? []).map((station) => { const stationRows = rows.filter((x) => x.stationId === station.id); return { station, minutes: stationRows.reduce((sum, row) => sum + durationMinutes(row), 0), operations: stationRows.length, risks: stationRows.filter((x) => x.hasProblem || x.hasMaterialShortage).length }; }).sort((a, b) => b.minutes - a.minutes), [definitions.data, rows]);
  return <section className="space-y-5"><GeneratorPageHeader eyebrow="Jeneratör Üretim / Analiz" title="Üretim Analiz Merkezi" description="Proje, gecikme, malzeme ve istasyon yükünü aynı karar destek ekranında değerlendirin." actions={<Link className={gpSecondaryButton} to="/warehouse/production/generator/gantt"><CalendarClock className="size-4" /> Gantt'a git</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><GeneratorMetric icon={Boxes} label="Proje" value={projects.data?.totalCount ?? 0} /><GeneratorMetric icon={AlertTriangle} label="Geciken operasyon" value={late.length} /><GeneratorMetric icon={ShieldAlert} label="Malzeme riski" value={material.length} /><GeneratorMetric icon={Factory} label="Açık problem" value={problems.length} /></div>
    {(projects.isLoading || definitions.isLoading || schedule.isLoading) ? <GeneratorLoading /> : <div className="grid gap-4 xl:grid-cols-[1.3fr_1fr]"><section className={`${gpPanel} overflow-hidden`}><header className="border-b border-[var(--wms-app-border)] p-4"><h2 className="font-black">İstasyon yük sıralaması</h2><p className="text-xs text-[var(--wms-app-text-muted)]">Görüntülenen plan penceresindeki toplam operasyon süresi</p></header><div className="divide-y divide-[var(--wms-app-border)]">{stationLoads.slice(0, 12).map(({ station, minutes, operations, risks }, index) => <div key={station.id} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 p-3"><span className="text-center text-sm font-black text-[var(--wms-app-text-muted)]">{index + 1}</span><div><strong className="font-mono text-xs text-[var(--wms-brand-primary)]">{station.code}</strong><p className="text-sm font-bold">{station.name}</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--wms-app-surface)]"><div className="h-full bg-[var(--wms-brand-primary)]" style={{ width: `${stationLoads[0]?.minutes ? minutes / stationLoads[0].minutes * 100 : 0}%` }} /></div></div><div className="text-right"><strong>{Math.round(minutes / 60)} saat</strong><p className="text-xs text-[var(--wms-app-text-muted)]">{operations} op · {risks} risk</p></div></div>)}</div></section><section className={`${gpPanel} p-4`}><h2 className="font-black">Durum dağılımı</h2><div className="mt-4 space-y-3">{Object.entries(rows.reduce<Record<string, number>>((result, row) => { result[row.status] = (result[row.status] ?? 0) + 1; return result; }, {})).sort((a, b) => b[1] - a[1]).map(([status, count]) => <div key={status} className="flex items-center justify-between rounded-xl border border-[var(--wms-app-border)] p-3"><GeneratorStatus status={status} /><strong>{count}</strong></div>)}</div><div className="mt-5 border-t border-[var(--wms-app-border)] pt-4"><h3 className="font-black">Öncelikli aksiyonlar</h3><div className="mt-3 space-y-2">{late.length > 0 && <Link className="flex items-center justify-between rounded-xl bg-red-500/10 p-3 text-sm font-bold text-red-500" to="/warehouse/production/generator/gantt"><span>{late.length} geciken operasyonu incele</span><AlertTriangle className="size-4" /></Link>}{material.length > 0 && <Link className="flex items-center justify-between rounded-xl bg-amber-500/10 p-3 text-sm font-bold text-amber-500" to="/warehouse/production/generator/materials"><span>{material.length} malzeme blokajını çöz</span><ShieldAlert className="size-4" /></Link>}{late.length === 0 && material.length === 0 && <p className="rounded-xl bg-emerald-500/10 p-3 text-sm font-bold text-emerald-500">Acil plan veya malzeme aksiyonu yok.</p>}</div></div></section></div>}
  </section>;
}
