export interface CustomerOption { id: number; branchCode: string; customerCode: string; customerName: string }
export interface WarehouseOption { id: number; branchCode: string; warehouseCode: number; warehouseName: string }
export interface LocationOption { id: number; warehouseId: number; code: string; name: string; locationType: string }
export interface PutawayLocationSuggestion extends LocationOption {
  zoneCode?: string;
  currentStockQuantity: number;
  currentAvailableQuantity: number;
  totalLocationQuantity: number;
  capacityQuantity?: number;
  remainingCapacity?: number;
  containsStock: boolean;
  isEmpty: boolean;
  score: number;
  reason: string;
}
export interface SeriesOption { id: number; code: string; name: string; previewDocumentNumber: string; isDefault: boolean }
export interface OpenOrderHeader { siparisNo: string; customerCode?: string; customerName?: string; branchCode?: number; targetWarehouseCode?: number; orderDate?: string; orderedQuantity?: number; deliveredQuantity?: number; remainingQuantity?: number; plannedQuantity?: number; availableQuantity?: number }
export interface OpenOrderLine { siparisNo: string; orderId: number; stockCode?: string; stockName?: string; unitCode?: string; yapCode?: string; yapDescription?: string; customerCode?: string; branchCode?: number; targetWarehouseCode?: number; orderDate?: string; orderedQuantity?: number; deliveredQuantity?: number; remainingQuantity?: number; plannedQuantity?: number; availableQuantity?: number }
export type StockTrackingType = 'None' | 'Lot' | 'Serial' | 'LotAndSerial';
export interface PlannedReceiptTracking { localId: string; quantity: number; lotNo?: string; serialNo?: string; manufacturingDate?: string; expirationDate?: string; description?: string }
export interface SelectedReceiptLine extends OpenOrderLine { stockId: number; quantity: number; targetWarehouseId?: number; targetWarehouseValue?: string | null; receivingLocationId?: number; receivingLocationValue?: string | null; trackingType: StockTrackingType; trackingPolicy: EffectiveStockTrackingPolicy; trackings: PlannedReceiptTracking[]; serialGenerationKey?: string }
export interface CreatedWarehouseInboundTaskResult { id: number; taskNo: string; warehouseId: number; lineCount: number; plannedQuantity: number }
export interface CreateWarehouseInboundResult { id: number; documentNo: string; taskId: number; taskNo: string; lineCount: number; reservedQuantity: number; replayed: boolean; tasks: CreatedWarehouseInboundTaskResult[] }
export interface StockOption { id: number; branchCode: string; erpStockCode: string; stockName?: string; unitCode?: string }
export interface YapCodeOption { id: number; branchCode: string; configurationCode: string; description?: string }
export interface ManualReceiptLine { localId: string; stockId: number; stockCode: string; stockName?: string; yapCodeId?: number; yapCode?: string; quantity: number; unitCode: string; targetWarehouseId: number; targetWarehouseCode?: number; receivingLocationId: number; receivingLocationCode?: string; lotNo?: string; serialNo?: string; manufacturingDate?: string; expirationDate?: string; scannedBarcode?: string; description?: string }
export interface ManualWarehouseInboundResult { id: number; documentNo: string; initiationMode: string; status: string; taskId?: number; taskNo?: string; executionId?: number; stockMovementOperationId?: number; qualityInspectionId?: number; lineCount: number; quantity: number; replayed: boolean }
export interface WarehouseInboundGridRow { id: number; branchCode: string; documentNo: string; documentDate: string; receiptType: string; initiationMode: string; processType: string; status: string; approvalStatus: string; qualityStatus: string; putawayStatus: string; erpIntegrationStatus: string; supplierCode?: string; supplierName?: string; targetWarehouseId: number; warehouseCode: number; warehouseName: string; waybillNo?: string; waybillDate?: string; lineCount: number; expectedQuantity: number; receivedQuantity: number; priority: number; plannedArrivalAtUtc?: string; receivedAtUtc?: string; createdBy?: number; createdDate?: string; updatedBy?: number; updatedDate?: string; rowVersion: string }
export interface WarehouseInboundDetailLine { id: number; lineNo: number; stockId: number; stockCode: string; stockName?: string; yapCodeId?: number; yapCode?: string; unitCode: string; expectedQuantity: number; receivedQuantity: number; acceptedQuantity: number; rejectedQuantity: number; quarantineQuantity: number; shortClosedQuantity: number; putawayQuantity: number; status: string; requireQualityControl: boolean; targetWarehouseId: number; defaultReceivingLocationId?: number; defaultPutawayLocationId?: number }
export interface WarehouseInboundPutawayCandidate { lineId: number; lineNo: number; stockId: number; stockCode: string; stockName?: string; yapCodeId?: number; yapCode?: string; unitCode: string; quantity: number; warehouseId: number; sourceLocationId: number; lotNo?: string; serialNo?: string; stockStatus: string; defaultTargetLocationId?: number }
export interface WarehouseInboundDetail { header: WarehouseInboundGridRow; lines: WarehouseInboundDetailLine[]; putawayCandidates: WarehouseInboundPutawayCandidate[]; sourceDocuments: string[]; taskNumbers: string[]; executionCount: number }
export interface WarehouseInboundLifecycleResult { id: number; documentNo: string; status: string; approvalStatus: string; qualityStatus: string; putawayStatus: string; stockMovementOperationId?: number; affectedQuantity: number; replayed: boolean; rowVersion: string }
export interface WarehouseInboundTaskGridRow { id: number; warehouseInboundId: number; branchCode: string; taskNo: string; documentNo: string; taskType: string; status: string; receiptStatus: string; processType: string; priority: number; warehouseId: number; warehouseCode: number; warehouseName: string; supplierCode?: string; supplierName?: string; lineCount: number; plannedQuantity: number; processedQuantity: number; assigneeCount: number; myAssignmentStatus?: string; plannedStartAtUtc?: string; dueAtUtc?: string; startedAtUtc?: string; completedAtUtc?: string; createdBy?: number; createdDate?: string; updatedBy?: number; updatedDate?: string; rowVersion: string }
export interface WarehouseInboundTaskLineTracking { id: number; sequenceNo: number; plannedQuantity: number; lotNo?: string; serialNo?: string; manufacturingDate?: string; expirationDate?: string; targetWarehouseId: number; toLocationId: number; description?: string }
export interface WarehouseInboundTaskLine { id: number; sequenceNo: number; warehouseInboundLineId: number; stockId: number; stockCode: string; stockName?: string; yapCode?: string; plannedQuantity: number; processedQuantity: number; unitCode: string; status: string; targetWarehouseId: number; toLocationId?: number; trackingType: StockTrackingType; trackings: WarehouseInboundTaskLineTracking[] }
export interface WarehouseInboundTaskAssignment { id: number; userId: number; username: string; displayName: string; role: string; status: string; assignedAtUtc: string; acceptedAtUtc?: string; startedAtUtc?: string; completedAtUtc?: string }
export interface WarehouseInboundTaskDetail { task: WarehouseInboundTaskGridRow; lines: WarehouseInboundTaskLine[]; assignments: WarehouseInboundTaskAssignment[] }
export interface ActiveUserOption { id: number; username: string; email: string; firstName: string; lastName: string; isActive: boolean }
export interface WarehouseInboundLabelBatchRow { id:number; warehouseInboundId:number; documentNo:string; taskId?:number; taskNo?:string; batchNo:string; status:string; totalLabelCount:number; printedLabelCount:number; consumedLabelCount:number; voidLabelCount:number; lastPrintedAtUtc?:string; createdBy?:number; createdDate?:string; rowVersion:string }
export interface WarehouseInboundLabelRow { id:number; batchId:number; warehouseInboundId:number; warehouseInboundLineId?:number; taskLineId?:number; stockId?:number; stockCode:string; stockName?:string; yapCode?:string; quantity:number; unitCode:string; lotNo?:string; serialNo?:string; manufacturingDate?:string; expirationDate?:string; barcodeValue:string; status:string; printCount:number; lastPrintedAtUtc?:string; consumedAtUtc?:string; voidReason?:string; rowVersion:string }
export interface WarehouseInboundLabelBatchDetail { batch:WarehouseInboundLabelBatchRow; labels:WarehouseInboundLabelRow[] }
export interface ReceiveWarehouseInboundTaskResult { executionId:number; stockMovementOperationId:number; warehouseInboundId:number; taskId:number; taskLineId:number; processedQuantity:number; remainingQuantity:number; taskStatus:string; lineStatus:string; qualityInspectionId?:number; consumedLabelId?:number; replayed:boolean }
import type { EffectiveStockTrackingPolicy } from '@/features/stock-tracking/effective-stock-tracking';
