export type MaterialType='Box'|'Pallet'|'Crate'|'Bag'|'Envelope'|'Drum'|'ReturnableContainer'|'Other';
export interface MaterialRow{ id:number;branchCode:string;code:string;name:string;type:MaterialType;tareWeight:number;maxNetWeight:number|null;maxGrossWeight:number|null;innerLength:number|null;innerWidth:number|null;innerHeight:number|null;maxVolume:number|null;isReturnable:boolean;isActive:boolean;description:string|null;createdBy:number|null;createdDate:string|null;updatedBy:number|null;updatedDate:string|null }
export interface StationRow{id:number;branchCode:string;warehouseId:number;locationId:number|null;code:string;name:string;scaleDeviceCode:string|null;printerDefinitionId:number|null;isActive:boolean;description:string|null;createdBy:number|null;createdDate:string|null;updatedBy:number|null;updatedDate:string|null}
export interface SpecificationRow{id:number;branchCode:string;stockId:number|null;stockCode:string|null;stockName:string|null;stockGroupCode:string|null;customerId:number|null;customerCode:string|null;customerName:string|null;packagingMaterialId:number;packagingMaterialCode:string;packagingMaterialName:string;unitsPerHandlingUnit:number|null;maxNetWeight:number|null;maxVolume:number|null;priority:number;isActive:boolean;notes:string|null;createdBy:number|null;createdDate:string|null;updatedBy:number|null;updatedDate:string|null}
export interface StockOption{id:number;branchCode:string;erpStockCode:string;stockName?:string;groupCode?:string|null}
export interface CustomerOption{id:number;branchCode:string;customerCode:string;customerName:string;phone1?:string|null;phone2?:string|null;phone3?:string|null;city?:string|null;district?:string|null;countryCode?:string|null;address?:string|null;customerType?:string|null;taxOffice?:string|null;email?:string|null;website?:string|null;businessUnitCode?:number;lastSyncDate?:string|null}
export interface WarehouseOption{id:number;branchCode:string;warehouseCode:number;warehouseName:string}
export interface LocationOption{id:number;warehouseId:number;code:string;name:string;locationType:string}
export interface PackingPolicy{id:number;branchCode:string;requirePacking:boolean;allowPartialPacking:boolean;allowMixedStock:boolean;allowMixedLot:boolean;allowMixedCustomer:boolean;requireSerialLotScan:boolean;requireWeight:boolean;weightTolerancePercent:number;requireDimensions:boolean;requireSscc:boolean;autoGenerateSscc:boolean;autoPrintLabelOnClose:boolean;allowReopen:boolean;allowRepack:boolean;closePolicy:'Manual'|'AutoWhenComplete';releasePolicy:'Manual'|'OnClose';rowVersion:string}
export interface SessionRow{id:number;branchCode:string;packingNo:string;sourceType:'WarehouseOutbound'|'Shipment'|'WarehouseTransfer'|'Manual';sourceHeaderId:number|null;sourceDocumentNo:string|null;warehouseId:number;packingStationId:number;customerId:number|null;customerCode:string|null;status:'Draft'|'InProgress'|'Packed'|'Released'|'Cancelled';handlingUnitCount:number;totalQuantity:number;totalGrossWeight:number;openedAtUtc:string;closedAtUtc:string|null;releasedAtUtc:string|null;createdBy:number|null;createdDate:string|null;updatedBy:number|null;updatedDate:string|null}
export interface UnitLine{id:number;sourceLineId:number;stockId:number;stockCode:string;yapCode:string|null;unitCode:string;quantity:number;lotNo:string|null;serialNo:string|null;packedAtUtc:string;packedBy:number}
export interface HandlingUnit{id:number;parentHandlingUnitId:number|null;packagingMaterialId:number;handlingUnitNo:string;sscc:string|null;status:string;tareWeight:number;netWeight:number;measuredGrossWeight:number|null;grossWeight:number;length:number|null;width:number|null;height:number|null;volume:number|null;rowVersion:string;lines:UnitLine[]}
export interface SessionDetail{header:SessionRow;rowVersion:string;handlingUnits:HandlingUnit[]}
export interface PackingSourceLine{id:number;lineNo:number;stockCode:string;stockName:string|null;yapCode:string|null;unitCode:string;pickedQuantity:number;packedQuantity:number;remainingQuantity:number;trackingType:string}
export type PackingSourceType='WarehouseOutbound'|'Shipment'|'WarehouseTransfer';
export interface PackingSourceDocumentOption{id:number;documentNo:string;sourceWarehouseId:number;status:string;sourceType:PackingSourceType}
export interface PackingPrintJob{id:number;handlingUnitId:number;packingStationId:number;printerDefinitionId:number|null;status:'Pending'|'Processing'|'Completed'|'Failed'|'Cancelled';copies:number;attemptCount:number;requestedAtUtc:string;completedAtUtc:string|null;lastError:string|null}
export interface ScaleReading{id:number;packingStationId:number;handlingUnitId:number|null;deviceCode:string;grossWeight:number;isStable:boolean;capturedAtUtc:string}
