import { useEffect,useState,type ReactNode } from 'react';
import { Loader2,Save,SlidersHorizontal } from 'lucide-react';
import { toast } from 'sonner';
import { AppDropdown } from '@/components/shared/AppDropdown';
import { useAuthStore } from '@/stores/auth-store';
import { warehouseTransferApi } from '../api/warehouse-transfer.api';
import type { WarehouseTransferPolicy } from '../types/warehouse-transfer.types';

export function WarehouseTransferPolicyPage(){
  const branchCode=useAuthStore(x=>x.branch?.code??'0');
  const[form,setForm]=useState<WarehouseTransferPolicy|null>(null);
  const[saving,setSaving]=useState(false);
  useEffect(()=>{void warehouseTransferApi.policy(branchCode).then(setForm).catch((e:Error)=>toast.error(e.message))},[branchCode]);
  const set=<K extends keyof WarehouseTransferPolicy>(key:K,value:WarehouseTransferPolicy[K])=>setForm(x=>x?{...x,[key]:value}:x);
  const save=async()=>{if(!form)return;setSaving(true);try{setForm(await warehouseTransferApi.updatePolicy(form));toast.success('Transfer politikası kaydedildi.')}catch(e){toast.error(e instanceof Error?e.message:'Politika kaydedilemedi.')}finally{setSaving(false)}};
  if(!form)return <div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin"/></div>;
  return <section className="mx-auto max-w-6xl space-y-5">
    <header><div className="flex items-center gap-2 text-violet-500"><SlidersHorizontal/><span className="text-xs font-bold uppercase tracking-widest">Depolar Arası Transfer</span></div><h1 className="mt-2 text-2xl font-black">Transfer Süreç Politikası</h1><p className="text-sm text-slate-500">Sipariş kaynağı ve yürütme biçiminden rezervasyon, transit, kabul, fark ve yerleştirmeye kadar merkezi kuralları yönetin.</p></header>
    <div className="rounded-2xl border border-[var(--wms-app-border)] bg-[var(--wms-app-panel)] p-5">
      <Section title="İzin verilen başlangıç ve yürütme matrisi"><div className="grid gap-3 md:grid-cols-2"><Toggle label="Netsis emrinden + görevli" value={form.allowOrderBasedTask} set={v=>set('allowOrderBasedTask',v)}/><Toggle label="Serbest stoktan + görevli" value={form.allowStockBasedTask} set={v=>set('allowStockBasedTask',v)}/><Toggle label="Netsis emrinden + doğrudan" value={form.allowOrderBasedDirect} set={v=>set('allowOrderBasedDirect',v)}/><Toggle label="Serbest stoktan + doğrudan" value={form.allowStockBasedDirect} set={v=>set('allowStockBasedDirect',v)}/></div></Section>
      <Section title="Emir, rezervasyon ve karşılama"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Rezervasyon zamanı"><AppDropdown value={form.reservationPolicy} onValueChange={v=>set('reservationPolicy',v as WarehouseTransferPolicy['reservationPolicy'])} options={[{value:'None',label:'Rezervasyon yapma'},{value:'OnCreate',label:'Emir oluşunca'},{value:'OnRelease',label:'Depoya serbest bırakınca'}]}/></Field><Field label="Minimum karşılama (%)"><input className="input" type="number" min="0" max="100" step="0.01" value={form.minimumFulfillmentPercent} onChange={e=>set('minimumFulfillmentPercent',Number(e.target.value))}/></Field><Field label="Fark politikası"><AppDropdown value={form.discrepancyPolicy} onValueChange={v=>set('discrepancyPolicy',v as WarehouseTransferPolicy['discrepancyPolicy'])} options={[{value:'Block',label:'Farkta bloke et'},{value:'AllowWithReason',label:'Neden ile izin ver'},{value:'RequireApproval',label:'Onaya gönder'}]}/></Field></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Toggle label="Transfer onayı zorunlu" value={form.requireApproval} set={v=>set('requireApproval',v)}/><Toggle label="Emirli transferde kullanıcı zorunlu" value={form.requireAssigneeForTask} set={v=>set('requireAssigneeForTask',v)}/><Toggle label="Birden fazla kullanıcı atanabilir" value={form.allowMultipleAssignees} set={v=>set('allowMultipleAssignees',v)}/><Toggle label="Emirli transferi otomatik serbest bırak" value={form.autoReleaseTaskBased} set={v=>set('autoReleaseTaskBased',v)}/></div></Section>
      <Section title="Kaynak operasyonu ve hedef kabul"><div className="grid gap-3 md:grid-cols-2"><Toggle label="Kısmi toplamaya izin ver" value={form.allowPartialPicking} set={v=>set('allowPartialPicking',v)}/><Toggle label="Kısmi sevke izin ver" value={form.allowPartialShipment} set={v=>set('allowPartialShipment',v)}/><Toggle label="Kısmi kabule izin ver" value={form.allowPartialReceipt} set={v=>set('allowPartialReceipt',v)}/><Toggle label="Hedef depo kabulü zorunlu" value={form.requireDestinationAcceptance} set={v=>set('requireDestinationAcceptance',v)}/><Toggle label="Transit stok oluştur" value={form.createTransitInventory} set={v=>set('createTransitInventory',v)}/><Toggle label="Raf yerleştirme zorunlu" value={form.requirePutaway} set={v=>set('requirePutaway',v)}/><Toggle label="Kaynak raf zorunlu" value={form.requireSourceLocation} set={v=>set('requireSourceLocation',v)}/><Toggle label="Hedef raf zorunlu" value={form.requireTargetLocation} set={v=>set('requireTargetLocation',v)}/><Toggle label="Sevk/plaka bilgisi zorunlu" value={form.requireShipmentInformation} set={v=>set('requireShipmentInformation',v)}/></div><div className="mt-4 max-w-md"><Field label="Doğrudan transfer davranışı"><AppDropdown value={form.directPostingPolicy} onValueChange={v=>set('directPostingPolicy',v as WarehouseTransferPolicy['directPostingPolicy'])} options={[{value:'OneStep',label:'Tek adım: kaynak → hedef'},{value:'TwoStepTransit',label:'İki adım: kaynak → transit → hedef'}]}/></Field></div></Section>
      <div className="rounded-xl border border-violet-500/30 bg-violet-500/10 p-4 text-sm">Politika transfer oluşturulurken başlığa snapshot alınır. Devam eden transferler sonradan değişen ayarlardan etkilenmez.</div>
      <div className="mt-5 flex justify-end"><button type="button" onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Politikayı Kaydet</button></div>
    </div>
  </section>;
}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="mb-6 border-b border-[var(--wms-app-border)] pb-6"><h2 className="mb-3 font-black">{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="space-y-1.5 text-sm"><span className="font-semibold">{label}</span>{children}</label>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(value:boolean)=>void}){return <label className="flex items-center justify-between rounded-xl border border-[var(--wms-app-border)] p-3 text-sm"><span>{label}</span><input className="size-4" type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/></label>}
