import { ArrowRight,ClipboardList,Loader2,PackageCheck,PackageOpen,Rows3,Settings2,Truck,UserRoundCog } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useModuleTranslation } from '@/hooks/useModuleTranslation';

const cards=[
  {title:'Netsis Emrinden · Emirli',description:'Netsis transfer emirlerini seçin, açık miktarı ayırın ve toplama görevini kullanıcılara atayın.',href:'/warehouse/transfers/new',icon:ClipboardList},
  {title:'Serbest Stoktan · Emirli',description:'Sipariş bağlantısı olmadan stok kalemlerinden planlı toplama ve sevk emri oluşturun.',href:'/warehouse/transfers/new',icon:UserRoundCog},
  {title:'Netsis Emrinden · Doğrudan',description:'Politika izin veriyorsa Netsis emrine istinaden kullanıcı görevi oluşturmadan transfer başlatın.',href:'/warehouse/transfers/new',icon:Truck},
  {title:'Serbest Stoktan · Doğrudan',description:'Acil ve kontrollü emirsiz transferi serbest stok kalemlerinden başlatın.',href:'/warehouse/transfers/new',icon:PackageOpen},
];
export function WarehouseTransferHubPage(){
  const{t,moduleReady}=useModuleTranslation('warehouse-transfer-v2');
  if(!moduleReady)return <section className="grid min-h-[50vh] place-items-center"><Loader2 className="size-7 animate-spin text-violet-500"/></section>;
  return <section className="space-y-6">
    <header className="rounded-2xl border border-[var(--wms-app-border)] bg-gradient-to-r from-violet-500/10 via-[var(--wms-app-panel)] to-cyan-500/10 p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-500">{t('title')}</p><h1 className="mt-1 text-3xl font-black">{t('hubTitle')}</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-500">{t('hubDescription')}</p></header>
    <section><div className="mb-3"><h2 className="text-lg font-black">01 · Transferi başlat</h2><p className="text-sm text-slate-500">Sipariş kaynağı ve emir yürütme biçimi birbirinden bağımsızdır; dört senaryo aynı domain üzerinde ilerler.</p></div><div className="grid gap-3 md:grid-cols-2">{cards.map(({title,description,href,icon:Icon})=><Link key={title} to={href} className="group rounded-2xl border border-[var(--wms-app-border)] bg-[var(--wms-app-panel)] p-4 transition hover:-translate-y-0.5 hover:border-violet-500/50"><div className="flex justify-between"><div className="grid size-10 place-items-center rounded-xl bg-violet-500/15 text-violet-500"><Icon className="size-5"/></div><ArrowRight className="size-5 text-slate-500 group-hover:text-violet-500"/></div><h3 className="mt-3 font-black">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></Link>)}</div></section>
    <section><div className="mb-3"><h2 className="text-lg font-black">02 · Yürüt, kabul et ve yönet</h2><p className="text-sm text-slate-500">Kaynak toplama/sevk ile hedef kabul/yerleştirme ayrı statüler ve miktarlar üzerinden izlenir.</p></div><div className="grid gap-3 md:grid-cols-3"><Disabled title="Toplama ve Sevk" text="Rezervasyon, görev kabulü, barkodlu toplama ve sevk kesinleştirme." icon={PackageOpen}/><Disabled title="Hedef Kabul ve Yerleştirme" text="Transit kabul, fark nedeni, kısmi kabul ve hedef rafa yerleştirme." icon={PackageCheck}/><Link to="/warehouse/transfers/list" className="rounded-2xl border border-[var(--wms-app-border)] bg-[var(--wms-app-panel)] p-4"><Rows3 className="size-6 text-violet-500"/><h3 className="mt-3 font-black">Transfer Kayıtları</h3><p className="mt-1 text-xs text-slate-500">Tüm varyantları ve miktar ilerlemelerini ortak gridde görüntüleyin.</p></Link></div></section>
    <Link to="/warehouse/transfers/settings" className="flex items-center justify-between rounded-2xl border border-violet-500/30 bg-violet-500/10 p-5"><div className="flex items-center gap-3"><Settings2 className="size-6 text-violet-500"/><div><h3 className="font-black">Transfer Süreç Ayarları</h3><p className="text-xs text-slate-500">Varyant izinleri, rezervasyon, kısmi işlem, transit, kabul, raf ve fark politikaları.</p></div></div><ArrowRight className="size-5"/></Link>
  </section>;
}
function Disabled({title,text,icon:Icon}:{title:string;text:string;icon:typeof PackageOpen}){return <div className="rounded-2xl border border-[var(--wms-app-border)] bg-[var(--wms-app-panel)] p-4 opacity-65"><div className="flex justify-between"><Icon className="size-6 text-violet-500"/><span className="rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-bold text-amber-500">Operasyon dilimi</span></div><h3 className="mt-3 font-black">{title}</h3><p className="mt-1 text-xs text-slate-500">{text}</p></div>}
