import { api } from '@/lib/axios';
import type { GridPage, GridRequest } from '@/components/shared/AdvancedDataGrid';
import type { DropdownPageRequest } from '@/hooks/useDropdownInfiniteSearch';
type Envelope<T>={success:boolean;data:T;message?:string}; const unwrap=<T,>(x:Envelope<T>):T=>{if(!x.success)throw new Error(x.message||'İşlem başarısız.');return x.data};
export type QualityParameter={id:number;branchCode:string;autoCreateInspectionOnReceipt:boolean;defaultInspectionMode:string;defaultFailAction:string;holdInventoryUntilDecision:boolean;blockPutawayUntilDecision:boolean;blockErpPostingUntilDecision:boolean;requireManagerApprovalForRelease:boolean;allowPartialDecision:boolean;allowDirectReceiptWhenNoRule:boolean;blockReceiptWhenLotMissing:boolean;blockReceiptWhenSerialMissing:boolean;blockReceiptWhenExpiryMissing:boolean;defaultQualityLocationId:number|null;defaultQuarantineLocationId:number|null;defaultRejectLocationId:number|null;updatedBy?:number|null;updatedDate?:string|null};
export type QualityRule={id:number;branchCode:string;scopeType:string;stockId:number|null;stockCode?:string|null;stockName?:string|null;stockGroupCode?:string|null;inspectionMode:string;samplingMode:string;samplingValue:number;failAction:string;autoQuarantine:boolean;requireLot:boolean;requireSerial:boolean;requireExpiryDate:boolean;minimumRemainingShelfLifeDays:number|null;isActive:boolean;description?:string|null;createdBy?:number|null;createdDate?:string|null;updatedBy?:number|null;updatedDate?:string|null};
export type QualityInspection={id:number;branchCode:string;inspectionNo:string;sourceDocumentType:string;sourceDocumentNo:string;sourceWaybillNo?:string|null;warehouseCode?:number|null;warehouseName?:string|null;createdByName?:string|null;status:string;lineCount:number;totalQuantity:number;createdAtUtc:string;queuedAtUtc?:string|null;decidedAtUtc?:string|null;createdBy?:number|null;createdDate?:string|null;updatedBy?:number|null;updatedDate?:string|null};
export type QualityInspectionLine={id:number;goodsReceiptLineId?:number|null;stockId:number;stockCode:string;stockName?:string|null;yapCode?:string|null;lotNo?:string|null;serialNo?:string|null;expiryDate?:string|null;quantity:number;sampleQuantity:number;acceptedQuantity:number;rejectedQuantity:number;quarantineQuantity:number;decision:string;reasonCode?:string|null;reasonNote?:string|null;decisionBy?:number|null;decisionAtUtc?:string|null};
export type QualityInspectionDetail={header:QualityInspection;lines:QualityInspectionLine[];note?:string|null;rowVersion:string;allowPartialDecision:boolean;requireManagerApprovalForRelease:boolean};
export const qualityApi={
 getParameters:async(branchCode:string)=>unwrap(await api.get<Envelope<QualityParameter>>(`/api/quality/parameters?branchCode=${encodeURIComponent(branchCode)}`)),
 updateParameters:async(x:Omit<QualityParameter,'id'>)=>unwrap(await api.put<Envelope<QualityParameter>>('/api/quality/parameters',x)),
 rulesPaged:async(p:GridRequest):Promise<GridPage<QualityRule>>=>unwrap(await api.post<Envelope<GridPage<QualityRule>>>('/api/quality/rules/paged',p)),
 createRule:async(x:unknown)=>unwrap(await api.post<Envelope<{id:number}>>('/api/quality/rules',x)),
 updateRule:async(id:number,x:unknown)=>unwrap(await api.put<Envelope<boolean>>(`/api/quality/rules/${id}`,x)),
 deleteRule:async(id:number)=>unwrap(await api.post<Envelope<boolean>>(`/api/quality/rules/${id}/delete`,{})),
 inspectionsPaged:async(p:GridRequest):Promise<GridPage<QualityInspection>>=>unwrap(await api.post<Envelope<GridPage<QualityInspection>>>('/api/quality/inspections/paged',p)),
 inspection:async(id:number):Promise<QualityInspectionDetail>=>unwrap(await api.get<Envelope<QualityInspectionDetail>>(`/api/quality/inspections/${id}`)),
 decide:async(id:number,x:{idempotencyKey:string;decision:string;note?:string;reasonCode?:string;lineIds:number[];rowVersion:string})=>unwrap(await api.post<Envelope<boolean>>(`/api/quality/inspections/${id}/decision`,x)),
 stocks:async(request:{pageNumber:number;pageSize:number;search?:string|null;sortBy?:string;sortDirection?:string;signal?:AbortSignal},branchCode:string)=>unwrap(await api.post<Envelope<{items:Array<{id:number;erpStockCode:string;stockName:string}>;pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>('/api/erp-mirror/stocks/paged',{pageNumber:request.pageNumber,pageSize:request.pageSize,search:request.search??null,sortBy:'erpStockCode',sortDirection:'asc',filterLogic:'and',filters:[{column:'branchCode',operator:'equals',value:branchCode}]},{signal:request.signal})),
 locations:async(request:DropdownPageRequest,branchCode:string)=>unwrap(await api.post<Envelope<{items:Array<{id:number;warehouseId:number;warehouseCode:number;warehouseName:string;code:string;name:string;locationType:string;isQuarantine:boolean;isActive:boolean}>;pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>('/api/locations/paged',{pageNumber:request.pageNumber,pageSize:request.pageSize,search:request.search??null,sortBy:'code',sortDirection:'asc',filterLogic:'and',filters:[{column:'branchCode',operator:'equals',value:branchCode},{column:'isActive',operator:'equals',value:'true'}]},{signal:request.signal})),
};
