import { api } from '@/lib/axios';
import type { GridPage, GridRequest } from '@/components/shared/AdvancedDataGrid';
import type { DropdownPageRequest } from '@/hooks/useDropdownInfiniteSearch';
import { buildDropdownPagedBody } from '@/lib/dropdown-paging';
type Envelope<T>={success:boolean;data:T;message?:string}; const unwrap=<T,>(x:Envelope<T>):T=>{if(!x.success)throw new Error(x.message||'İşlem başarısız.');return x.data};
export type QualityQuarantineDestination={id:number;locationId:number;warehouseId:number;warehouseCode:number;warehouseName:string;locationCode:string;locationName:string;priority:number;isDefault:boolean;isActive:boolean};
export type QualityDecisionDestination={locationId:number;warehouseId:number;warehouseCode:number;warehouseName:string;locationCode:string;locationName:string};
export type QualityDatDocumentSeries={id:number;code:string;name:string;previewDocumentNumber:string;isDefault:boolean};
export type QualityWarehouseRoute={id:number;sourceWarehouseId:number;sourceWarehouseCode:number;sourceWarehouseName:string;qualityLocationId:number|null;acceptedLocationId:number|null;quarantineLocationId:number|null;rejectLocationId:number|null;qualityLocation?:QualityDecisionDestination|null;acceptedLocation?:QualityDecisionDestination|null;quarantineLocation?:QualityDecisionDestination|null;rejectLocation?:QualityDecisionDestination|null;isActive:boolean};
export type QualityParameter={id:number;branchCode:string;autoCreateInspectionOnReceipt:boolean;defaultInspectionMode:string;defaultFailAction:string;holdInventoryUntilDecision:boolean;blockPutawayUntilDecision:boolean;blockErpPostingUntilDecision:boolean;requireManagerApprovalForRelease:boolean;allowPartialDecision:boolean;allowDirectReceiptWhenNoRule:boolean;blockReceiptWhenLotMissing:boolean;blockReceiptWhenSerialMissing:boolean;blockReceiptWhenExpiryMissing:boolean;defaultQualityLocationId:number|null;defaultAcceptedLocationId:number|null;defaultQuarantineLocationId:number|null;defaultRejectLocationId:number|null;quarantineDestinations:QualityQuarantineDestination[];warehouseRoutes:QualityWarehouseRoute[];updatedBy?:number|null;updatedDate?:string|null};
export type QualityRule={id:number;branchCode:string;scopeType:string;stockId:number|null;stockCode?:string|null;stockName?:string|null;stockGroupCode?:string|null;inspectionMode:string;samplingMode:string;samplingValue:number;failAction:string;autoQuarantine:boolean;requireLot:boolean;requireSerial:boolean;requireExpiryDate:boolean;minimumRemainingShelfLifeDays:number|null;isActive:boolean;description?:string|null;createdBy?:number|null;createdDate?:string|null;updatedBy?:number|null;updatedDate?:string|null};
export type QualityRulePayload={branchCode:string;scopeType:string;stockId:number|null;stockGroupCode:string|null;inspectionMode:string;samplingMode:string;samplingValue:number;failAction:string;autoQuarantine:boolean;requireLot:boolean;requireSerial:boolean;requireExpiryDate:boolean;minimumRemainingShelfLifeDays:number|null;isActive:boolean;description:string|null};
export type QualityStockGroupOption={code:string;stockCount:number};
export type QualityDecisionCode={id:number;branchCode:string;code:string;name:string;applicableDecision?:string|null;description?:string|null;requiresNote:boolean;sortOrder:number;isActive:boolean;createdBy?:number|null;createdDate?:string|null;updatedBy?:number|null;updatedDate?:string|null;rowVersion:string};
export type QualityDecisionCodeOption={id:number;code:string;name:string;applicableDecision?:string|null;requiresNote:boolean};
export type QualityDecisionCodePayload={branchCode:string;code:string;name:string;applicableDecision:string|null;description:string|null;requiresNote:boolean;sortOrder:number;isActive:boolean;rowVersion?:string|null};
export type QualityRuleImportRow={rowNumber:number;status:'Created'|'Skipped'|'Failed';scopeType:string;scopeCode?:string|null;message:string};
export type QualityRuleImportResult={totalRows:number;createdCount:number;skippedCount:number;failedCount:number;rows:QualityRuleImportRow[]};
export type QualityInspection={id:number;branchCode:string;inspectionNo:string;sourceDocumentType:string;sourceDocumentNo:string;sourceWaybillNo?:string|null;projectCodes?:string|null;warehouseId:number;warehouseCode?:number|null;warehouseName?:string|null;createdByName?:string|null;isPriority:boolean;priorityRank?:number|null;status:string;lineCount:number;totalQuantity:number;requiredInspectionQuantity:number;inspectedQuantity:number;createdAtUtc:string;queuedAtUtc?:string|null;decidedAtUtc?:string|null;workState:string;recordedWorkSeconds:number;workSessionCount:number;participantCount:number;activeWorkerUserId?:number|null;activeWorkerName?:string|null;activeWorkStartedAtUtc?:string|null;workStartedByName?:string|null;workStoppedByName?:string|null;createdBy?:number|null;createdDate?:string|null;updatedBy?:number|null;updatedDate?:string|null};
export type QualityInspectionStatusOption={value:string;isDefault:boolean;isTerminal:boolean;canPrioritize:boolean};
export type QualityInspectionStatusCatalog={defaultValue:string;items:QualityInspectionStatusOption[]};
export type QualityInspectionLine={id:number;goodsReceiptLineId?:number|null;stockId:number;stockCode:string;stockName?:string|null;yapCode?:string|null;lotNo?:string|null;serialNo?:string|null;expiryDate?:string|null;quantity:number;sampleQuantity:number;inspectedQuantity:number;acceptedQuantity:number;rejectedQuantity:number;quarantineQuantity:number;quarantineLocationId?:number|null;decision:string;decisionCodeId?:number|null;reasonCode?:string|null;reasonNote?:string|null;decisionBy?:number|null;decisionAtUtc?:string|null;defaultAcceptedDestination?:QualityDecisionDestination|null;projectCodes?:string|null;orderNumbers?:string|null};
export type QualityInspectionImage={id:number;qualityInspectionId:number;qualityInspectionLineId:number;qualityInspectionDispositionId?:number|null;draftDispositionKey?:string|null;contentUrl:string;originalFileName:string;contentType:string;fileLength:number;caption?:string|null;uploadedBy?:number|null;uploadedAtUtc?:string|null};
export type QualityDecisionResult={goodsReceiptId:number;goodsReceiptDocumentNo:string;goodsReceiptWaybillNo?:string|null;goodsReceiptElectronicWaybillNo?:string|null;goodsReceiptStatus:string;qualityStatus:string;approvalStatus:string;erpIntegrationStatus:string;erpDocumentCreatedNow:boolean;message:string};
export type QualityInspectionQuantityDecision={lineId:number;acceptedQuantity:number;rejectedQuantity:number;quarantineQuantity:number;quarantineLocationId?:number|null};
export type QualityInspectionDispositionRequest={lineId:number;decision:string;quantity:number;targetLocationId?:number|null;decisionCodeId?:number|null;note?:string|null;draftDispositionKey:string};
export type QualityInspectionDisposition={id:number;lineId:number;idempotencyKey:string;sequenceNo:number;decision:string;quantity:number;sourceWarehouseId:number;sourceLocationId:number;targetWarehouseId:number;targetLocationId:number;sourceWarehouseCode:string;sourceLocationCode:string;targetWarehouseCode:string;targetLocationCode:string;sourceStockStatus:string;targetStockStatus:string;stockMovementOperationId?:number|null;warehouseTransferId?:number|null;decisionCodeId?:number|null;reasonCode?:string|null;reasonNote?:string|null;decisionBy:number;decisionAtUtc:string;draftDispositionKey?:string|null;images?:QualityInspectionImage[]};
export type QualityInspectionControlQuantityRequest={lineId:number;inspectedQuantity:number};
export type QualityInspectionControl={id:number;lineId:number;idempotencyKey:string;lotQuantity:number;requiredQuantity:number;inspectedQuantity:number;outcomeSummary:string;note?:string|null;inspectedBy:number;inspectedAtUtc:string};
export type QualityInspectionWorkStopReason='Break'|'MaterialWait'|'EquipmentIssue'|'DocumentationWait'|'SupervisorWait'|'ShiftEnd'|'Handover'|'Other'|'DecisionApplied'|'InspectionCancelled';
export type QualityInspectionWorkSession={id:number;sequenceNo:number;workerUserId:number;workerName:string;startedAtUtc:string;endedAtUtc?:string|null;durationSeconds:number;stopReason?:QualityInspectionWorkStopReason|null;stopNote?:string|null;endedByUserId?:number|null};
export type QualityInspectionWorkSummary={state:'NotStarted'|'Running'|'Paused'|'Completed';serverNowUtc:string;totalWorkedSeconds:number;currentUserWorkedSeconds:number;sessionCount:number;participantCount:number;activeWorkerUserId?:number|null;activeWorkerName?:string|null;activeStartedAtUtc?:string|null;canStart:boolean;canPause:boolean;canApplyDecision:boolean};
export type QualityInspectionDetail={header:QualityInspection;lines:QualityInspectionLine[];note?:string|null;rowVersion:string;allowPartialDecision:boolean;requireManagerApprovalForRelease:boolean;sourceOperationStatus?:string|null;canDecideInventoryDisposition:boolean;quarantineDestinations:QualityQuarantineDestination[];defaultAcceptedDestination?:QualityDecisionDestination|null;defaultRejectedDestination?:QualityDecisionDestination|null;warehouseTransferDocumentSeries:QualityDatDocumentSeries[];dispositions:QualityInspectionDisposition[];controls:QualityInspectionControl[];work:QualityInspectionWorkSummary;workSessions:QualityInspectionWorkSession[]};
export type QualityInspectionReportRow={id:number;inspectionNo:string;sourceDocumentNo:string;waybillNo?:string|null;supplierCode?:string|null;supplierName?:string|null;warehouseCode?:number|null;warehouseName?:string|null;status:string;lineCount:number;totalQuantity:number;requiredInspectionQuantity:number;inspectedQuantity:number;acceptedQuantity:number;rejectedQuantity:number;quarantineQuantity:number;controlCount:number;imageCount:number;createdAtUtc:string;startedAtUtc?:string|null;decidedAtUtc?:string|null;activeWorkSeconds:number;elapsedSeconds:number;pauseSeconds:number;pauseCount:number;breakCount:number;participantCount:number;participants?:string|null;inspectionCoveragePercent:number};
export type QualityStockReportRow={id:number;stockId:number;stockCode:string;stockName?:string|null;inspectionCount:number;receiptCount:number;totalQuantity:number;requiredInspectionQuantity:number;inspectedQuantity:number;acceptedQuantity:number;rejectedQuantity:number;quarantineQuantity:number;firstInspectionAtUtc:string;lastInspectionAtUtc:string;activeWorkSeconds:number;averageWorkSeconds:number;participantCount:number;inspectionCoveragePercent:number};
export type QualityReportWorker={userId:number;userName:string;activeWorkSeconds:number;sessionCount:number;firstStartedAtUtc:string;lastEndedAtUtc?:string|null};
export type QualityReportPause={sequenceNo:number;workerUserId:number;workerName:string;reason:QualityInspectionWorkStopReason;note?:string|null;startedAtUtc:string;endedAtUtc:string;workSecondsBeforeStop:number;pauseSecondsUntilNextSession?:number|null};
export type QualityInspectionReportLine={id:number;stockId:number;stockCode:string;stockName?:string|null;yapCode?:string|null;lotNo?:string|null;serialNo?:string|null;totalQuantity:number;requiredInspectionQuantity:number;inspectedQuantity:number;acceptedQuantity:number;rejectedQuantity:number;quarantineQuantity:number;decision:string;controlCount:number;imageCount:number;decisionCode?:string|null;decisionNote?:string|null;decisionAtUtc?:string|null};
export type QualityInspectionReportDetail={header:QualityInspectionReportRow;lines:QualityInspectionReportLine[];workers:QualityReportWorker[];pauses:QualityReportPause[]};
export const qualityApi={
 getParameters:async(branchCode:string)=>unwrap(await api.get<Envelope<QualityParameter>>(`/api/quality/parameters?branchCode=${encodeURIComponent(branchCode)}`)),
 updateParameters:async(x:Omit<QualityParameter,'id'>)=>unwrap(await api.put<Envelope<QualityParameter>>('/api/quality/parameters',x)),
 rulesPaged:async(p:GridRequest):Promise<GridPage<QualityRule>>=>unwrap(await api.post<Envelope<GridPage<QualityRule>>>('/api/quality/rules/paged',p)),
 decisionCodesPaged:async(p:GridRequest):Promise<GridPage<QualityDecisionCode>>=>unwrap(await api.post<Envelope<GridPage<QualityDecisionCode>>>('/api/quality/decision-codes/paged',p)),
 createDecisionCode:async(x:QualityDecisionCodePayload)=>unwrap(await api.post<Envelope<{id:number}>>('/api/quality/decision-codes',x)),
 updateDecisionCode:async(id:number,x:QualityDecisionCodePayload)=>unwrap(await api.put<Envelope<boolean>>(`/api/quality/decision-codes/${id}`,x)),
 deleteDecisionCode:async(id:number)=>unwrap(await api.post<Envelope<boolean>>(`/api/quality/decision-codes/${id}/delete`,{})),
 decisionCodeOptions:async(request:DropdownPageRequest,branchCode:string,decision:string)=>unwrap(await api.post<Envelope<{items:QualityDecisionCodeOption[];pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>(`/api/quality/decision-codes/options/paged?branchCode=${encodeURIComponent(branchCode)}&decision=${encodeURIComponent(decision)}`,buildDropdownPagedBody(request,{sortBy:'code'}),{signal:request.signal})),
 createRule:async(x:QualityRulePayload)=>unwrap(await api.post<Envelope<{id:number}>>('/api/quality/rules',x)),
 updateRule:async(id:number,x:QualityRulePayload)=>unwrap(await api.put<Envelope<boolean>>(`/api/quality/rules/${id}`,x)),
 deleteRule:async(id:number)=>unwrap(await api.post<Envelope<boolean>>(`/api/quality/rules/${id}/delete`,{})),
 stockGroups:async(request:DropdownPageRequest,branchCode:string)=>unwrap(await api.post<Envelope<{items:QualityStockGroupOption[];pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>(`/api/quality/rules/stock-groups/paged?branchCode=${encodeURIComponent(branchCode)}`,buildDropdownPagedBody(request,{sortBy:'code'}),{signal:request.signal})),
 downloadRuleImportTemplate:async(branchCode:string):Promise<Blob>=>await api.get<Blob>(`/api/quality/rules/import-template?branchCode=${encodeURIComponent(branchCode)}`,{responseType:'blob'}),
 importRules:async(file:File,branchCode:string):Promise<QualityRuleImportResult>=>{const form=new FormData();form.append('file',file);return unwrap(await api.post<Envelope<QualityRuleImportResult>>(`/api/quality/rules/import?branchCode=${encodeURIComponent(branchCode)}`,form));},
 inspectionStatusOptions:async():Promise<QualityInspectionStatusCatalog>=>unwrap(await api.get<Envelope<QualityInspectionStatusCatalog>>('/api/quality/inspections/status-options')),
 inspectionsPaged:async(p:GridRequest):Promise<GridPage<QualityInspection>>=>unwrap(await api.post<Envelope<GridPage<QualityInspection>>>('/api/quality/inspections/paged',p)),
 inspectionReportsPaged:async(p:GridRequest):Promise<GridPage<QualityInspectionReportRow>>=>unwrap(await api.post<Envelope<GridPage<QualityInspectionReportRow>>>('/api/quality/reports/inspections/paged',p)),
 inspectionReportDetail:async(id:number):Promise<QualityInspectionReportDetail>=>unwrap(await api.get<Envelope<QualityInspectionReportDetail>>(`/api/quality/reports/inspections/${id}`)),
 stockReportsPaged:async(p:GridRequest):Promise<GridPage<QualityStockReportRow>>=>unwrap(await api.post<Envelope<GridPage<QualityStockReportRow>>>('/api/quality/reports/stocks/paged',p)),
 inspection:async(id:number):Promise<QualityInspectionDetail>=>unwrap(await api.get<Envelope<QualityInspectionDetail>>(`/api/quality/inspections/${id}`)),
 inspectionImages:async(inspectionId:number,lineId:number,draftDispositionKey?:string):Promise<QualityInspectionImage[]>=>{const query=draftDispositionKey?`?draftDispositionKey=${encodeURIComponent(draftDispositionKey)}`:'';return unwrap(await api.get<Envelope<QualityInspectionImage[]>>(`/api/quality/inspections/${inspectionId}/lines/${lineId}/images${query}`));},
 inspectionImageContent:async(contentUrl:string):Promise<Blob>=>await api.get<Blob>(contentUrl,{responseType:'blob'}),
 uploadInspectionImages:async(inspectionId:number,lineId:number,files:File[],draftDispositionKey:string):Promise<QualityInspectionImage[]>=>{const form=new FormData();files.forEach(file=>form.append('files',file));form.append('draftDispositionKey',draftDispositionKey);return unwrap(await api.post<Envelope<QualityInspectionImage[]>>(`/api/quality/inspections/${inspectionId}/lines/${lineId}/images`,form));},
 deleteInspectionImage:async(inspectionId:number,lineId:number,imageId:number):Promise<void>=>{unwrap(await api.post<Envelope<object>>(`/api/quality/inspections/${inspectionId}/lines/${lineId}/images/${imageId}/delete`,{}));},
 startInspectionWork:async(id:number,x:{idempotencyKey:string;rowVersion:string})=>unwrap(await api.post<Envelope<QualityInspectionWorkSummary>>(`/api/quality/inspections/${id}/work/start`,x)),
 pauseInspectionWork:async(id:number,x:{idempotencyKey:string;reason:QualityInspectionWorkStopReason;note?:string|null;rowVersion:string;controlQuantities?:QualityInspectionControlQuantityRequest[]})=>unwrap(await api.post<Envelope<QualityInspectionWorkSummary>>(`/api/quality/inspections/${id}/work/pause`,x)),
 togglePriority:async(id:number):Promise<{inspectionId:number;isPriority:boolean}>=>unwrap(await api.post<Envelope<{inspectionId:number;isPriority:boolean}>>(`/api/quality/inspections/${id}/priority/toggle`,{})),
 reorderPriority:async(inspectionId:number,targetRank:number):Promise<{inspectionId:number;targetRank:number}>=>unwrap(await api.post<Envelope<{inspectionId:number;targetRank:number}>>('/api/quality/inspections/priority/reorder',{inspectionId,targetRank})),
 decide:async(id:number,x:{idempotencyKey:string;decision:string;note?:string;decisionCodeId?:number|null;lineIds?:number[];rowVersion:string;quantityDecisions?:QualityInspectionQuantityDecision[];quarantineLocationId?:number|null;dispositions?:QualityInspectionDispositionRequest[];warehouseTransferDocumentSeriesId?:number|null;controlQuantities:QualityInspectionControlQuantityRequest[]})=>unwrap(await api.post<Envelope<QualityDecisionResult>>(`/api/quality/inspections/${id}/decision`,x)),
 stocks:async(request:DropdownPageRequest,branchCode:string)=>unwrap(await api.post<Envelope<{items:Array<{id:number;erpStockCode:string;stockName:string}>;pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>('/api/erp-mirror/stocks/paged',buildDropdownPagedBody(request,{sortBy:'erpStockCode',filters:[{column:'branchCode',operator:'equals',value:branchCode}]}),{signal:request.signal})),
 locations:async(request:DropdownPageRequest,branchCode:string,warehouseId?:number|null)=>unwrap(await api.post<Envelope<{items:Array<{id:number;warehouseId:number;warehouseCode:number;warehouseName:string;code:string;name:string;locationType:string;isPickable:boolean;isPutaway:boolean;isQuarantine:boolean;isActive:boolean}>;pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>('/api/locations/paged',buildDropdownPagedBody(request,{sortBy:'code',filters:[{column:'branchCode',operator:'equals',value:branchCode},{column:'isActive',operator:'equals',value:'true'},...(warehouseId?[{column:'warehouseId',operator:'equals',value:String(warehouseId)}]:[])]}),{signal:request.signal})),
 warehouses:async(request:DropdownPageRequest,branchCode:string)=>unwrap(await api.post<Envelope<{items:Array<{id:number;warehouseCode:number;warehouseName:string;branchCode:string}>;pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasNextPage:boolean}>>('/api/erp-mirror/warehouses/paged',buildDropdownPagedBody(request,{sortBy:'warehouseCode',filters:[{column:'branchCode',operator:'equals',value:branchCode}]}),{signal:request.signal})),
};
