import { useCallback, useMemo, useState, type ReactElement } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { code128 } from 'bwip-js/browser';
import { Ban, Eye, Loader2, Printer, X } from 'lucide-react';
import { toast } from 'sonner';
import { AdvancedDataGrid, type GridColumn } from '@/components/shared/AdvancedDataGrid';
import { ResponsiveDialog } from '@/components/shared/ResponsiveDialog';
import { requiredActionColumn, systemColumns } from '@/components/shared/GridSystemColumns';
import { formatProjectDateTime, formatProjectNumber } from '@/lib/project-format';
import { warehouseInboundV2Api } from '../api/warehouse-inbound.api';
import type { WarehouseInboundLabelBatchDetail, WarehouseInboundLabelBatchRow, WarehouseInboundLabelRow } from '../types/warehouse-inbound.types';

export function WarehouseInboundLabelsPage():ReactElement {
  const cache=useQueryClient(); const [detail,setDetail]=useState<WarehouseInboundLabelBatchDetail|null>(null); const [busy,setBusy]=useState<number|null>(null);
  const open=useCallback(async(id:number)=>{setBusy(id);try{setDetail(await warehouseInboundV2Api.labelBatch(id))}catch(error){toast.error(message(error,'Etiket paketi açılamadı.'))}finally{setBusy(null)}},[]);
  const columns=useMemo<GridColumn<WarehouseInboundLabelBatchRow>[]>(()=>[
    ...systemColumns<WarehouseInboundLabelBatchRow>(),
    {key:'batchNo',label:'Paket No',sortable:true,filterable:true,render:r=><span className="font-mono font-semibold">{r.batchNo}</span>},
    {key:'documentNo',label:'Mal Kabul No',sortable:true,filterable:true,render:r=>r.documentNo},
    {key:'taskNo',label:'Emir No',sortable:true,filterable:true,render:r=>r.taskNo||'—'},
    {key:'status',label:'Durum',sortable:true,filterable:true,render:r=>r.status},
    {key:'totalLabelCount',label:'Toplam',sortable:true,filterable:true,render:r=>r.totalLabelCount},
    {key:'printedLabelCount',label:'Basılı',sortable:true,filterable:true,render:r=>r.printedLabelCount},
    {key:'consumedLabelCount',label:'Kullanılan',sortable:true,filterable:true,render:r=>r.consumedLabelCount},
    {key:'lastPrintedAtUtc',label:'Son Baskı',sortable:true,filterable:true,render:r=>r.lastPrintedAtUtc?formatProjectDateTime(r.lastPrintedAtUtc):'—'},
    {key:'actions',label:'İşlemler',...requiredActionColumn,render:r=><button type="button" onClick={()=>void open(r.id)} className="rounded-lg p-2 text-cyan-500" aria-label="Etiket paketini aç">{busy===r.id?<Loader2 className="size-4 animate-spin"/>:<Eye className="size-4"/>}</button>},
  ],[busy,open]);
  const reload=async()=>{if(detail)setDetail(await warehouseInboundV2Api.labelBatch(detail.batch.id));await cache.invalidateQueries({queryKey:['advanced-grid','warehouse-inbound-labels']})};
  return <><AdvancedDataGrid pageKey="warehouse-inbound-labels" title="Mal Kabul Ön Etiketleri" description="Emirden üretilen etiketleri izleyin, yazdırın ve kullanım yaşam döngüsünü yönetin." columns={columns} fetchPage={warehouseInboundV2Api.labelBatchesPaged}/>{detail&&<LabelDialog detail={detail} close={()=>setDetail(null)} reload={()=>void reload()}/>}</>;
}

function LabelDialog({detail,close,reload}:{detail:WarehouseInboundLabelBatchDetail;close:()=>void;reload:()=>void}):ReactElement {
  const [selected,setSelected]=useState<number[]>(detail.labels.filter(x=>!['Consumed','Void'].includes(x.status)).map(x=>x.id)); const [busy,setBusy]=useState(false);
  const printable=detail.labels.filter(x=>selected.includes(x.id)&&!['Consumed','Void'].includes(x.status));
  const print=async()=>{if(printable.length===0){toast.error('Yazdırılabilir etiket seçin.');return}const win=window.open('','_blank');if(!win){toast.error('Yazdırma penceresine tarayıcı izin vermedi.');return}setBusy(true);try{const cards=printable.map(label=>labelHtml(label)).join('');win.document.write(`<html><head><title>${escapeHtml(detail.batch.batchNo)}</title><style>@page{size:100mm 70mm;margin:0}*{box-sizing:border-box}body{margin:0;font:12px Arial;color:#111}.label{width:100mm;height:70mm;padding:5mm;page-break-after:always;border:1px solid #ddd}.title{font-size:16px;font-weight:700}.row{display:flex;justify-content:space-between;margin-top:2mm}.barcode{width:90mm;height:24mm;object-fit:contain;margin-top:3mm}.code{font:11px monospace;text-align:center;word-break:break-all}</style></head><body>${cards}<script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script></body></html>`);win.document.close();await warehouseInboundV2Api.markLabelsPrinted(printable.map(x=>x.id));toast.success(`${printable.length} etiket yazdırma kuyruğuna alındı.`);reload()}catch(error){win.close();toast.error(message(error,'Etiketler yazdırılamadı.'))}finally{setBusy(false)}};
  const voidLabel=async(label:WarehouseInboundLabelRow)=>{const reason=window.prompt('Etiket iptal nedenini yazın:');if(!reason?.trim())return;setBusy(true);try{await warehouseInboundV2Api.voidLabel(label.id,reason.trim(),label.rowVersion);toast.success('Etiket iptal edildi.');reload()}catch(error){toast.error(message(error,'Etiket iptal edilemedi.'))}finally{setBusy(false)}};
  const toggle=(id:number)=>setSelected(value=>value.includes(id)?value.filter(x=>x!==id):[...value,id]);
  return <ResponsiveDialog onClose={close} title={`Ön etiket paketi ${detail.batch.batchNo}`} description="Üretilen etiketleri seçin, yazdırın veya iptal edin." className="!max-w-6xl"><header className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-cyan-500">Ön Etiket Paketi</p><h2 className="text-xl font-bold">{detail.batch.batchNo}</h2><p className="text-sm text-slate-500">{detail.batch.documentNo} · {detail.batch.taskNo}</p></div><button onClick={close} aria-label="Pencereyi kapat" className="grid size-11 shrink-0 place-items-center rounded-xl hover:bg-black/5 dark:hover:bg-white/10"><X className="size-5"/></button></header><div className="mt-4 flex flex-col gap-3 rounded-xl border border-[var(--wms-app-border)] p-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm"><strong>{selected.length}</strong> etiket seçili · Yazdırılan {detail.batch.printedLabelCount}/{detail.batch.totalLabelCount} · Kullanılan {detail.batch.consumedLabelCount}</p><button type="button" disabled={busy||printable.length===0} onClick={()=>void print()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 py-2 font-semibold text-white disabled:opacity-40">{busy?<Loader2 className="size-4 animate-spin"/>:<Printer className="size-4"/>}Seçilenleri Yazdır</button></div><div className="mt-4 overflow-x-auto rounded-xl border border-[var(--wms-app-border)]"><table className="min-w-[760px] w-full text-sm"><thead><tr><th className="p-3"></th><th className="p-3 text-left">Stok</th><th className="p-3 text-left">Seri / Lot</th><th className="p-3 text-right">Miktar</th><th className="p-3 text-left">Barkod</th><th className="p-3">Durum</th><th className="p-3">İşlemler</th></tr></thead><tbody>{detail.labels.map(label=><tr key={label.id} className="border-t border-[var(--wms-app-border)]"><td className="p-3"><input type="checkbox" disabled={['Consumed','Void'].includes(label.status)} checked={selected.includes(label.id)} onChange={()=>toggle(label.id)}/></td><td className="p-3"><strong>{label.stockCode}</strong><div className="text-xs text-slate-500">{label.stockName} {label.yapCode&&`· ${label.yapCode}`}</div></td><td className="p-3">{label.serialNo||'—'} / {label.lotNo||'—'}</td><td className="p-3 text-right">{formatProjectNumber(label.quantity)} {label.unitCode}</td><td className="max-w-72 break-all p-3 font-mono text-xs">{label.barcodeValue}</td><td className="p-3 text-center">{label.status}</td><td className="p-3 text-center"><button type="button" disabled={busy||['Consumed','Void'].includes(label.status)} onClick={()=>void voidLabel(label)} className="grid size-11 place-items-center rounded-lg text-red-500" title="Etiketi iptal et"><Ban className="size-4"/></button></td></tr>)}</tbody></table></div></ResponsiveDialog>;
}

function labelHtml(label:WarehouseInboundLabelRow):string {const canvas=document.createElement('canvas');code128(canvas,{bcid:'code128',text:label.barcodeValue,scale:3,height:14,includetext:false});return `<section class="label"><div class="title">${escapeHtml(label.stockCode)} · ${escapeHtml(label.stockName||'')}</div><div class="row"><span>Yapı: ${escapeHtml(label.yapCode||'—')}</span><strong>${escapeHtml(String(label.quantity))} ${escapeHtml(label.unitCode)}</strong></div><div class="row"><span>Lot: ${escapeHtml(label.lotNo||'—')}</span><span>Seri: ${escapeHtml(label.serialNo||'—')}</span></div><img class="barcode" src="${canvas.toDataURL('image/png')}"/><div class="code">${escapeHtml(label.barcodeValue)}</div></section>`}
function escapeHtml(value:string):string{return value.replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]!))}
function message(error:unknown,fallback:string):string{return error instanceof Error?error.message:fallback}
