import { useCallback,useEffect,useMemo,useState,type ReactElement,type ReactNode } from 'react';
import { ArrowRight,CheckCircle2,ClipboardList,FileCheck2,FileSearch,Plus,RefreshCw,ShoppingCart,Trash2,X } from 'lucide-react';
import { toast } from 'sonner';
import { AdvancedDataGrid,type GridColumn,type GridRequest } from '@/components/shared/AdvancedDataGrid';
import { AppDateInput,AppInput } from '@/components/shared/AppInput';
import { PagedAppDropdown } from '@/components/shared/PagedAppDropdown';
import { ResponsiveDialog } from '@/components/shared/ResponsiveDialog';
import { warehouseTransferApi } from '@/features/warehouse-transfer-v2/api/warehouse-transfer.api';
import { goodsReceiptV2Api } from '@/features/goods-receipt-v2/api/goods-receipt.api';
import type { CustomerOption,StockOption } from '@/features/goods-receipt-v2/types/goods-receipt.types';
import { usePermissionAccess } from '@/features/access-control/hooks/usePermissionAccess';
import { useAuthStore } from '@/stores/auth-store';
import { formatProjectDate,formatProjectDateTime,formatProjectNumber } from '@/lib/project-format';
import { procurementApi } from './api';
import type { ProcurementDocumentDetail,ProcurementDocumentType,ProcurementGridRow,ProcurementRequestLineInput,ProcurementSummary,SupplierQuoteLineInput } from './types';

const today=()=>new Date().toLocaleDateString('en-CA');
const tabs:Array<{key:ProcurementDocumentType;label:string;icon:typeof ClipboardList}>=[{key:'request',label:'Satınalma Talepleri',icon:ClipboardList},{key:'rfq',label:'Teklif Talepleri',icon:FileSearch},{key:'quote',label:'Tedarikçi Teklifleri',icon:FileCheck2},{key:'order',label:'Satınalma Siparişleri',icon:ShoppingCart}];
const statusLabel:Record<string,string>={Draft:'Taslak',PendingApproval:'Onay Bekliyor',Approved:'Onaylandı',Rejected:'Reddedildi',Converted:'Dönüştürüldü',Cancelled:'İptal',Sent:'Gönderildi',Quoted:'Teklif Geldi',Closed:'Kapandı',Submitted:'Sunuldu',SentToSupplier:'Tedarikçiye Gönderildi',PartiallyReceived:'Kısmi Kabul',Received:'Tamamlandı'};
const blankLine=():ProcurementRequestLineInput&{key:string;stockValue:string|null}=>({key:crypto.randomUUID(),stockValue:null,stockName:'',unitCode:'ADET',quantity:1});
const workflow:Array<{key:ProcurementDocumentType;label:string;hint:string}>=[
  {key:'request',label:'1. İhtiyaç talebi',hint:'Ne ve ne zaman gerekli?'},
  {key:'rfq',label:'2. Teklif toplama',hint:'Kimlerden fiyat istenecek?'},
  {key:'quote',label:'3. Teklif kararı',hint:'Fiyat ve termin karşılaştırması'},
  {key:'order',label:'4. Sipariş',hint:'Onay ve tedarikçiye gönderim'},
];

export function ProcurementPage():ReactElement{
  const branch=useAuthStore(x=>x.branch?.code??'0');
  const {can}=usePermissionAccess();
  const [type,setType]=useState<ProcurementDocumentType>('request');
  const [summary,setSummary]=useState<ProcurementSummary>();
  const [revision,setRevision]=useState(0);
  const [detail,setDetail]=useState<ProcurementDocumentDetail>();
  const [creating,setCreating]=useState(false);
  const [rfqSource,setRfqSource]=useState<ProcurementDocumentDetail>();
  const [quoteSource,setQuoteSource]=useState<ProcurementDocumentDetail>();
  const loadSummary=useCallback(()=>procurementApi.summary().then(setSummary).catch(e=>toast.error(e instanceof Error?e.message:'Özet alınamadı.')),[]);
  useEffect(()=>{void loadSummary();},[loadSummary,revision]);
  const fetchPage=useCallback((request:GridRequest)=>procurementApi.paged(type,request),[type]);
  const columns=useMemo<GridColumn<ProcurementGridRow>[]>(()=>[
    {key:'documentNo',label:'Belge No',sortable:true,render:x=><button className="font-semibold text-cyan-500 hover:underline" onClick={()=>void procurementApi.detail(type,x.id).then(setDetail).catch(e=>toast.error(e.message))}>{x.documentNo}</button>},
    {key:'documentDate',label:'Tarih',sortable:true,render:x=>formatProjectDate(x.documentDate)},
    {key:'status',label:'Durum',sortable:true,render:x=><span className="rounded-full border border-cyan-500/25 px-2 py-1 text-xs text-cyan-400">{statusLabel[x.status]??x.status}</span>},
    {key:'subject',label:'Konu',sortable:true,render:x=>x.subject},
    {key:'counterparty',label:'Tedarikçi',render:x=>x.counterparty||'—'},
    {key:'lineCount',label:'Satır',sortable:true,render:x=>formatProjectNumber(x.lineCount)},
    {key:'totalAmount',label:'Toplam',render:x=>x.totalAmount?`${formatProjectNumber(x.totalAmount)} ${x.currencyCode}`:'—'},
    {key:'dueDate',label:'Termin',render:x=>x.dueDate?formatProjectDate(x.dueDate):'—'},
  ],[type]);
  return <section className="space-y-5">
    <header className="rounded-2xl border border-cyan-500/20 bg-[var(--wms-app-panel)] p-6">
      <p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-500">PROCURE_TO_PAY / SATINALMA</p>
      <div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Satınalma Çalışma Alanı</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Bir ihtiyacı talep olarak başlatın; teklifleri aynı akışta toplayın, karşılaştırın ve onaylı siparişe dönüştürün.</p></div>{can('WMS.PROCUREMENT.REQUEST.MANAGE')?<button className="btn btn-primary" onClick={()=>setCreating(true)}><Plus size={16}/> Yeni ihtiyaç talebi</button>:null}</div>
    </header>
    <div className="grid gap-2 md:grid-cols-4">{workflow.map((step,index)=><button key={step.key} onClick={()=>setType(step.key)} className={`rounded-xl border p-4 text-left transition ${type===step.key?'border-cyan-400 bg-cyan-500/10':'border-cyan-500/15 bg-[var(--wms-app-panel)] hover:border-cyan-500/35'}`}><div className="flex items-center justify-between"><span className={`text-sm font-semibold ${type===step.key?'text-cyan-400':''}`}>{step.label}</span>{index<workflow.length-1?<ArrowRight size={15} className="text-slate-600"/>:<CheckCircle2 size={16} className="text-emerald-500"/>}</div><p className="mt-1 text-xs text-slate-500">{step.hint}</p></button>)}</div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[
      ['Taslak talep',summary?.draftRequests??0],['Onay bekleyen',summary?.pendingRequests??0],['Açık RFQ',summary?.openRfqs??0],['Gelen teklif',summary?.submittedQuotes??0],['Sipariş onayı',summary?.pendingOrders??0],['Mal kabule açık',summary?.approvedOpenOrders??0],
    ].map(([label,value])=><div key={String(label)} className="rounded-xl border border-cyan-500/15 bg-[var(--wms-app-panel)] p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-cyan-400">{value}</p></div>)}</div>
    <div className="flex flex-wrap items-center gap-2"><div><h2 className="font-semibold">{tabs.find(x=>x.key===type)?.label}</h2><p className="text-xs text-slate-500">{type==='request'?'Yeni ihtiyaçları ve onay durumlarını yönetin.':type==='rfq'?'Onaylanan talepler için tedarikçilerden fiyat toplayın.':type==='quote'?'Gelen fiyat ve terminleri inceleyip karar verin.':'Onaylanan siparişleri tedarikçiye gönderin ve mal kabul kaynağına dönüştürün.'}</p></div><button className="btn btn-secondary ml-auto" onClick={()=>setRevision(x=>x+1)}><RefreshCw size={16}/> Yenile</button></div>
    <AdvancedDataGrid key={type} refreshKey={revision} pageKey={`procurement-${type}`} title={tabs.find(x=>x.key===type)?.label??'Satınalma'} description="Belgeye tıklayarak satırları ve karar geçmişini inceleyin." columns={columns} fetchPage={fetchPage}/>
    {creating?<CreateRequestDialog branch={branch} onClose={()=>setCreating(false)} onSaved={()=>{setCreating(false);setRevision(x=>x+1);toast.success('Satınalma talebi oluşturuldu.');}}/>:null}
    {detail?<DetailDialog detail={detail} can={can} onClose={()=>setDetail(undefined)} onCreateRfq={()=>{setRfqSource(detail);setDetail(undefined);}} onCreateQuote={()=>{setQuoteSource(detail);setDetail(undefined);}} onChanged={async()=>{setDetail(await procurementApi.detail(detail.documentType,detail.id));setRevision(x=>x+1);}} onConverted={target=>{setDetail(undefined);setType(target);setRevision(x=>x+1);}}/>:null}
    {rfqSource?<CreateRfqDialog source={rfqSource} branch={branch} onClose={()=>setRfqSource(undefined)} onSaved={()=>{setRfqSource(undefined);setType('rfq');setRevision(x=>x+1);toast.success('Teklif talebi oluşturuldu; göndermeden önce kontrol edebilirsiniz.');}}/>:null}
    {quoteSource?<CreateQuoteDialog source={quoteSource} onClose={()=>setQuoteSource(undefined)} onSaved={()=>{setQuoteSource(undefined);setType('quote');setRevision(x=>x+1);toast.success('Tedarikçi teklifi kaydedildi.');}}/>:null}
  </section>;
}

function CreateRequestDialog({branch,onClose,onSaved}:{branch:string;onClose:()=>void;onSaved:()=>void}):ReactElement{
  const [subject,setSubject]=useState('');const [requestDate,setRequestDate]=useState(today);const [requiredDate,setRequiredDate]=useState('');const [departmentCode,setDepartmentCode]=useState('');const [projectCode,setProjectCode]=useState('');const [description,setDescription]=useState('');const [lines,setLines]=useState([blankLine()]);const [busy,setBusy]=useState(false);
  const patch=(key:string,next:Partial<(typeof lines)[number]>)=>setLines(xs=>xs.map(x=>x.key===key?{...x,...next}:x));
  const save=async()=>{if(!subject.trim()||lines.some(x=>!x.stockName.trim()||x.quantity<=0)){toast.error('Konu ve geçerli stok satırları zorunludur.');return;}setBusy(true);try{await procurementApi.createRequest({requestDate,requiredDate:requiredDate||undefined,departmentCode:departmentCode||undefined,projectCode:projectCode||undefined,subject,description:description||undefined,lines:lines.map(x=>({stockId:x.stockId,stockCode:x.stockCode,stockName:x.stockName,unitCode:x.unitCode,quantity:x.quantity,requiredDate:x.requiredDate,projectCode:x.projectCode,description:x.description}))});onSaved();}catch(e){toast.error(e instanceof Error?e.message:'Talep oluşturulamadı.');}finally{setBusy(false);}};
  return <ResponsiveDialog open onClose={onClose} title="Yeni satınalma talebi" description="İhtiyacı tanımlayın; tedarikçi ve fiyat süreci onaydan sonra RFQ aşamasında yürütülür." className="!max-w-6xl"><div className="space-y-5">
    <div className="grid gap-4 md:grid-cols-2"><Field label="Talep konusu"><AppInput value={subject} onChange={e=>setSubject(e.target.value)} maxLength={250}/></Field><Field label="Departman"><AppInput value={departmentCode} onChange={e=>setDepartmentCode(e.target.value)}/></Field><Field label="Talep tarihi"><AppDateInput value={requestDate} onChange={e=>setRequestDate(e.target.value)}/></Field><Field label="İstenen tarih"><AppDateInput value={requiredDate} onChange={e=>setRequiredDate(e.target.value)}/></Field><Field label="Proje kodu"><AppInput value={projectCode} onChange={e=>setProjectCode(e.target.value)}/></Field><Field label="Açıklama"><AppInput value={description} onChange={e=>setDescription(e.target.value)}/></Field></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Talep satırları</h3><button className="btn btn-secondary" onClick={()=>setLines(x=>[...x,blankLine()])}><Plus size={15}/> Satır ekle</button></div>{lines.map((line,index)=><div key={line.key} className="grid gap-3 rounded-xl border border-cyan-500/15 p-4 md:grid-cols-[minmax(260px,2fr)_100px_120px_140px_42px]"><Field label={`Stok ${index+1}`}><PagedAppDropdown<StockOption> queryKey={['procurement-stock',branch]} fetchPage={r=>warehouseTransferApi.stocks(r,branch)} toOption={x=>({value:encodeURIComponent(JSON.stringify(x)),label:`${x.erpStockCode} · ${x.stockName}`,description:x.unitCode})} value={line.stockValue} onValueChange={value=>{const x=value?JSON.parse(decodeURIComponent(value)) as StockOption:null;patch(line.key,{stockValue:value,stockId:x?.id,stockCode:x?.erpStockCode,stockName:x?.stockName??'',unitCode:x?.unitCode??'ADET'});}} searchable minSearchLength={2}/></Field><Field label="Miktar"><AppInput type="number" min="0.000001" step="any" value={line.quantity} onChange={e=>patch(line.key,{quantity:Number(e.target.value)})}/></Field><Field label="Birim"><AppInput value={line.unitCode} onChange={e=>patch(line.key,{unitCode:e.target.value})}/></Field><Field label="Termin"><AppDateInput value={line.requiredDate??''} onChange={e=>patch(line.key,{requiredDate:e.target.value})}/></Field><button className="mt-6 text-rose-400" disabled={lines.length===1} onClick={()=>setLines(x=>x.filter(y=>y.key!==line.key))}><Trash2 size={18}/></button></div>)}</div>
    <div className="flex justify-end gap-2"><button className="btn btn-secondary" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" disabled={busy} onClick={()=>void save()}>{busy?'Kaydediliyor…':'Talebi oluştur'}</button></div>
  </div></ResponsiveDialog>;
}

function CreateRfqDialog({source,branch,onClose,onSaved}:{source:ProcurementDocumentDetail;branch:string;onClose:()=>void;onSaved:()=>void}):ReactElement{
  const [dueDate,setDueDate]=useState(source.dueDate??'');
  const [message,setMessage]=useState('');
  const [suppliers,setSuppliers]=useState<CustomerOption[]>([]);
  const [supplierValue,setSupplierValue]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);
  const addSupplier=(value:string|null)=>{setSupplierValue(null);if(!value)return;const item=JSON.parse(decodeURIComponent(value)) as CustomerOption;setSuppliers(xs=>xs.some(x=>x.id===item.id)?xs:[...xs,item]);};
  const save=async()=>{if(!dueDate||suppliers.length===0){toast.error('Teklif son tarihi ve en az bir tedarikçi zorunludur.');return;}setBusy(true);try{await procurementApi.convertRequestToRfq(source.id,{responseDueDate:dueDate,supplierIds:suppliers.map(x=>x.id),buyerMessage:message||undefined});onSaved();}catch(e){toast.error(e instanceof Error?e.message:'Teklif talebi oluşturulamadı.');}finally{setBusy(false);}};
  return <ResponsiveDialog open onClose={onClose} title="Teklif talebi oluştur" description={`${source.documentNo} numaralı onaylı ihtiyaç için fiyat toplayın.`} className="!max-w-3xl"><div className="space-y-5">
    <div className="rounded-xl border border-cyan-500/15 bg-cyan-500/5 p-4"><p className="text-xs uppercase text-slate-500">Kaynak ihtiyaç</p><p className="mt-1 font-semibold">{source.subject}</p><p className="mt-1 text-sm text-slate-500">{source.lines.length} kalem · toplam {formatProjectNumber(source.lines.reduce((sum,x)=>sum+x.quantity,0))} birim</p></div>
    <Field label="Teklif cevap son tarihi *"><AppDateInput value={dueDate} min={today()} onChange={e=>setDueDate(e.target.value)}/></Field>
    <Field label="Tedarikçi ekle *"><PagedAppDropdown<CustomerOption> queryKey={['procurement-suppliers',branch]} fetchPage={r=>goodsReceiptV2Api.customers(r,branch)} toOption={x=>({value:encodeURIComponent(JSON.stringify(x)),label:`${x.customerCode} · ${x.customerName}`})} value={supplierValue} onValueChange={addSupplier} searchable minSearchLength={2} placeholder="Kod veya unvan ile tedarikçi ara…"/></Field>
    {suppliers.length?<div className="flex flex-wrap gap-2">{suppliers.map(x=><span key={x.id} className="inline-flex items-center gap-2 rounded-full border border-cyan-500/20 bg-cyan-500/5 px-3 py-1 text-sm">{x.customerCode} · {x.customerName}<button aria-label={`${x.customerName} tedarikçisini kaldır`} onClick={()=>setSuppliers(xs=>xs.filter(y=>y.id!==x.id))}><X size={14}/></button></span>)}</div>:<p className="rounded-lg border border-dashed border-cyan-500/20 p-3 text-sm text-slate-500">Henüz tedarikçi eklenmedi. Karşılaştırma için birden fazla tedarikçi seçebilirsiniz.</p>}
    <Field label="Tedarikçiye not"><AppInput value={message} onChange={e=>setMessage(e.target.value)} placeholder="Teslim, paketleme veya teklif koşulları…"/></Field>
    <div className="flex justify-end gap-2"><button className="btn btn-secondary" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" disabled={busy} onClick={()=>void save()}>{busy?'Oluşturuluyor…':'Teklif talebi oluştur'}</button></div>
  </div></ResponsiveDialog>;
}

function CreateQuoteDialog({source,onClose,onSaved}:{source:ProcurementDocumentDetail;onClose:()=>void;onSaved:()=>void}):ReactElement{
  const suppliers=source.suppliers??[];
  const [supplierId,setSupplierId]=useState(suppliers.length===1?String(suppliers[0].supplierId):'');
  const [quoteNo,setQuoteNo]=useState('');
  const [quoteDate,setQuoteDate]=useState(today);
  const [validUntil,setValidUntil]=useState('');
  const [currency,setCurrency]=useState('TRY');
  const [exchangeRate,setExchangeRate]=useState(1);
  const [note,setNote]=useState('');
  const [busy,setBusy]=useState(false);
  const [lines,setLines]=useState<SupplierQuoteLineInput[]>(source.lines.map(x=>({rfqLineId:x.id,quantity:x.quantity,unitPrice:0,discountRate:0,vatRate:20,deliveryDate:x.requiredDate})));
  const patchLine=(id:number,next:Partial<SupplierQuoteLineInput>)=>setLines(xs=>xs.map(x=>x.rfqLineId===id?{...x,...next}:x));
  const total=lines.reduce((sum,x)=>sum+x.quantity*x.unitPrice*(1-x.discountRate/100)*(1+x.vatRate/100),0);
  const save=async()=>{if(!supplierId||!quoteNo.trim()||exchangeRate<=0||lines.some(x=>x.quantity<=0||x.unitPrice<0)){toast.error('Tedarikçi, teklif numarası, kur ve geçerli satırlar zorunludur.');return;}setBusy(true);try{await procurementApi.createQuote(source.id,{supplierId:Number(supplierId),quoteNo,quoteDate,validUntil:validUntil||undefined,currencyCode:currency,exchangeRate,note:note||undefined,lines});onSaved();}catch(e){toast.error(e instanceof Error?e.message:'Teklif kaydedilemedi.');}finally{setBusy(false);}};
  return <ResponsiveDialog open onClose={onClose} title="Tedarikçi teklifini kaydet" description={`${source.documentNo} için gelen fiyat ve teslim koşullarını girin.`} className="!max-w-6xl"><div className="space-y-5">
    <div className="grid gap-4 md:grid-cols-3"><Field label="Tedarikçi *"><select className="app-input w-full" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Tedarikçi seçin</option>{suppliers.map(x=><option key={x.supplierId} value={x.supplierId}>{x.supplierCode} · {x.supplierName}</option>)}</select></Field><Field label="Teklif numarası *"><AppInput value={quoteNo} onChange={e=>setQuoteNo(e.target.value)} maxLength={100}/></Field><Field label="Teklif tarihi"><AppDateInput value={quoteDate} onChange={e=>setQuoteDate(e.target.value)}/></Field><Field label="Geçerlilik tarihi"><AppDateInput value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></Field><Field label="Para birimi"><AppInput value={currency} maxLength={3} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></Field><Field label="Kur"><AppInput type="number" min="0.000001" step="any" value={exchangeRate} onChange={e=>setExchangeRate(Number(e.target.value))}/></Field></div>
    <div className="space-y-3"><div className="flex items-end justify-between"><div><h3 className="font-semibold">Teklif kalemleri</h3><p className="text-xs text-slate-500">Miktar, birim fiyat, iskonto, KDV ve teslim tarihini kalem bazında girin.</p></div><p className="text-right"><span className="block text-xs uppercase text-slate-500">Teklif toplamı</span><b className="text-lg text-cyan-400">{formatProjectNumber(total)} {currency}</b></p></div>{source.lines.map((line,index)=>{const value=lines[index];return <div key={line.id} className="grid gap-3 rounded-xl border border-cyan-500/15 p-4 md:grid-cols-[minmax(220px,2fr)_100px_130px_90px_90px_140px]"><div><p className="text-xs uppercase text-slate-500">Stok</p><p className="mt-2 text-sm font-semibold">{line.stockCode?`${line.stockCode} · `:''}{line.stockName}</p></div><Field label="Miktar"><AppInput type="number" min="0.000001" step="any" value={value.quantity} onChange={e=>patchLine(line.id,{quantity:Number(e.target.value)})}/></Field><Field label="Birim fiyat"><AppInput type="number" min="0" step="any" value={value.unitPrice} onChange={e=>patchLine(line.id,{unitPrice:Number(e.target.value)})}/></Field><Field label="İskonto %"><AppInput type="number" min="0" max="100" value={value.discountRate} onChange={e=>patchLine(line.id,{discountRate:Number(e.target.value)})}/></Field><Field label="KDV %"><AppInput type="number" min="0" value={value.vatRate} onChange={e=>patchLine(line.id,{vatRate:Number(e.target.value)})}/></Field><Field label="Teslim"><AppDateInput value={value.deliveryDate??''} onChange={e=>patchLine(line.id,{deliveryDate:e.target.value||undefined})}/></Field></div>})}</div>
    <Field label="Teklif notu"><AppInput value={note} onChange={e=>setNote(e.target.value)} placeholder="Ödeme, teslim veya teklif açıklaması…"/></Field>
    <div className="flex justify-end gap-2"><button className="btn btn-secondary" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" disabled={busy} onClick={()=>void save()}>{busy?'Kaydediliyor…':'Teklifi kaydet'}</button></div>
  </div></ResponsiveDialog>;
}

function DetailDialog({detail,can,onClose,onChanged,onCreateRfq,onCreateQuote,onConverted}:{detail:ProcurementDocumentDetail;can:(permission:string)=>boolean;onClose:()=>void;onChanged:()=>Promise<void>;onCreateRfq:()=>void;onCreateQuote:()=>void;onConverted:(target:ProcurementDocumentType)=>void}):ReactElement{
  const [busy,setBusy]=useState(false);const actions=allowedActions(detail,can);
  const run=async(action:string)=>{setBusy(true);try{await procurementApi.transition(detail.documentType,detail.id,action);toast.success('Belge durumu güncellendi.');await onChanged();}catch(e){toast.error(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}};
  const convertQuote=async()=>{setBusy(true);try{await procurementApi.convertQuoteToOrder(detail.id);toast.success('Satınalma siparişi taslak olarak oluşturuldu.');onConverted('order');}catch(e){toast.error(e instanceof Error?e.message:'Sipariş oluşturulamadı.');}finally{setBusy(false);}};
  const processedLabel=detail.documentType==='request'?'RFQ’ya aktarılan':detail.documentType==='order'?'Mal kabul edilen':detail.documentType==='quote'?'—':'Teklif verilen';
  return <ResponsiveDialog open onClose={onClose} title={`${detail.documentNo} · ${detail.subject}`} description={`${formatProjectDate(detail.documentDate)} · ${statusLabel[detail.status]??detail.status}`} className="!max-w-6xl"><div className="space-y-5">
    <NextStepBanner detail={detail}/>
    <div className="grid gap-3 sm:grid-cols-4"><Info label="Tedarikçi" value={detail.counterpartyName||'Henüz seçilmedi'}/><Info label="Para birimi" value={detail.currencyCode}/><Info label="Termin" value={detail.dueDate?formatProjectDate(detail.dueDate):'—'}/><Info label="Satır" value={String(detail.lines.length)}/></div>
    {detail.suppliers?.length?<div><h3 className="mb-2 font-semibold">Davet edilen tedarikçiler</h3><div className="flex flex-wrap gap-2">{detail.suppliers.map(x=><span key={x.supplierId} className="rounded-full border border-cyan-500/20 bg-cyan-500/5 px-3 py-1 text-sm">{x.supplierCode} · {x.supplierName}</span>)}</div></div>:null}
    <div className="overflow-x-auto rounded-xl border border-cyan-500/15"><table className="w-full min-w-[760px] text-sm"><thead className="bg-cyan-500/10 text-left text-xs uppercase text-cyan-400"><tr><th className="p-3">#</th><th>Stok</th><th>Miktar</th><th>{processedLabel}</th><th>Birim fiyat</th><th>Termin</th></tr></thead><tbody>{detail.lines.map(x=><tr key={x.id} className="border-t border-cyan-500/10"><td className="p-3">{x.lineNo}</td><td>{x.stockCode?`${x.stockCode} · `:''}{x.stockName}</td><td>{formatProjectNumber(x.quantity)} {x.unitCode}</td><td>{processedLabel==='—'?'—':formatProjectNumber(x.secondaryQuantity)}</td><td>{x.unitPrice>0?`${formatProjectNumber(x.unitPrice)} ${detail.currencyCode}`:'—'}</td><td>{x.requiredDate?formatProjectDate(x.requiredDate):'—'}</td></tr>)}</tbody></table></div>
    <div><h3 className="mb-2 font-semibold">Karar geçmişi</h3><div className="space-y-2">{detail.history.length?detail.history.map((x,i)=><div key={`${x.changedAtUtc}-${i}`} className="rounded-lg border border-cyan-500/10 p-3 text-sm"><b>{(statusLabel[x.fromStatus]??x.fromStatus)||'Oluşturuldu'} → {statusLabel[x.toStatus]??x.toStatus}</b><span className="ml-3 text-slate-500">{formatProjectDateTime(x.changedAtUtc)} · Kullanıcı #{x.actorUserId}</span>{x.note?<p className="mt-1 text-slate-500">{x.note}</p>:null}</div>):<p className="text-sm text-slate-500">Henüz durum hareketi yok.</p>}</div></div>
    <div className="flex flex-wrap justify-end gap-2">{detail.documentType==='request'&&detail.status==='Approved'&&can('WMS.PROCUREMENT.RFQ.MANAGE')?<button className="btn btn-primary" disabled={busy} onClick={onCreateRfq}>Teklif talebi oluştur <ArrowRight size={16}/></button>:null}{detail.documentType==='rfq'&&(detail.status==='Sent'||detail.status==='Quoted')&&can('WMS.PROCUREMENT.QUOTE.MANAGE')?<button className="btn btn-primary" disabled={busy} onClick={onCreateQuote}><Plus size={16}/> Tedarikçi teklifi gir</button>:null}{detail.documentType==='quote'&&detail.status==='Approved'&&can('WMS.PROCUREMENT.ORDER.MANAGE')?<button className="btn btn-primary" disabled={busy} onClick={()=>void convertQuote()}>Sipariş oluştur <ArrowRight size={16}/></button>:null}{actions.map(x=><button key={x.action} className={`btn ${x.action==='cancel'||x.action==='reject'?'btn-secondary':'btn-primary'}`} disabled={busy} onClick={()=>void run(x.action)}>{x.label}</button>)}</div>
  </div></ResponsiveDialog>;
}
const allowedActions=(d:ProcurementDocumentDetail,can:(permission:string)=>boolean):Array<{action:string;label:string}>=>d.documentType==='request'?(d.status==='Draft'&&can('WMS.PROCUREMENT.REQUEST.MANAGE')?[{action:'submit',label:'Onaya gönder'}]:d.status==='PendingApproval'&&can('WMS.PROCUREMENT.APPROVE')?[{action:'approve',label:'Onayla'},{action:'reject',label:'Reddet'}]:[]):d.documentType==='order'?(d.status==='Draft'&&can('WMS.PROCUREMENT.ORDER.MANAGE')?[{action:'submit',label:'Onaya gönder'}]:d.status==='PendingApproval'&&can('WMS.PROCUREMENT.APPROVE')?[{action:'approve',label:'Onayla'},{action:'reject',label:'Taslağa döndür'}]:d.status==='Approved'&&can('WMS.PROCUREMENT.ORDER.MANAGE')?[{action:'send',label:'Tedarikçiye gönder'}]:[]):d.documentType==='rfq'&&d.status==='Draft'&&can('WMS.PROCUREMENT.RFQ.MANAGE')?[{action:'send',label:'Tedarikçilere gönder'}]:d.documentType==='quote'&&d.status==='Submitted'&&can('WMS.PROCUREMENT.APPROVE')?[{action:'approve',label:'Teklifi onayla'},{action:'reject',label:'Reddet'}]:[];
function NextStepBanner({detail}:{detail:ProcurementDocumentDetail}){const text=detail.documentType==='request'?(detail.status==='Draft'?'Sonraki adım: Talebi onaya gönderin.':detail.status==='PendingApproval'?'Onay kararı bekleniyor.':detail.status==='Approved'?'Talep hazır: Tedarikçileri seçip teklif talebi oluşturun.':detail.status==='Converted'?'Bu talep teklif sürecine aktarıldı.':'Bu talep için işlem kapandı.'):detail.documentType==='rfq'?(detail.status==='Draft'?'Sonraki adım: Teklif talebini tedarikçilere gönderin.':detail.status==='Sent'?'Tedarikçi cevaplarını teklif olarak kaydedebilirsiniz.':detail.status==='Quoted'?'En az bir teklif geldi; diğer teklifleri de kaydedebilir veya süreci kapatabilirsiniz.':'Teklif toplama süreci kapandı.'):detail.documentType==='quote'?(detail.status==='Submitted'?'Teklifi inceleyip onaylayın veya reddedin.':detail.status==='Approved'?'Teklif hazır: Satınalma siparişine dönüştürün.':detail.status==='Converted'?'Bu teklif satınalma siparişine dönüştürüldü.':'Teklif için işlem kapandı.'):(detail.status==='Draft'?'Sonraki adım: Siparişi onaya gönderin.':detail.status==='PendingApproval'?'Sipariş onay kararı bekliyor.':detail.status==='Approved'?'Siparişi tedarikçiye gönderin.':detail.status==='SentToSupplier'?'Sipariş gönderildi; mal kabul için açık kaynak belgedir.':'Sipariş süreci devam ediyor.');return <div className="rounded-xl border border-cyan-500/25 bg-cyan-500/5 p-3 text-sm text-cyan-200"><b>Şimdi ne olacak?</b><span className="ml-2 text-slate-400">{text}</span></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1 block text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</span>{children}</label>;}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-cyan-500/15 p-3"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>;}
